// Latin American Spanish idioms & useful phrases for the Idioms Test and Useful Phrases quizzes.
window.QUIZ_IDIOMS = window.QUIZ_IDIOMS || {};
window.QUIZ_IDIOMS.spanish = [
  {t:"Me importa un pepino.", e:"I couldn't care less", lit:"it matters a cucumber to me", hint:"casual; also: un comino"},
  {t:"Estar en las nubes", e:"to be daydreaming", lit:"to be in the clouds", hint:"distracted in class or a meeting"},
  {t:"Costar un ojo de la cara", e:"to cost an arm and a leg", lit:"to cost an eye from the face", hint:"anything very expensive"},
  {t:"No tener pelos en la lengua", e:"to speak one's mind bluntly", lit:"to have no hairs on the tongue", hint:"said of very direct people"},
  {t:"Tomar el pelo", e:"to pull someone's leg", lit:"to take the hair", hint:"friendly teasing, not malicious"},
  {t:"Meter la pata", e:"to put your foot in your mouth", lit:"to stick the paw in", hint:"after a social blunder or mistake"},
  {t:"Echar agua al mar", e:"to do something pointless", lit:"to throw water into the sea", hint:"wasted, redundant effort"},
  {t:"Ser pan comido", e:"to be a piece of cake", lit:"to be eaten bread", hint:"something very easy"},
  {t:"Estar como agua para chocolate", e:"to be boiling mad", lit:"to be like water for chocolate", hint:"(Mexico) water heated for hot chocolate; also a famous novel"},
  {t:"Ponerse las pilas", e:"to get one's act together", lit:"to put in one's batteries", hint:"very common pep talk: ¡ponte las pilas!"},
  {t:"Dar en el clavo", e:"to hit the nail on the head", lit:"to hit on the nail", hint:"an exactly right answer or guess"},
  {t:"Estar hasta las narices", e:"to be fed up", lit:"to be up to the nostrils", hint:"exasperation: hasta las narices de tanto ruido"},
  {t:"Hablar hasta por los codos", e:"to talk nonstop", lit:"to talk even through the elbows", hint:"said of chatterboxes"},
  {t:"No hay mal que por bien no venga", e:"every cloud has a silver lining", lit:"there is no bad that doesn't come for a good", hint:"consolation proverb after a setback"},
  {t:"Más vale tarde que nunca", e:"better late than never", lit:"late is worth more than never", hint:"when someone finally shows up or delivers"},
  {t:"Al mal tiempo, buena cara", e:"grin and bear it", lit:"to bad weather, a good face", hint:"staying positive in hard times"},
  {t:"Estar entre la espada y la pared", e:"to be between a rock and a hard place", lit:"between the sword and the wall", hint:"trapped with no good options"},
  {t:"Buscarle tres pies al gato", e:"to overcomplicate things", lit:"to look for three feet on the cat", hint:"also heard as cinco pies"},
  {t:"Tirar la toalla", e:"to throw in the towel", lit:"to throw the towel", hint:"same boxing image as English; giving up"},
  {t:"Quedarse de piedra", e:"to be stunned", lit:"to be left as stone", hint:"frozen by shocking news"},
  {t:"Ser uña y mugre", e:"to be inseparable friends", lit:"to be fingernail and grime", hint:"(LatAm) Spain says uña y carne"},
  {t:"Dormirse en los laureles", e:"to rest on one's laurels", lit:"to fall asleep on the laurels", hint:"warning against complacency after success"},
  {t:"Echar leña al fuego", e:"to add fuel to the fire", lit:"to throw firewood on the fire", hint:"making a conflict worse"},
  {t:"Hacerse de la vista gorda", e:"to turn a blind eye", lit:"to make oneself of the fat view", hint:"LatAm form with de; deliberately ignoring something"},
  {t:"No dar pie con bola", e:"to get nothing right", lit:"to not hit foot to ball", hint:"an off day: hoy no doy pie con bola"},
  {t:"Sacar de quicio", e:"to drive someone up the wall", lit:"to take off the door hinge", hint:"me sacas de quicio = you're driving me crazy"},
  {t:"Ponerse rojo como un tomate", e:"to blush deeply", lit:"to turn red as a tomato", hint:"embarrassment"},
  {t:"Ser la oveja negra", e:"to be the black sheep", lit:"to be the black sheep", hint:"the odd one out of a family or group"},
  {t:"Matar dos pájaros de un tiro", e:"to kill two birds with one stone", lit:"to kill two birds with one shot", hint:"one action, two goals"},
  {t:"A caballo regalado no se le mira el diente", e:"don't look a gift horse in the mouth", lit:"you don't look at a gift horse's tooth", hint:"accept gifts without criticizing them"},
  {t:"Camarón que se duerme se lo lleva la corriente", e:"you snooze, you lose", lit:"the shrimp that falls asleep is carried off by the current", hint:"classic Latin American proverb"},
  {t:"A quien madruga, Dios le ayuda", e:"the early bird gets the worm", lit:"God helps the one who rises early", hint:"praise for early risers and early starts"},
  {t:"Más vale pájaro en mano que cien volando", e:"a bird in the hand is worth two in the bush", lit:"a bird in hand is worth more than a hundred flying", hint:"take the sure thing"},
  {t:"Cada loco con su tema", e:"to each their own", lit:"each madman with his topic", hint:"shrugging at someone's obsession"},
  {t:"Echarle ganas", e:"to put in real effort", lit:"to throw desire at it", hint:"(LatAm) ¡échale ganas! = give it your all"},
  {t:"¡Aguas!", e:"watch out!", lit:"waters!", hint:"(Mexico) from wastewater once tossed from windows"},
  {t:"¡No manches!", e:"no way! you're kidding!", lit:"don't stain!", hint:"(Mexico) mild version of a ruder phrase"},
  {t:"Hacerse el sueco", e:"to play dumb", lit:"to act Swedish", hint:"pretending not to hear or understand"},
  {t:"Tener mala leche", e:"to have bad luck", lit:"to have bad milk", hint:"(LatAm) in Spain it means bad temper instead"},
  {t:"Estar salado", e:"to be jinxed", lit:"to be salted", hint:"(LatAm) a run of bad luck"},
  {t:"Ser buena onda", e:"to be cool, nice", lit:"to be good wave", hint:"(LatAm) people or vibes; opposite: mala onda"},
  {t:"Tirar la casa por la ventana", e:"to spare no expense", lit:"to throw the house out the window", hint:"big weddings and quinceañeras; also echar la casa..."},
  {t:"Quedarse con los brazos cruzados", e:"to sit idly by", lit:"to stay with arms crossed", hint:"criticizing inaction"},
  {t:"Poner el dedo en la llaga", e:"to touch a sore spot", lit:"to put the finger on the wound", hint:"raising the painful topic directly"},
  {t:"Andar con pies de plomo", e:"to tread very carefully", lit:"to walk with feet of lead", hint:"delicate negotiations or touchy people"},
  {t:"Estar de manteles largos", e:"to be celebrating in style", lit:"to be with long tablecloths", hint:"(Mexico) big anniversaries or feasts"},
  {t:"Dar gato por liebre", e:"to rip someone off", lit:"to give cat instead of hare", hint:"being sold a fake or inferior product"},
  {t:"Ir al grano", e:"to get to the point", lit:"to go to the grain", hint:"vamos al grano = let's cut to the chase"},
  {t:"Costar trabajo", e:"to be hard to do", lit:"to cost work", hint:"very LatAm: me cuesta trabajo levantarme temprano"},
  {t:"Valer la pena", e:"to be worth it", lit:"to be worth the sorrow", hint:"vale la pena intentarlo = it's worth a try"},
  {t:"Llover a cántaros", e:"to rain cats and dogs", lit:"to rain by the pitcherful", hint:"heavy downpour"},
  {t:"Ser el brazo derecho", e:"to be someone's right-hand person", lit:"to be the right arm", hint:"the indispensable helper"},
  {t:"No tener ni un quinto", e:"to be flat broke", lit:"to not have even a fifth (old coin)", hint:"(Mexico) also: no tener ni un peso"},
  {t:"Dar el avión", e:"to nod along without really listening", lit:"to give the airplane", hint:"(Mexico) me está dando el avión = he's just humoring me"},
  {t:"Hacer el oso", e:"to embarrass oneself", lit:"to do the bear", hint:"(Mexico, Colombia) ¡qué oso! = how embarrassing!"},
  {t:"Estar en chino", e:"to be extremely difficult", lit:"to be in Chinese", hint:"(LatAm) está en chino = it's nearly impossible"},
  {t:"A lo hecho, pecho", e:"what's done is done", lit:"to what is done, chest", hint:"face the consequences bravely"},
  {t:"En boca cerrada no entran moscas", e:"silence is golden", lit:"flies don't enter a closed mouth", hint:"advice to keep quiet"},
  {t:"Más sabe el diablo por viejo que por diablo", e:"experience beats cleverness", lit:"the devil knows more from being old than from being the devil", hint:"deference to elders' wisdom"},
  {t:"Ponerle mucha crema a sus tacos", e:"to brag, to oversell oneself", lit:"to put too much cream on one's tacos", hint:"(Mexico) said of show-offs"},
  {t:"Echar porras", e:"to cheer someone on", lit:"to throw cheers", hint:"(Mexico) te echo porras en tu examen"},
  {t:"Estar hecho polvo", e:"to be exhausted", lit:"to be turned into dust", hint:"after a brutal day or workout"},
  {t:"Quedar como anillo al dedo", e:"to suit perfectly", lit:"to fit like a ring on the finger", hint:"perfect timing or fit: me queda como anillo al dedo"},
  {t:"Ahogarse en un vaso de agua", e:"to make a mountain out of a molehill", lit:"to drown in a glass of water", hint:"overreacting to small problems"},
  {t:"Parecerse como dos gotas de agua", e:"to be like two peas in a pod", lit:"to look alike as two drops of water", hint:"identical people, often twins"},
  {t:"Tener memoria de elefante", e:"to have an excellent memory", lit:"to have an elephant's memory", hint:"never forgets anything"},
  {t:"Pedirle peras al olmo", e:"to ask the impossible", lit:"to ask the elm tree for pears", hint:"expecting what someone can't give"},
  {t:"Estar frito", e:"to be done for", lit:"to be fried", hint:"si no estudio, estoy frito"},
  {t:"Irse por las ramas", e:"to beat around the bush", lit:"to go off through the branches", hint:"avoiding the main point"},
  {t:"Tener la sartén por el mango", e:"to call the shots", lit:"to hold the frying pan by the handle", hint:"having the upper hand"},
  {t:"Tomar el toro por los cuernos", e:"to take the bull by the horns", lit:"to take the bull by the horns", hint:"confronting a problem head-on"},
  {t:"Dar lata", e:"to pester", lit:"to give tin can", hint:"kids dando lata = being a nuisance"},
  {t:"Agarrar con las manos en la masa", e:"to catch red-handed", lit:"to catch with hands in the dough", hint:"caught in the act"},
  {t:"De tal palo, tal astilla", e:"a chip off the old block", lit:"from such a stick, such a splinter", hint:"children resembling parents"},
  {t:"Hacer castillos en el aire", e:"to build castles in the air", lit:"to make castles in the air", hint:"unrealistic plans and fantasies"},
  {t:"Perder los estribos", e:"to lose one's temper", lit:"to lose the stirrups", hint:"riding image; losing control in anger"},
  {t:"Poner las cartas sobre la mesa", e:"to lay one's cards on the table", lit:"to put the cards on the table", hint:"being fully transparent"},
  {t:"Ser harina de otro costal", e:"to be a whole different story", lit:"to be flour from another sack", hint:"eso es harina de otro costal = separate issue"},
  {t:"Tener un as bajo la manga", e:"to have an ace up one's sleeve", lit:"to have an ace under the sleeve", hint:"a hidden advantage in reserve"},
  {t:"Verle la cara a alguien", e:"to take advantage of someone", lit:"to see someone's face", hint:"(LatAm) me vieron la cara = they played me for a fool"},
  {t:"Echar flores", e:"to flatter", lit:"to throw flowers", hint:"paying compliments: me echó muchas flores"},
  {t:"Media naranja", e:"better half, soulmate", lit:"half orange", hint:"mi media naranja = my significant other"},
  {t:"Estar como pez en el agua", e:"to be in one's element", lit:"to be like a fish in water", hint:"totally comfortable in a situation"},
  {t:"Quemarse las pestañas", e:"to burn the midnight oil", lit:"to burn one's eyelashes", hint:"studying late before exams"},
  {t:"Sudar la gota gorda", e:"to sweat buckets, to struggle hard", lit:"to sweat the fat drop", hint:"great effort: sudé la gota gorda para terminar"},
  {t:"No pegar el ojo", e:"to not sleep a wink", lit:"to not stick the eye", hint:"anoche no pegué el ojo"},
  {t:"Estar en boca de todos", e:"to be the talk of the town", lit:"to be in everyone's mouth", hint:"gossip and scandals"},
  {t:"Salirse con la suya", e:"to get one's way", lit:"to go off with one's own", hint:"often disapproving: siempre se sale con la suya"},
  {t:"Sacar canas verdes", e:"to drive someone up the wall with worry", lit:"to bring out green gray-hairs", hint:"(LatAm) what kids do to their parents"},
  {t:"Estar hasta el gorro", e:"to be totally fed up", lit:"to be up to the cap", hint:"(Mexico) like hasta las narices"},
  {t:"Hacer puente", e:"to take a long weekend", lit:"to make a bridge", hint:"holiday next to a weekend; el puente = the long weekend"},
  {t:"Ni modo", e:"oh well, nothing to be done", lit:"not even a way", hint:"(Mexico/LatAm) resigned acceptance"},
  {t:"Ser codo", e:"to be stingy", lit:"to be elbow", hint:"(Mexico) mimed by tapping the elbow"},
  {t:"Echar un ojo", e:"to keep an eye on", lit:"to throw an eye", hint:"échale un ojo a mis cosas = watch my stuff"},
  {t:"Quedar en veremos", e:"to be left up in the air", lit:"to remain in we-shall-see", hint:"plans that never get confirmed"},
  {t:"Hablando del rey de Roma", e:"speak of the devil", lit:"speaking of the king of Rome", hint:"when the person mentioned walks in"},
  {t:"Zapatero, a tus zapatos", e:"stick to what you know", lit:"shoemaker, to your shoes", hint:"telling someone to stay in their lane"},
  {t:"Ojos que no ven, corazón que no siente", e:"out of sight, out of mind", lit:"eyes that don't see, heart that doesn't feel", hint:"what you don't know can't hurt you"},
  {t:"Más vale prevenir que lamentar", e:"better safe than sorry", lit:"preventing is worth more than regretting", hint:"advice before taking risks"},
  {t:"Dime con quién andas y te diré quién eres", e:"you are known by the company you keep", lit:"tell me who you walk with and I'll tell you who you are", hint:"warning about bad influences"},
  {t:"A buen hambre no hay pan duro", e:"beggars can't be choosers", lit:"to good hunger there is no hard bread", hint:"hunger makes everything tasty"},
  {t:"Estar hecho una sopa", e:"to be soaked to the bone", lit:"to be turned into a soup", hint:"caught in the rain"},
  {t:"Estar como un fideo", e:"to be thin as a rail", lit:"to be like a noodle", hint:"very skinny"},
  {t:"Ser del año de la pera", e:"to be ancient", lit:"to be from the year of the pear", hint:"hopelessly outdated things"},
  {t:"Acostarse con las gallinas", e:"to go to bed very early", lit:"to go to bed with the hens", hint:"asleep at sunset"},
  {t:"A perro flaco, todo son pulgas", e:"when it rains, it pours", lit:"to a skinny dog, everything is fleas", hint:"misfortunes pile onto the unlucky"},
  {t:"Estar en la edad del pavo", e:"to be at that awkward age", lit:"to be in the turkey's age", hint:"the teenage years"},
  {t:"La curiosidad mató al gato", e:"curiosity killed the cat", lit:"curiosity killed the cat", hint:"mind your own business"},
  {t:"¿Te comió la lengua el gato?", e:"cat got your tongue?", lit:"did the cat eat your tongue?", hint:"teasing someone silent"},
  {t:"No tener ni pies ni cabeza", e:"to make no sense at all", lit:"to have neither feet nor head", hint:"an incoherent plan or story"},
  {t:"Consultar con la almohada", e:"to sleep on it", lit:"to consult with the pillow", hint:"decide tomorrow"},
  {t:"En casa del herrero, cuchillo de palo", e:"the shoemaker's children go barefoot", lit:"in the blacksmith's house, a wooden knife", hint:"experts neglect their own domain"},
  {t:"Las palabras se las lleva el viento", e:"actions speak louder than words", lit:"words are carried off by the wind", hint:"talk is cheap; get it in writing"},
  {t:"Meterse en camisa de once varas", e:"to get in over one's head", lit:"to get into an eleven-yard shirt", hint:"needless entanglement in trouble"},
  {t:"Un clavo saca otro clavo", e:"a new love cures the old one", lit:"one nail drives out another nail", hint:"rebound wisdom"},
  {t:"Despedirse a la francesa", e:"to leave without saying goodbye", lit:"to say goodbye French-style", hint:"the Irish exit, blamed on the French"},
  {t:"Dios los cría y ellos se juntan", e:"birds of a feather flock together", lit:"God raises them and they find each other", hint:"usually said disapprovingly"},
  {t:"Faltarle un tornillo", e:"to have a screw loose", lit:"to be missing a screw", hint:"le falta un tornillo — he's nuts"},
  {t:"Subirse al carro", e:"to jump on the bandwagon", lit:"to climb onto the cart", hint:"joining once it's winning"},
  {t:"Ver todo color de rosa", e:"to see everything through rose-colored glasses", lit:"to see everything rose-colored", hint:"unshakeable optimism"},
  {t:"Estar como unas castañuelas", e:"to be happy as a clam", lit:"to be like a pair of castanets", hint:"bursting with cheer"},
  {t:"Estar de mala uva", e:"to be in a foul mood", lit:"to be of bad grape", hint:"Spain; like estar de mala leche"},
  {t:"Estar hecho un ají", e:"to be hopping mad", lit:"to be turned into a chili pepper", hint:"LatAm; red with anger"},
];
window.QUIZ_PHRASES = window.QUIZ_PHRASES || {};
window.QUIZ_PHRASES.spanish = [
  {id:"restaurant", title:"Ordering at a restaurant", items:[
    {t:"¿Me trae el menú, por favor?", e:"Could you bring me the menu, please?"},
    {t:"¿Tiene una mesa para dos?", e:"Do you have a table for two?"},
    {t:"¿Qué me recomienda?", e:"What do you recommend?"},
    {t:"Quisiera ordenar, por favor.", e:"I'd like to order, please."},
    {t:"Para mí, el pollo con arroz.", e:"For me, the chicken with rice."},
    {t:"¿Este platillo pica mucho?", e:"Is this dish very spicy?"},
    {t:"Un jugo de naranja, por favor.", e:"An orange juice, please."},
    {t:"¿Me trae más agua, por favor?", e:"Could you bring me more water, please?"},
    {t:"Soy alérgico a los mariscos.", e:"I'm allergic to seafood."},
    {t:"Soy vegetariana. ¿Qué opciones tienen?", e:"I'm vegetarian. What options do you have?"},
    {t:"¿Me puede traer la cuenta, por favor?", e:"Could you bring me the check, please?"},
    {t:"¿Aceptan tarjeta de crédito?", e:"Do you take credit cards?"},
    {t:"¿La propina está incluida?", e:"Is the tip included?"},
    {t:"Todo estuvo delicioso, gracias.", e:"Everything was delicious, thank you."}
  ]},
  {id:"directions", title:"Directions & transport", items:[
    {t:"Disculpe, ¿dónde está la estación del metro?", e:"Excuse me, where is the subway station?"},
    {t:"¿Cómo llego al centro?", e:"How do I get downtown?"},
    {t:"¿Está lejos de aquí?", e:"Is it far from here?"},
    {t:"Siga derecho dos cuadras.", e:"Go straight for two blocks."},
    {t:"Doble a la derecha en el semáforo.", e:"Turn right at the traffic light."},
    {t:"¿Me puede llevar a esta dirección?", e:"Can you take me to this address?"},
    {t:"¿Cuánto cuesta el viaje al aeropuerto?", e:"How much is the ride to the airport?"},
    {t:"¿Qué autobús va al centro?", e:"Which bus goes downtown?"},
    {t:"¿Dónde puedo tomar un taxi?", e:"Where can I get a taxi?"},
    {t:"¿Cuánto tarda en llegar?", e:"How long does it take to get there?"},
    {t:"Me bajo en la próxima parada.", e:"I'm getting off at the next stop."},
    {t:"¿Me avisa cuando lleguemos, por favor?", e:"Could you let me know when we arrive, please?"},
    {t:"Estoy perdido. ¿Me puede ayudar?", e:"I'm lost. Can you help me?"},
    {t:"¿Se puede ir caminando?", e:"Can you walk there?"}
  ]},
  {id:"shopping", title:"Shopping", items:[
    {t:"¿Cuánto cuesta esto?", e:"How much does this cost?"},
    {t:"¿Lo tiene en otra talla?", e:"Do you have it in another size?"},
    {t:"¿Lo tiene en otro color?", e:"Do you have it in another color?"},
    {t:"Solo estoy mirando, gracias.", e:"I'm just looking, thanks."},
    {t:"¿Me puedo probar esto?", e:"Can I try this on?"},
    {t:"¿Dónde están los probadores?", e:"Where are the fitting rooms?"},
    {t:"¿Está en oferta?", e:"Is it on sale?"},
    {t:"Está muy caro. ¿Me puede hacer un descuento?", e:"It's very expensive. Can you give me a discount?"},
    {t:"¿Aceptan tarjeta o solo efectivo?", e:"Do you take cards or only cash?"},
    {t:"¿Me da una bolsa, por favor?", e:"Could you give me a bag, please?"},
    {t:"¿Puedo pagar en cuotas?", e:"Can I pay in installments?"},
    {t:"¿A qué hora cierran?", e:"What time do you close?"},
    {t:"Quisiera devolver esto.", e:"I'd like to return this."},
    {t:"¿Me da el recibo, por favor?", e:"Could you give me the receipt, please?"}
  ]},
  {id:"hotel", title:"Hotel & accommodation", items:[
    {t:"Tengo una reservación a nombre de García.", e:"I have a reservation under the name García."},
    {t:"Quisiera una habitación doble.", e:"I'd like a double room."},
    {t:"¿Cuánto cuesta por noche?", e:"How much is it per night?"},
    {t:"¿El desayuno está incluido?", e:"Is breakfast included?"},
    {t:"¿A qué hora es la entrada y la salida?", e:"What time are check-in and check-out?"},
    {t:"¿Me da la clave del wifi, por favor?", e:"Could you give me the wifi password, please?"},
    {t:"El aire acondicionado no funciona.", e:"The air conditioning doesn't work."},
    {t:"No hay agua caliente en mi habitación.", e:"There's no hot water in my room."},
    {t:"¿Tienen elevador?", e:"Do you have an elevator?"},
    {t:"¿Me pueden despertar a las siete, por favor?", e:"Could you wake me at seven, please?"},
    {t:"¿Pueden guardar mi equipaje hasta la tarde?", e:"Can you store my luggage until the afternoon?"},
    {t:"Quisiera hacer la salida, por favor.", e:"I'd like to check out, please."},
    {t:"¿Me puede pedir un taxi, por favor?", e:"Could you call me a taxi, please?"},
    {t:"¿Hay estacionamiento en el hotel?", e:"Is there parking at the hotel?"}
  ]},
  {id:"smalltalk", title:"Greetings & small talk", items:[
    {t:"¡Hola! ¿Cómo estás?", e:"Hi! How are you?"},
    {t:"¿Cómo le va?", e:"How's it going? (formal)"},
    {t:"Mucho gusto en conocerte.", e:"Nice to meet you."},
    {t:"¿De dónde eres?", e:"Where are you from?"},
    {t:"Soy de Estados Unidos.", e:"I'm from the United States."},
    {t:"¿A qué te dedicas?", e:"What do you do for a living?"},
    {t:"¿Cuánto tiempo llevas viviendo aquí?", e:"How long have you been living here?"},
    {t:"¡Qué calor hace hoy!", e:"It's so hot today!"},
    {t:"¿Qué tal tu fin de semana?", e:"How was your weekend?"},
    {t:"¿Me pasas tu número de celular?", e:"Can you give me your cell number?"},
    {t:"¿Ustedes son de aquí?", e:"Are you all from here?"},
    {t:"Fue un placer platicar contigo.", e:"It was a pleasure chatting with you."},
    {t:"Saludos a tu familia.", e:"Say hi to your family."},
    {t:"Nos vemos pronto. ¡Cuídate!", e:"See you soon. Take care!"}
  ]},
  {id:"emergency", title:"Emergencies & health", items:[
    {t:"¡Auxilio! ¡Ayúdenme!", e:"Help! Help me!"},
    {t:"Llamen a una ambulancia, por favor.", e:"Call an ambulance, please."},
    {t:"Necesito un doctor.", e:"I need a doctor."},
    {t:"Me duele mucho el estómago.", e:"My stomach hurts a lot."},
    {t:"Tengo fiebre y dolor de cabeza.", e:"I have a fever and a headache."},
    {t:"Soy alérgica a la penicilina.", e:"I'm allergic to penicillin."},
    {t:"¿Dónde está la farmacia más cercana?", e:"Where is the nearest pharmacy?"},
    {t:"¿Tiene algo para la gripa?", e:"Do you have something for the flu?"},
    {t:"Me robaron la cartera.", e:"My wallet was stolen."},
    {t:"Perdí mi pasaporte.", e:"I lost my passport."},
    {t:"¿Dónde está la estación de policía?", e:"Where is the police station?"},
    {t:"Fue un accidente.", e:"It was an accident."},
    {t:"¿Me puede llevar al hospital?", e:"Can you take me to the hospital?"},
    {t:"No me siento bien.", e:"I don't feel well."}
  ]},
  {id:"phone", title:"Phone & appointments", items:[
    {t:"¿Bueno? ¿Quién habla?", e:"Hello? Who's calling? (answering the phone, Mexico)"},
    {t:"¿Puedo hablar con la doctora Ramírez?", e:"May I speak with Dr. Ramírez?"},
    {t:"¿De parte de quién?", e:"Who may I say is calling?"},
    {t:"Le llamo para hacer una cita.", e:"I'm calling to make an appointment."},
    {t:"Quisiera agendar una cita para el martes.", e:"I'd like to schedule an appointment for Tuesday."},
    {t:"¿Tiene algo disponible en la mañana?", e:"Do you have anything available in the morning?"},
    {t:"Necesito cambiar mi cita.", e:"I need to change my appointment."},
    {t:"¿Me puede llamar más tarde?", e:"Can you call me later?"},
    {t:"Le marco al rato.", e:"I'll call you back in a bit."},
    {t:"Se está cortando la llamada.", e:"The call is breaking up."},
    {t:"No tengo señal aquí.", e:"I don't have a signal here."},
    {t:"¿Me manda un mensaje de texto?", e:"Can you send me a text message?"},
    {t:"Disculpe, me equivoqué de número.", e:"Sorry, I dialed the wrong number."},
    {t:"Mi número de celular es cinco, cinco, tres, dos...", e:"My cell number is five, five, three, two..."}
  ]},
  {id:"opinions", title:"Opinions & feelings", items:[
    {t:"Me parece una buena idea.", e:"It seems like a good idea to me."},
    {t:"Estoy de acuerdo contigo.", e:"I agree with you."},
    {t:"No estoy de acuerdo.", e:"I don't agree."},
    {t:"¿Tú qué opinas?", e:"What do you think?"},
    {t:"A mí me da igual.", e:"It's all the same to me."},
    {t:"Me encanta esta ciudad.", e:"I love this city."},
    {t:"Estoy muy emocionado por el viaje.", e:"I'm very excited about the trip."},
    {t:"Estoy un poco cansada.", e:"I'm a little tired."},
    {t:"Me molesta mucho el ruido.", e:"The noise really bothers me."},
    {t:"¡Qué pena!", e:"What a shame!"},
    {t:"Tengo muchas ganas de verte.", e:"I really want to see you."},
    {t:"Me preocupa llegar tarde.", e:"I'm worried about arriving late."},
    {t:"La verdad, no me convence.", e:"Honestly, it doesn't convince me."}
  ]},
  {id:"travel", title:"Travel & tickets", items:[
    {t:"Quisiera comprar un boleto a Lima.", e:"I'd like to buy a ticket to Lima."},
    {t:"¿Cuánto cuesta el boleto de ida y vuelta?", e:"How much is the round-trip ticket?"},
    {t:"¿A qué hora sale el próximo autobús?", e:"What time does the next bus leave?"},
    {t:"¿De qué puerta sale el vuelo?", e:"Which gate does the flight leave from?"},
    {t:"¿El vuelo está retrasado?", e:"Is the flight delayed?"},
    {t:"¿Dónde se documenta el equipaje?", e:"Where do you check in luggage?"},
    {t:"Quisiera un asiento junto a la ventanilla.", e:"I'd like a window seat."},
    {t:"¿Cuántas maletas puedo llevar?", e:"How many suitcases can I take?"},
    {t:"Mi equipaje no llegó.", e:"My luggage didn't arrive."},
    {t:"¿Dónde está la sala de espera?", e:"Where is the waiting room?"},
    {t:"¿Necesito visa para viajar a Brasil?", e:"Do I need a visa to travel to Brazil?"},
    {t:"¿Dónde puedo rentar un carro?", e:"Where can I rent a car?"},
    {t:"¿Puedo pagar el boleto con tarjeta?", e:"Can I pay for the ticket by card?"},
    {t:"¿Hay que hacer escala?", e:"Is there a layover?"}
  ]}
];
