// Idiom units for German, Italian and Dutch, attached to existing courses at
// load time (Irish idioms live directly in data_irish.js). Same merge pattern
// as the conjugation drills.
window.QUIZ_ADDON_UNITS = [
  { lang:"german", course:"de_a2b1", unit:{ id:"de_v_idioms", type:"vocab", title:"Vocab: Idioms & Redewendungen", items:[
    {t:"Das ist mir Wurst.", e:"I don't care (lit. that's sausage to me)"},
    {t:"Ich verstehe nur Bahnhof.", e:"it's all Greek to me (lit. I only understand train station)"},
    {t:"die Daumen drücken", e:"to keep one's fingers crossed (lit. press thumbs)"},
    {t:"Tomaten auf den Augen haben", e:"to be oblivious (lit. have tomatoes on one's eyes)"},
    {t:"um den heißen Brei herumreden", e:"to beat around the bush"},
    {t:"zwei Fliegen mit einer Klappe schlagen", e:"to kill two birds with one stone"},
    {t:"die Kirche im Dorf lassen", e:"to not get carried away (lit. leave the church in the village)"},
    {t:"Jetzt geht's um die Wurst.", e:"now it's crunch time"},
    {t:"Da liegt der Hund begraben.", e:"that's the crux of the matter (lit. that's where the dog is buried)"},
    {t:"die Nase voll haben", e:"to be fed up"},
    {t:"auf dem Holzweg sein", e:"to be on the wrong track"},
    {t:"Hals- und Beinbruch!", e:"break a leg! (lit. neck and leg fracture)"},
    {t:"ein Katzensprung", e:"a stone's throw away (lit. a cat's jump)"},
    {t:"wie ein Elefant im Porzellanladen", e:"like a bull in a china shop"},
    {t:"kein Blatt vor den Mund nehmen", e:"to speak frankly"},
    {t:"auf Wolke sieben schweben", e:"to be on cloud nine"},
    {t:"den Nagel auf den Kopf treffen", e:"to hit the nail on the head"},
    {t:"aus einer Mücke einen Elefanten machen", e:"to make a mountain out of a molehill"},
    {t:"Schwein haben", e:"to be lucky (lit. to have pig)"},
    {t:"fix und fertig sein", e:"to be completely exhausted"},
    {t:"blaumachen", e:"to skip work or school"},
    {t:"die Ohren spitzen", e:"to prick up one's ears"},
    {t:"unter vier Augen", e:"in private (lit. under four eyes)"},
    {t:"Übung macht den Meister.", e:"practice makes perfect"},
    {t:"Morgenstund hat Gold im Mund.", e:"the early bird catches the worm"}
  ]}},
  { lang:"italian", course:"it_b1b2", unit:{ id:"it_v_idioms", type:"vocab", title:"Vocab: Modi di dire (idioms)", items:[
    {t:"In bocca al lupo!", e:"good luck! (lit. into the wolf's mouth — answer: Crepi!)"},
    {t:"Non vedo l'ora.", e:"I can't wait (lit. I don't see the hour)"},
    {t:"costare un occhio della testa", e:"to cost an arm and a leg (lit. an eye from the head)"},
    {t:"essere al verde", e:"to be broke (lit. to be at the green)"},
    {t:"prendere due piccioni con una fava", e:"to kill two birds with one stone (two pigeons, one bean)"},
    {t:"avere la testa fra le nuvole", e:"to have one's head in the clouds"},
    {t:"in quattro e quattr'otto", e:"in a flash (lit. in four and four-is-eight)"},
    {t:"Piove sul bagnato.", e:"when it rains, it pours (lit. it rains on the wet)"},
    {t:"essere in gamba", e:"to be smart / on the ball (lit. to be in leg)"},
    {t:"Acqua in bocca!", e:"mum's the word! (lit. water in the mouth)"},
    {t:"cadere dalle nuvole", e:"to be taken completely by surprise (lit. fall from the clouds)"},
    {t:"ogni morte di papa", e:"once in a blue moon (lit. every death of a pope)"},
    {t:"toccare ferro", e:"to knock on wood (lit. touch iron)"},
    {t:"rompere il ghiaccio", e:"to break the ice"},
    {t:"avere le mani bucate", e:"to spend money like water (lit. have holes in one's hands)"},
    {t:"Meglio tardi che mai.", e:"better late than never"},
    {t:"Chi dorme non piglia pesci.", e:"the early bird catches the worm (who sleeps catches no fish)"},
    {t:"avere fegato", e:"to have guts (lit. to have liver)"},
    {t:"Magari!", e:"if only! / I wish!"},
    {t:"Boh!", e:"no idea! (colloquial shrug)"},
    {t:"Che figata!", e:"how cool! (colloquial)"},
    {t:"Mi raccomando!", e:"please do! / don't forget! (urging)"},
    {t:"Non c'è male.", e:"not bad (reply to 'how are you')"},
    {t:"fare il ponte", e:"to take a long weekend (lit. make the bridge)"},
    {t:"la dolce vita", e:"the sweet life"}
  ]}},
  { lang:"dutch", course:"nl_speak", unit:{ id:"nl_v_idioms", type:"vocab", title:"Vocab: Uitdrukkingen (idioms)", items:[
    {t:"Helaas pindakaas.", e:"too bad! (lit. unfortunately peanut butter)"},
    {t:"Nu komt de aap uit de mouw.", e:"now the truth comes out (lit. the monkey comes out of the sleeve)"},
    {t:"met de deur in huis vallen", e:"to get straight to the point (lit. fall into the house with the door)"},
    {t:"de koe bij de horens vatten", e:"to take the bull by the horns (lit. the cow)"},
    {t:"Het regent pijpenstelen.", e:"it's raining cats and dogs (lit. pipe stems)"},
    {t:"een appeltje voor de dorst", e:"a nest egg / savings (lit. a little apple for the thirst)"},
    {t:"iets onder de knie hebben", e:"to have mastered something (lit. have it under the knee)"},
    {t:"door de mand vallen", e:"to be found out (lit. fall through the basket)"},
    {t:"op hete kolen zitten", e:"to be on tenterhooks (lit. sit on hot coals)"},
    {t:"een kat in de zak kopen", e:"to buy a pig in a poke (lit. a cat in the bag)"},
    {t:"over koetjes en kalfjes praten", e:"to make small talk (lit. talk about little cows and calves)"},
    {t:"Hoge bomen vangen veel wind.", e:"high positions attract criticism (tall trees catch much wind)"},
    {t:"Wie A zegt, moet ook B zeggen.", e:"if you start something, finish it"},
    {t:"twee vliegen in één klap slaan", e:"to kill two birds with one stone (two flies in one blow)"},
    {t:"Het is koek en ei.", e:"they get along great (lit. it's cake and egg)"},
    {t:"De kogel is door de kerk.", e:"the decision has finally been made (the bullet is through the church)"},
    {t:"Oost west, thuis best.", e:"home sweet home (east west, home is best)"},
    {t:"De appel valt niet ver van de boom.", e:"the apple doesn't fall far from the tree"},
    {t:"Nou breekt mijn klomp!", e:"well, I never! (lit. now my clog breaks)"},
    {t:"niet voor de poes", e:"not to be trifled with (lit. not for the cat)"},
    {t:"een frisse neus halen", e:"to get some fresh air (lit. fetch a fresh nose)"},
    {t:"iemand achter de broek zitten", e:"to keep someone on their toes (lit. sit behind someone's pants)"},
    {t:"Dat is andere koek.", e:"that's a different story (lit. that's different cake)"},
    {t:"uit je dak gaan", e:"to go wild with excitement (lit. go out of your roof)"},
    {t:"Beter één vogel in de hand dan tien in de lucht.", e:"a bird in the hand is worth two in the bush (ten in the air)"}
  ]}}
];
