// Dutch idioms & useful phrases for the Idioms Test and Useful Phrases quizzes.
window.QUIZ_IDIOMS = window.QUIZ_IDIOMS || {};
window.QUIZ_IDIOMS.dutch = [
  {t:"Nu komt de aap uit de mouw.", e:"now the truth comes out", lit:"now the monkey comes out of the sleeve", hint:"when a hidden motive is revealed"},
  {t:"De kogel is door de kerk.", e:"the decision has finally been made", lit:"the bullet is through the church", hint:"after long hesitation, something is settled for good"},
  {t:"Met de deur in huis vallen", e:"to get straight to the point", lit:"to fall into the house with the door", hint:"often as an apology: 'om maar meteen met de deur in huis te vallen...'"},
  {t:"Iets onder de knie hebben", e:"to have mastered something", lit:"to have something under the knee", hint:"used for skills: a language, driving, a program"},
  {t:"De koe bij de horens vatten", e:"to take the bull by the horns", lit:"to grab the cow by the horns", hint:"tackle a problem head-on instead of postponing it"},
  {t:"Appeltje-eitje", e:"a piece of cake, very easy", lit:"little apple, little egg", hint:"informal; 'dat is appeltje-eitje voor mij'"},
  {t:"Over koetjes en kalfjes praten", e:"to make small talk", lit:"to talk about little cows and little calves", hint:"chatting about nothing in particular"},
  {t:"Het regent pijpenstelen.", e:"it's raining cats and dogs", lit:"it's raining pipe stems", hint:"very heavy rain — a very Dutch complaint"},
  {t:"Een appeltje met iemand te schillen hebben", e:"to have a bone to pick with someone", lit:"to have a little apple to peel with someone", hint:"you want to confront someone about a grievance"},
  {t:"Twee vliegen in één klap slaan", e:"to kill two birds with one stone", lit:"to hit two flies in one blow", hint:"achieve two goals with one action"},
  {t:"Een kat in de zak kopen", e:"to buy a pig in a poke, make a bad purchase", lit:"to buy a cat in the bag", hint:"you were deceived about what you bought"},
  {t:"Iemand blij maken met een dode mus", e:"to raise someone's hopes for nothing", lit:"to make someone happy with a dead sparrow", hint:"a promise or gift that turns out to be worthless"},
  {t:"Een oogje in het zeil houden", e:"to keep an eye on things", lit:"to keep a little eye on the sail", hint:"watch over children, a house, a situation"},
  {t:"De handen uit de mouwen steken", e:"to roll up your sleeves and get to work", lit:"to stick the hands out of the sleeves", hint:"stop talking, start doing"},
  {t:"Iets met een korreltje zout nemen", e:"to take something with a grain of salt", lit:"to take something with a little grain of salt", hint:"don't believe it too literally"},
  {t:"Het is koek en ei tussen hen.", e:"they get along wonderfully", lit:"it is cake and egg between them", hint:"often negated: 'het is niet allemaal koek en ei'"},
  {t:"Roet in het eten gooien", e:"to spoil the plans", lit:"to throw soot into the food", hint:"an unexpected problem ruins something planned"},
  {t:"De knoop doorhakken", e:"to make the final decision", lit:"to chop through the knot", hint:"end a period of doubt by deciding"},
  {t:"Iemand om de tuin leiden", e:"to deceive someone, lead someone up the garden path", lit:"to lead someone around the garden", hint:"mislead someone deliberately"},
  {t:"Boter bij de vis", e:"cash on the spot, pay up immediately", lit:"butter with the fish", hint:"demanding immediate payment or proof"},
  {t:"Er geen doekjes om winden", e:"to not mince words", lit:"to wind no little cloths around it", hint:"say it bluntly, without softening"},
  {t:"Als een olifant in een porseleinkast", e:"like a bull in a china shop", lit:"like an elephant in a porcelain cabinet", hint:"clumsy or tactless behavior in a delicate situation"},
  {t:"Iets voor een appel en een ei kopen", e:"to buy something dirt cheap", lit:"to buy something for an apple and an egg", hint:"a bargain; almost nothing was paid"},
  {t:"Nu breekt mijn klomp!", e:"well, I never! I'm flabbergasted", lit:"now my clog breaks", hint:"exclamation of total astonishment"},
  {t:"Op grote voet leven", e:"to live beyond one's means, extravagantly", lit:"to live on a big foot", hint:"spending lavishly"},
  {t:"Iemand achter de broek zitten", e:"to keep pressuring someone to act", lit:"to sit behind someone's trousers", hint:"chasing someone up about unfinished work"},
  {t:"Het paard achter de wagen spannen", e:"to go about it the wrong way around", lit:"to hitch the horse behind the wagon", hint:"a counterproductive approach"},
  {t:"Water naar de zee dragen", e:"to do something utterly pointless", lit:"to carry water to the sea", hint:"like 'carrying coals to Newcastle'"},
  {t:"Tegen de lamp lopen", e:"to get caught", lit:"to walk into the lamp", hint:"a wrongdoer is finally exposed"},
  {t:"Door de mand vallen", e:"to be found out, exposed", lit:"to fall through the basket", hint:"a lie or pretense collapses"},
  {t:"Het onderste uit de kan willen", e:"to want the absolute maximum", lit:"to want the bottom-most out of the jug", hint:"warning: 'wie het onderste uit de kan wil, krijgt het lid op de neus'"},
  {t:"Van een mug een olifant maken", e:"to make a mountain out of a molehill", lit:"to make an elephant out of a mosquito", hint:"blowing a small issue out of proportion"},
  {t:"De kat uit de boom kijken", e:"to wait and see before acting", lit:"to watch the cat out of the tree", hint:"cautiously observing before committing"},
  {t:"Iemand de les lezen", e:"to lecture someone, tell someone off", lit:"to read someone the lesson", hint:"a superior tone of reprimand"},
  {t:"Met je neus in de boter vallen", e:"to arrive at exactly the right moment", lit:"to fall with your nose into the butter", hint:"lucky timing, e.g. arriving just as dinner is served"},
  {t:"Een gat in de lucht springen", e:"to jump for joy", lit:"to jump a hole in the air", hint:"extreme happiness about news"},
  {t:"Iets in de doofpot stoppen", e:"to cover something up", lit:"to put something into the extinguishing pot", hint:"hushing up a scandal"},
  {t:"Ergens een hard hoofd in hebben", e:"to have serious doubts something will succeed", lit:"to have a hard head in something", hint:"pessimistic expectation: 'ik heb er een hard hoofd in'"},
  {t:"Buiten de boot vallen", e:"to miss out, be left out", lit:"to fall outside the boat", hint:"excluded from a group, subsidy, selection"},
  {t:"De boot afhouden", e:"to stall, keep something at arm's length", lit:"to hold off the boat", hint:"avoiding commitment to a proposal"},
  {t:"In het diepe gegooid worden", e:"to be thrown in at the deep end", lit:"to be thrown into the deep", hint:"starting something hard without preparation"},
  {t:"Zijn eigen boontjes doppen", e:"to look after oneself, manage alone", lit:"to shell his own little beans", hint:"independence: no help needed"},
  {t:"De kip met de gouden eieren slachten", e:"to kill the goose that lays the golden eggs", lit:"to slaughter the chicken with the golden eggs", hint:"destroying your own source of profit"},
  {t:"Er als de kippen bij zijn", e:"to be very quick off the mark", lit:"to be there like the chickens", hint:"reacting immediately to an opportunity"},
  {t:"Een vinger in de pap hebben", e:"to have a say, have influence", lit:"to have a finger in the porridge", hint:"involvement in decisions"},
  {t:"Hoge bomen vangen veel wind.", e:"prominent people attract much criticism", lit:"tall trees catch a lot of wind", hint:"said about public figures under fire"},
  {t:"De spijker op de kop slaan", e:"to hit the nail on the head", lit:"to hit the nail on the head", hint:"a remark that is exactly right"},
  {t:"Oude koeien uit de sloot halen", e:"to rake up old grievances", lit:"to pull old cows out of the ditch", hint:"bringing up things long settled"},
  {t:"Het neusje van de zalm", e:"the very best, the pick of the bunch", lit:"the little nose of the salmon", hint:"top quality"},
  {t:"Voor spek en bonen meedoen", e:"to take part without really counting", lit:"to join in for bacon and beans", hint:"participating but your result doesn't matter"},
  {t:"Iemand een hak zetten", e:"to play a nasty trick on someone", lit:"to set someone a heel", hint:"deliberately harming someone's interests"},
  {t:"Met de gebakken peren zitten", e:"to be stuck with the mess", lit:"to sit with the baked pears", hint:"left to deal with the unpleasant consequences"},
  {t:"De wind van voren krijgen", e:"to get a severe telling-off", lit:"to get the wind from the front", hint:"facing harsh criticism"},
  {t:"Uit de school klappen", e:"to tell tales, leak secrets", lit:"to clap out of school", hint:"revealing confidential information"},
  {t:"Een blok aan het been", e:"a millstone around one's neck, a burden", lit:"a block on the leg", hint:"something or someone that holds you back"},
  {t:"Iets op je lever hebben", e:"to have something weighing on you", lit:"to have something on your liver", hint:"asking: 'wat heb je op je lever?' = what's bothering you?"},
  {t:"Geen blad voor de mond nemen", e:"to speak one's mind frankly", lit:"to take no leaf in front of the mouth", hint:"blunt, unfiltered speaking"},
  {t:"Het loopt de spuigaten uit.", e:"it's getting completely out of hand", lit:"it runs out of the scuppers", hint:"a situation has become intolerable"},
  {t:"Iets aan je laars lappen", e:"to flout, blatantly ignore something", lit:"to patch something onto your boot", hint:"typically rules or advice being ignored"},
  {t:"Iemand op de kast jagen", e:"to wind someone up, provoke someone", lit:"to chase someone onto the cupboard", hint:"teasing until someone gets angry"},
  {t:"Van de hak op de tak springen", e:"to jump from one subject to another", lit:"to jump from the heel to the branch", hint:"an unstructured, rambling conversation"},
  {t:"In zijn vuistje lachen", e:"to laugh up one's sleeve", lit:"to laugh in his little fist", hint:"secret satisfaction at someone else's expense"},
  {t:"Een frisse neus halen", e:"to get a breath of fresh air", lit:"to fetch a fresh nose", hint:"a short walk outside"},
  {t:"Op zijn tandvlees lopen", e:"to be utterly exhausted", lit:"to walk on his gums", hint:"running on empty, at the end of one's strength"},
  {t:"Het over een andere boeg gooien", e:"to try a completely different approach", lit:"to throw it over another tack", hint:"sailing term; changing strategy"},
  {t:"Iemand in de maling nemen", e:"to pull someone's leg, fool someone", lit:"to take someone into the grinding", hint:"joking deception: 'neem je me in de maling?'"},
  {t:"De mist ingaan", e:"to go wrong, fail", lit:"to go into the fog", hint:"a plan or performance that flops"},
  {t:"Op rozen zitten", e:"to be sitting pretty", lit:"to sit on roses", hint:"often negated: 'hij zit niet op rozen'"},
  {t:"Niet op zijn mondje gevallen zijn", e:"to be quick-witted, never at a loss for words", lit:"not to have fallen on his little mouth", hint:"a compliment about verbal sharpness"},
  {t:"De plank misslaan", e:"to be wide of the mark, get it wrong", lit:"to strike the plank wrongly", hint:"a completely mistaken judgment"},
  {t:"Iets uit de mouw schudden", e:"to produce something effortlessly", lit:"to shake something out of the sleeve", hint:"improvising with apparent ease"},
  {t:"Aan de bak komen", e:"to get work, get a chance", lit:"to get to the tray", hint:"informal; finding a job or opportunity"},
  {t:"De bloemetjes buitenzetten", e:"to paint the town red", lit:"to put the little flowers outside", hint:"going out and celebrating exuberantly"},
  {t:"Een boekje opendoen over iemand", e:"to dish the dirt on someone", lit:"to open a little book about someone", hint:"revealing unflattering facts"},
  {t:"Met twee maten meten", e:"to apply double standards", lit:"to measure with two measures", hint:"judging comparable cases unequally"},
  {t:"Het zekere voor het onzekere nemen", e:"to play it safe", lit:"to take the certain over the uncertain", hint:"choosing the risk-free option"},
  {t:"Iemand aan de tand voelen", e:"to grill someone, question closely", lit:"to feel someone's tooth", hint:"a probing interrogation"},
  {t:"Zijn hart luchten", e:"to get something off one's chest", lit:"to air his heart", hint:"talking about what troubles you"},
  {t:"Achter het net vissen", e:"to miss out, arrive too late", lit:"to fish behind the net", hint:"the opportunity is already gone"},
  {t:"Iets onder de loep nemen", e:"to examine something closely", lit:"to take something under the magnifying glass", hint:"careful scrutiny of a plan or proposal"},
  {t:"Het kind van de rekening zijn", e:"to be the one who pays the price", lit:"to be the child of the bill", hint:"the innocent party who suffers"},
  {t:"Een storm in een glas water", e:"a storm in a teacup", lit:"a storm in a glass of water", hint:"a fuss about nothing"},
  {t:"Een klap van de molen gekregen hebben", e:"to be a bit crazy", lit:"to have received a blow from the mill", hint:"informal; someone acting bizarrely"},
  {t:"Ergens brood in zien", e:"to see money-making potential in something", lit:"to see bread in something", hint:"a promising business opportunity"},
  {t:"Zoete broodjes bakken", e:"to eat humble pie, act ingratiatingly", lit:"to bake sweet little bread rolls", hint:"suddenly meek after being confronted"},
  {t:"De lakens uitdelen", e:"to call the shots, be the boss", lit:"to hand out the sheets", hint:"who is really in charge"},
  {t:"Het is in kannen en kruiken.", e:"it's all settled, signed and sealed", lit:"it is in jugs and pitchers", hint:"a deal or arrangement is finalized"},
  {t:"Er met de pet naar gooien", e:"to make a half-hearted effort", lit:"to throw the cap at it", hint:"sloppy, careless work"},
  {t:"De hond in de pot vinden", e:"to arrive too late for dinner", lit:"to find the dog in the pot", hint:"all the food is already gone"},
  {t:"Het achterste van je tong niet laten zien", e:"to not reveal everything you think", lit:"to not show the hindmost part of your tongue", hint:"holding back your true opinion"},
  {t:"Uit je slof schieten", e:"to lose your temper suddenly", lit:"to shoot out of your slipper", hint:"an unexpected outburst of anger"},
  {t:"Het gras voor iemands voeten wegmaaien", e:"to beat someone to it, steal their thunder", lit:"to mow away the grass in front of someone's feet", hint:"doing first what someone else planned to do"},
  {t:"Met je mond vol tanden staan", e:"to be speechless, at a loss for words", lit:"to stand with your mouth full of teeth", hint:"unable to reply at the crucial moment"},
  {t:"Iemand het vuur na aan de schenen leggen", e:"to put someone under intense pressure", lit:"to lay the fire close to someone's shins", hint:"grilling someone with hard questions"},
  {t:"De kastanjes uit het vuur halen", e:"to do someone else's dirty work", lit:"to pull the chestnuts out of the fire", hint:"taking risks so another can profit"},
  {t:"Op eieren lopen", e:"to walk on eggshells", lit:"to walk on eggs", hint:"acting very cautiously to avoid conflict"},
  {t:"Het varkentje wel even wassen", e:"to take care of the job easily", lit:"to just wash the little pig", hint:"confident promise: 'ik zal dat varkentje wel even wassen'"},
  {t:"Op het puntje van je stoel zitten", e:"to be on the edge of your seat", lit:"to sit on the tip of your chair", hint:"full of tension or excitement"},
  {t:"Zich met hand en tand verzetten", e:"to fight tooth and nail", lit:"to resist with hand and tooth", hint:"fierce resistance to a change"},
  {t:"Iets door de vingers zien", e:"to turn a blind eye to something", lit:"to see something through the fingers", hint:"tolerating a small offense"},
  {t:"Op hete kolen zitten", e:"to be on tenterhooks, very impatient", lit:"to sit on hot coals", hint:"anxiously waiting, eager to leave"},
  {t:"De eerste viool spelen", e:"to play first fiddle, dominate", lit:"to play the first violin", hint:"who takes the leading role"},
  {t:"Iets onder vier ogen bespreken", e:"to discuss something in private", lit:"to discuss something under four eyes", hint:"a one-on-one confidential talk"},
  {t:"Het hoofd boven water houden", e:"to keep one's head above water", lit:"to keep the head above water", hint:"barely surviving financially"},
  {t:"Iemand de wind uit de zeilen nemen", e:"to take the wind out of someone's sails", lit:"to take the wind out of someone's sails", hint:"pre-empting someone's argument or plan"}
];
window.QUIZ_PHRASES = window.QUIZ_PHRASES || {};
window.QUIZ_PHRASES.dutch = [
  {id:"restaurant", title:"Ordering at a restaurant", items:[
    {t:"Mag ik de menukaart, alstublieft?", e:"May I have the menu, please?"},
    {t:"Heeft u een tafel voor twee personen?", e:"Do you have a table for two people?"},
    {t:"Ik wil graag een tafel reserveren voor vanavond.", e:"I would like to reserve a table for tonight."},
    {t:"Wat kunt u aanbevelen?", e:"What can you recommend?"},
    {t:"Ik neem de dagschotel.", e:"I'll have the dish of the day."},
    {t:"Is dit gerecht vegetarisch?", e:"Is this dish vegetarian?"},
    {t:"Ik ben allergisch voor noten.", e:"I am allergic to nuts."},
    {t:"Mag ik nog een glas water?", e:"May I have another glass of water?"},
    {t:"Het eten was heerlijk.", e:"The food was delicious."},
    {t:"Mag ik de rekening, alstublieft?", e:"May I have the bill, please?"},
    {t:"Kunnen we apart betalen?", e:"Can we pay separately?"},
    {t:"Kan ik met pin betalen?", e:"Can I pay by debit card?"},
    {t:"Is de fooi inbegrepen?", e:"Is the tip included?"},
    {t:"Eet smakelijk!", e:"Enjoy your meal!"}
  ]},
  {id:"directions", title:"Directions & transport", items:[
    {t:"Pardon, hoe kom ik bij het station?", e:"Excuse me, how do I get to the station?"},
    {t:"Is het ver lopen?", e:"Is it far to walk?"},
    {t:"Ga rechtdoor en sla dan linksaf.", e:"Go straight ahead and then turn left."},
    {t:"Bij het stoplicht gaat u rechtsaf.", e:"At the traffic light you turn right."},
    {t:"Welke tram gaat naar het centrum?", e:"Which tram goes to the city center?"},
    {t:"Waar is de dichtstbijzijnde bushalte?", e:"Where is the nearest bus stop?"},
    {t:"Moet ik overstappen?", e:"Do I have to change (transfer)?"},
    {t:"Bij welke halte moet ik uitstappen?", e:"At which stop do I have to get off?"},
    {t:"Hoe laat vertrekt de laatste trein?", e:"What time does the last train leave?"},
    {t:"Ik ben verdwaald.", e:"I am lost."},
    {t:"Kunt u het op de kaart aanwijzen?", e:"Can you point it out on the map?"},
    {t:"Is deze plaats vrij?", e:"Is this seat free?"},
    {t:"Waar kan ik een OV-chipkaart kopen?", e:"Where can I buy a public transport card?"}
  ]},
  {id:"shopping", title:"Shopping", items:[
    {t:"Hoeveel kost dit?", e:"How much does this cost?"},
    {t:"Ik kijk alleen even rond.", e:"I'm just looking around."},
    {t:"Heeft u dit in een andere maat?", e:"Do you have this in another size?"},
    {t:"Mag ik dit passen?", e:"May I try this on?"},
    {t:"Waar zijn de paskamers?", e:"Where are the fitting rooms?"},
    {t:"Dat is te duur voor mij.", e:"That is too expensive for me."},
    {t:"Is dit in de aanbieding?", e:"Is this on special offer?"},
    {t:"Ik neem deze.", e:"I'll take this one."},
    {t:"Kan ik het ruilen als het niet past?", e:"Can I exchange it if it doesn't fit?"},
    {t:"Mag ik het bonnetje?", e:"May I have the receipt?"},
    {t:"Heeft u een tasje voor me?", e:"Do you have a bag for me?"},
    {t:"Hoe laat gaat de winkel dicht?", e:"What time does the shop close?"},
    {t:"Ik zoek een cadeautje voor een vriend.", e:"I'm looking for a little gift for a friend."}
  ]},
  {id:"hotel", title:"Hotel & accommodation", items:[
    {t:"Ik heb een kamer gereserveerd op naam van De Vries.", e:"I have booked a room under the name De Vries."},
    {t:"Heeft u nog een kamer vrij voor vannacht?", e:"Do you still have a room available for tonight?"},
    {t:"Is het ontbijt inbegrepen?", e:"Is breakfast included?"},
    {t:"Hoe laat is het ontbijt?", e:"What time is breakfast?"},
    {t:"Hoe laat moet ik uitchecken?", e:"What time do I have to check out?"},
    {t:"Wat is het wachtwoord van de wifi?", e:"What is the wifi password?"},
    {t:"De verwarming doet het niet.", e:"The heating doesn't work."},
    {t:"Er is geen warm water.", e:"There is no hot water."},
    {t:"Kunt u mij om zeven uur wekken?", e:"Could you wake me at seven o'clock?"},
    {t:"Mag ik mijn bagage hier laten staan?", e:"May I leave my luggage here?"},
    {t:"Kunt u een taxi voor mij bellen?", e:"Could you call a taxi for me?"},
    {t:"Ik wil graag nog een nacht blijven.", e:"I would like to stay one more night."},
    {t:"De kamer is niet schoongemaakt.", e:"The room has not been cleaned."}
  ]},
  {id:"smalltalk", title:"Greetings & small talk", items:[
    {t:"Goedemorgen! Hoe gaat het met u?", e:"Good morning! How are you? (formal)"},
    {t:"Goed, dank u. En met u?", e:"Fine, thank you. And you?"},
    {t:"Ik heet Jan. Hoe heet jij?", e:"My name is Jan. What's your name?"},
    {t:"Aangenaam kennis te maken.", e:"Nice to meet you."},
    {t:"Waar kom je vandaan?", e:"Where are you from?"},
    {t:"Ik kom uit de Verenigde Staten.", e:"I come from the United States."},
    {t:"Ik spreek een beetje Nederlands.", e:"I speak a little Dutch."},
    {t:"Kunt u iets langzamer praten?", e:"Could you speak a little more slowly?"},
    {t:"Wat voor werk doe je?", e:"What do you do for a living?"},
    {t:"Lekker weertje, hè?", e:"Nice weather, isn't it?"},
    {t:"Heb je een fijn weekend gehad?", e:"Did you have a nice weekend?"},
    {t:"Tot ziens!", e:"Goodbye! / See you!"},
    {t:"Tot morgen!", e:"See you tomorrow!"},
    {t:"Doe de groeten aan je familie.", e:"Give my regards to your family."}
  ]},
  {id:"emergency", title:"Emergencies & health", items:[
    {t:"Help!", e:"Help!"},
    {t:"Bel een ambulance!", e:"Call an ambulance!"},
    {t:"Bel de politie!", e:"Call the police!"},
    {t:"Ik voel me niet lekker.", e:"I don't feel well."},
    {t:"Ik heb hoofdpijn.", e:"I have a headache."},
    {t:"Ik heb buikpijn.", e:"I have a stomachache."},
    {t:"Ik moet naar een dokter.", e:"I need to see a doctor."},
    {t:"Waar is de dichtstbijzijnde apotheek?", e:"Where is the nearest pharmacy?"},
    {t:"Ik ben mijn paspoort verloren.", e:"I have lost my passport."},
    {t:"Mijn portemonnee is gestolen.", e:"My wallet has been stolen."},
    {t:"Ik ben allergisch voor penicilline.", e:"I am allergic to penicillin."},
    {t:"Heeft u iets tegen de pijn?", e:"Do you have something for the pain?"},
    {t:"Het is een noodgeval.", e:"It is an emergency."},
    {t:"Waar is de eerste hulp?", e:"Where is the emergency room?"}
  ]},
  {id:"phone", title:"Phone & appointments", items:[
    {t:"Met Jan de Vries.", e:"Jan de Vries speaking. (how the Dutch answer the phone)"},
    {t:"Ik wil graag een afspraak maken.", e:"I would like to make an appointment."},
    {t:"Wanneer schikt het u?", e:"When would suit you?"},
    {t:"Schikt maandag om tien uur?", e:"Does Monday at ten o'clock suit you?"},
    {t:"Ik moet de afspraak helaas verzetten.", e:"Unfortunately I have to reschedule the appointment."},
    {t:"Ik moet de afspraak afzeggen.", e:"I have to cancel the appointment."},
    {t:"Kunt u mij doorverbinden met mevrouw Jansen?", e:"Could you put me through to Mrs. Jansen?"},
    {t:"Kunt u dat spellen, alstublieft?", e:"Could you spell that, please?"},
    {t:"Ik bel u morgen terug.", e:"I will call you back tomorrow."},
    {t:"Sorry, ik heb het verkeerde nummer gebeld.", e:"Sorry, I dialed the wrong number."},
    {t:"Kunt u een boodschap doorgeven?", e:"Could you pass on a message?"},
    {t:"De verbinding is slecht.", e:"The connection is bad."},
    {t:"Ik sta in de file, ik kom iets later.", e:"I'm stuck in traffic, I'll be a little late."}
  ]},
  {id:"opinions", title:"Opinions & feelings", items:[
    {t:"Ik vind het een goed idee.", e:"I think it's a good idea."},
    {t:"Ik ben het met je eens.", e:"I agree with you."},
    {t:"Ik ben het er niet mee eens.", e:"I don't agree with it."},
    {t:"Wat vind jij ervan?", e:"What do you think of it?"},
    {t:"Volgens mij klopt dat niet.", e:"In my opinion, that's not right."},
    {t:"Dat maakt mij niet uit.", e:"I don't mind. / It doesn't matter to me."},
    {t:"Ik twijfel nog.", e:"I'm still not sure."},
    {t:"Ik kijk ernaar uit.", e:"I'm looking forward to it."},
    {t:"Ik heb er zin in!", e:"I'm excited about it! / I can't wait!"},
    {t:"Ik maak me zorgen.", e:"I'm worried."},
    {t:"Dat valt me tegen.", e:"That's disappointing (worse than I expected)."},
    {t:"Dat valt me mee.", e:"That's better than I expected."},
    {t:"Het spijt me echt.", e:"I'm really sorry."},
    {t:"Wat jammer!", e:"What a pity!"}
  ]},
  {id:"travel", title:"Travel & tickets", items:[
    {t:"Een retourtje Amsterdam, alstublieft.", e:"A return ticket to Amsterdam, please."},
    {t:"Een enkele reis naar Utrecht, graag.", e:"A one-way ticket to Utrecht, please."},
    {t:"Van welk spoor vertrekt de trein?", e:"From which platform does the train leave?"},
    {t:"Hoe laat vertrekt de volgende trein naar Rotterdam?", e:"What time does the next train to Rotterdam leave?"},
    {t:"Is deze trein direct of moet ik overstappen?", e:"Is this train direct or do I have to change?"},
    {t:"De trein heeft vertraging.", e:"The train is delayed."},
    {t:"Vergeet niet in te checken met uw OV-chipkaart.", e:"Don't forget to check in with your public transport card."},
    {t:"Waar is de bagageband?", e:"Where is the baggage claim?"},
    {t:"Hoeveel bagage mag ik meenemen?", e:"How much luggage may I take with me?"},
    {t:"Ik wil graag een stoel bij het raam.", e:"I would like a window seat."},
    {t:"Gaat deze bus naar het vliegveld?", e:"Does this bus go to the airport?"},
    {t:"Hoe lang duurt de reis?", e:"How long does the journey take?"},
    {t:"Waar kan ik een fiets huren?", e:"Where can I rent a bicycle?"}
  ]}
];
