// Italian idioms & useful phrases for the Idioms Test and Useful Phrases quizzes.
window.QUIZ_IDIOMS = window.QUIZ_IDIOMS || {};
window.QUIZ_IDIOMS.italian = [
  {t:"In bocca al lupo!", e:"good luck!", lit:"into the wolf's mouth", hint:"reply: Crepi (il lupo)!"},
  {t:"Avere le mani bucate", e:"to spend money like water", lit:"to have holes in one's hands", hint:"money slips through the holes — a spendthrift"},
  {t:"Costare un occhio della testa", e:"to cost an arm and a leg", lit:"to cost an eye of the head", hint:"about outrageously expensive things"},
  {t:"Essere al verde", e:"to be broke", lit:"to be at the green", hint:"from candles burned down to the green base — no money left"},
  {t:"Non vedere l'ora", e:"to be unable to wait / to look forward to", lit:"to not see the hour", hint:"followed by di + infinitive: non vedo l'ora di partire"},
  {t:"Prendere due piccioni con una fava", e:"to kill two birds with one stone", lit:"to catch two pigeons with one fava bean", hint:"solve two problems with a single action"},
  {t:"Acqua in bocca!", e:"mum's the word! keep it secret!", lit:"water in the mouth", hint:"you can't talk with a mouth full of water"},
  {t:"Avere la botte piena e la moglie ubriaca", e:"to have your cake and eat it too", lit:"to have the barrel full and the wife drunk", hint:"wanting two incompatible things at once"},
  {t:"Essere in gamba", e:"to be smart / capable", lit:"to be on one's leg", hint:"a compliment: è una ragazza in gamba"},
  {t:"Avere un chiodo fisso", e:"to have an obsession", lit:"to have a fixed nail", hint:"an idea stuck in the head like a nail"},
  {t:"Toccare ferro", e:"to knock on wood", lit:"to touch iron", hint:"Italians touch iron, not wood, for luck"},
  {t:"Essere una mosca bianca", e:"to be a rare bird / very rare", lit:"to be a white fly", hint:"something almost impossible to find"},
  {t:"Avere la testa fra le nuvole", e:"to have one's head in the clouds", lit:"to have the head among the clouds", hint:"a daydreamer, distracted person"},
  {t:"Piove sul bagnato", e:"when it rains, it pours", lit:"it rains on what is already wet", hint:"good or bad luck keeps piling on the same person"},
  {t:"Chi dorme non piglia pesci", e:"the early bird catches the worm", lit:"who sleeps doesn't catch fish", hint:"proverb: laziness gets you nothing"},
  {t:"Fare le ore piccole", e:"to stay up very late", lit:"to make the small hours", hint:"the small hours = 1, 2, 3 a.m."},
  {t:"Avere l'acqua alla gola", e:"to be up against it / under extreme pressure", lit:"to have water at the throat", hint:"deadline panic — about to drown"},
  {t:"Rompere il ghiaccio", e:"to break the ice", lit:"to break the ice", hint:"same as English — starting a conversation"},
  {t:"Costare uno sproposito", e:"to cost a fortune", lit:"to cost an enormity", hint:"colloquial alternative to un occhio della testa"},
  {t:"Essere pane e cacio", e:"to be thick as thieves / a perfect match", lit:"to be bread and cheese", hint:"two people who go perfectly together"},
  {t:"Buono come il pane", e:"good as gold (of a person)", lit:"good as bread", hint:"bread = the ultimate wholesome thing in Italy"},
  {t:"Rendere pan per focaccia", e:"to give tit for tat / pay back in kind", lit:"to give back bread for focaccia", hint:"revenge of equal measure"},
  {t:"Non tutte le ciambelle escono col buco", e:"things don't always turn out as planned", lit:"not all doughnuts come out with a hole", hint:"consolation after a flop"},
  {t:"Avere sale in zucca", e:"to have common sense / brains", lit:"to have salt in the pumpkin", hint:"zucca = head; salt = wit"},
  {t:"Essere come il prezzemolo", e:"to turn up everywhere", lit:"to be like parsley", hint:"parsley goes in every Italian dish"},
  {t:"Andare liscio come l'olio", e:"to go off without a hitch", lit:"to go smooth as oil", hint:"è andato tutto liscio — it all went smoothly"},
  {t:"Cadere a fagiolo", e:"to come at just the right moment", lit:"to fall like a bean", hint:"perfect timing: capiti a fagiolo!"},
  {t:"Essere alla frutta", e:"to be at the end of one's rope / washed up", lit:"to be at the fruit (course)", hint:"fruit is the last course — nothing left"},
  {t:"Tutto fa brodo", e:"every little bit helps", lit:"everything makes broth", hint:"any scrap can go into the soup"},
  {t:"Avere le fette di salame sugli occhi", e:"to be blind to the obvious", lit:"to have slices of salami on one's eyes", hint:"often about someone ignoring a partner's flaws"},
  {t:"In quattro e quattr'otto", e:"in no time at all", lit:"in four and four (makes) eight", hint:"as fast as saying 4+4=8"},
  {t:"Da che pulpito viene la predica!", e:"look who's talking!", lit:"from what pulpit the sermon comes!", hint:"sarcastic — the accuser is guilty of the same thing"},
  {t:"Il gioco non vale la candela", e:"the game isn't worth the candle", lit:"the game isn't worth the candle", hint:"the effort outweighs the reward"},
  {t:"Chi va piano va sano e va lontano", e:"slow and steady wins the race", lit:"who goes slowly goes healthily and goes far", hint:"classic proverb; often shortened to chi va piano..."},
  {t:"Mettere la pulce nell'orecchio", e:"to plant a seed of doubt", lit:"to put a flea in the ear", hint:"a hint that makes someone suspicious"},
  {t:"Avere uno scheletro nell'armadio", e:"to have a skeleton in the closet", lit:"to have a skeleton in the wardrobe", hint:"same as English — a hidden secret"},
  {t:"Prendere lucciole per lanterne", e:"to get the wrong end of the stick", lit:"to mistake fireflies for lanterns", hint:"a complete misunderstanding"},
  {t:"Vuotare il sacco", e:"to spill the beans", lit:"to empty the sack", hint:"confess everything: dai, vuota il sacco!"},
  {t:"Tirare il pacco", e:"to stand someone up", lit:"to throw the package", hint:"colloquial/youth slang; also dare buca"},
  {t:"Prendere in giro", e:"to tease / pull someone's leg", lit:"to take (someone) around", hint:"mi stai prendendo in giro? — are you kidding me?"},
  {t:"Farsene una ragione", e:"to come to terms with it", lit:"to make oneself a reason of it", hint:"fattene una ragione — deal with it"},
  {t:"Non avere peli sulla lingua", e:"to not mince words", lit:"to have no hairs on the tongue", hint:"someone brutally frank"},
  {t:"Avere la coda di paglia", e:"to have a guilty conscience", lit:"to have a tail of straw", hint:"straw tails catch fire easily — touchy because guilty"},
  {t:"Fare orecchie da mercante", e:"to turn a deaf ear", lit:"to make merchant's ears", hint:"merchants hear only what suits them"},
  {t:"Attaccare bottone", e:"to strike up a (long) conversation / chat someone up", lit:"to attach a button", hint:"buttonholing someone who can't escape"},
  {t:"Essere un pezzo grosso", e:"to be a big shot", lit:"to be a big piece", hint:"an important, powerful person"},
  {t:"Fare il passo più lungo della gamba", e:"to bite off more than you can chew", lit:"to take a step longer than the leg", hint:"overreaching, esp. financially"},
  {t:"Chi troppo vuole nulla stringe", e:"grasp all, lose all", lit:"who wants too much grasps nothing", hint:"proverb against greed"},
  {t:"Ogni morte di papa", e:"once in a blue moon", lit:"every death of a pope", hint:"extremely rarely"},
  {t:"Alle calende greche", e:"when pigs fly / never", lit:"at the Greek calends", hint:"the Greek calendar had no calends — i.e. never"},
  {t:"Campa cavallo (che l'erba cresce)", e:"you'll be waiting forever", lit:"live on, horse, for the grass is growing", hint:"sarcastic about promises that never materialize"},
  {t:"Essere il fanalino di coda", e:"to be at the bottom of the league / bring up the rear", lit:"to be the little tail light", hint:"the last in a ranking"},
  {t:"Menare il can per l'aia", e:"to beat around the bush", lit:"to lead the dog around the farmyard", hint:"avoiding the point; non meniamo il can per l'aia"},
  {t:"Tagliare la testa al toro", e:"to settle the matter once and for all", lit:"to cut off the bull's head", hint:"a decisive move that ends all debate"},
  {t:"Essere sulla bocca di tutti", e:"to be the talk of the town", lit:"to be on everyone's mouth", hint:"gossip: everyone is talking about it"},
  {t:"Trovare pane per i propri denti", e:"to meet one's match", lit:"to find bread for one's teeth", hint:"finally facing a worthy opponent or challenge"},
  {t:"Andare a gonfie vele", e:"to be going swimmingly", lit:"to go with swollen sails", hint:"business or life going great: va a gonfie vele"},
  {t:"Essere un libro aperto", e:"to be an open book", lit:"to be an open book", hint:"same as English — easy to read someone"},
  {t:"Avere la luna storta", e:"to be in a bad mood / got up on the wrong side of bed", lit:"to have the crooked moon", hint:"oggi ha la luna storta — steer clear"},
  {t:"Essere di poche parole", e:"to be a person of few words", lit:"to be of few words", hint:"neutral-positive: reserved but reliable"},
  {t:"Fare quattro chiacchiere", e:"to have a little chat", lit:"to make four chats", hint:"quattro = just a few; facciamo due/quattro chiacchiere"},
  {t:"Fare quattro passi", e:"to take a short stroll", lit:"to make four steps", hint:"andiamo a fare quattro passi? — casual invitation"},
  {t:"In alto mare", e:"still far from a solution", lit:"on the high sea", hint:"siamo ancora in alto mare — nowhere near done"},
  {t:"Arrampicarsi sugli specchi", e:"to clutch at straws / make desperate excuses", lit:"to climb up mirrors", hint:"defending an indefensible position"},
  {t:"Cercare il pelo nell'uovo", e:"to nitpick", lit:"to look for the hair in the egg", hint:"hunting for microscopic flaws"},
  {t:"Cercare un ago in un pagliaio", e:"to look for a needle in a haystack", lit:"to look for a needle in a haystack", hint:"same as English"},
  {t:"Avere grilli per la testa", e:"to have strange ideas / big fanciful notions", lit:"to have crickets in the head", hint:"often said of restless young people"},
  {t:"Essere testardo come un mulo", e:"to be stubborn as a mule", lit:"to be stubborn as a mule", hint:"same as English"},
  {t:"Sano come un pesce", e:"fit as a fiddle", lit:"healthy as a fish", hint:"perfectly healthy"},
  {t:"Matto come un cavallo", e:"mad as a hatter", lit:"crazy as a horse", hint:"affectionately crazy"},
  {t:"Mangiare la foglia", e:"to catch on / smell a rat", lit:"to eat the leaf", hint:"realizing a hidden trick: ha mangiato la foglia"},
  {t:"Ingoiare il rospo", e:"to swallow a bitter pill", lit:"to swallow the toad", hint:"accepting something unpleasant without protest"},
  {t:"Sputare il rospo", e:"to spit it out / come clean", lit:"to spit out the toad", hint:"dai, sputa il rospo! — say what you're hiding"},
  {t:"Avere un diavolo per capello", e:"to be furious", lit:"to have a devil per hair", hint:"one devil on every single hair — steaming mad"},
  {t:"Andare su tutte le furie", e:"to fly into a rage", lit:"to go on all the furies", hint:"è andato su tutte le furie quando l'ha saputo"},
  {t:"Fare buon viso a cattivo gioco", e:"to put on a brave face / make the best of a bad situation", lit:"to make a good face to a bad game", hint:"grin and bear it"},
  {t:"Gettare la spugna", e:"to throw in the towel", lit:"to throw the sponge", hint:"from boxing — to give up"},
  {t:"Darci un taglio", e:"to cut it out / stop it", lit:"to give it a cut", hint:"dacci un taglio! — knock it off!"},
  {t:"Farsi in quattro", e:"to bend over backwards", lit:"to split oneself in four", hint:"si fa in quattro per i figli — huge effort for someone"},
  {t:"Togliersi un peso dallo stomaco", e:"to get a weight off one's chest", lit:"to remove a weight from the stomach", hint:"relief after confessing something"},
  {t:"Avere il pollice verde", e:"to have a green thumb", lit:"to have the green thumb", hint:"good with plants — same as English"},
  {t:"Essere nato con la camicia", e:"to be born lucky / with a silver spoon", lit:"to be born with the shirt on", hint:"someone to whom everything comes easily"},
  {t:"Avere la pelle d'oca", e:"to have goosebumps", lit:"to have goose skin", hint:"from cold, fear or emotion: mi è venuta la pelle d'oca"},
  {t:"Essere al settimo cielo", e:"to be over the moon", lit:"to be at the seventh heaven", hint:"pure happiness"},
  {t:"Toccare il cielo con un dito", e:"to be on cloud nine", lit:"to touch the sky with a finger", hint:"a moment of supreme joy"},
  {t:"Avere il cuore in gola", e:"to have one's heart in one's throat", lit:"to have the heart in the throat", hint:"from running or from fear/excitement"},
  {t:"Rimanere di stucco", e:"to be flabbergasted", lit:"to remain of stucco", hint:"frozen like a plaster statue from surprise"},
  {t:"Rimanere di sasso", e:"to be stunned / petrified", lit:"to remain of stone", hint:"synonym of rimanere di stucco"},
  {t:"Non stare più nella pelle", e:"to be beside oneself with excitement", lit:"to no longer fit in one's skin", hint:"non sto più nella pelle! — I can't wait!"},
  {t:"Essere giù di corda", e:"to be down in the dumps", lit:"to be down of rope", hint:"mildly depressed, low energy"},
  {t:"Essere a cavallo", e:"to have it made / be home free", lit:"to be on horseback", hint:"the hard part is done: ormai siamo a cavallo!"},
  {t:"Salvarsi in corner", e:"to save oneself at the last second", lit:"to save oneself in a corner (kick)", hint:"from football — a narrow escape"},
  {t:"Prendere la palla al balzo", e:"to seize the opportunity", lit:"to take the ball on the bounce", hint:"jump on a chance the moment it appears"},
  {t:"Chiudere un occhio", e:"to turn a blind eye", lit:"to close one eye", hint:"per questa volta chiudo un occhio — I'll let it slide"},
  {t:"Costare due lire", e:"to cost next to nothing", lit:"to cost two lire", hint:"pre-euro nostalgia; also valere due lire = worthless"},
  {t:"Sputtanare i soldi", e:"to blow money stupidly", lit:"to squander money shamefully", hint:"vulgar/colloquial register — use with friends only"},
  {t:"Fare una figuraccia", e:"to make a terrible impression / embarrass oneself", lit:"to make an ugly figure", hint:"opposite: fare una bella figura — a core Italian concept"},
  {t:"Essere fuori come un balcone", e:"to be out of one's mind", lit:"to be out like a balcony", hint:"youth slang; also fuori di testa"},
  {t:"Non avere voce in capitolo", e:"to have no say in the matter", lit:"to have no voice in the chapter", hint:"from monastery chapter meetings"},
  {t:"Portare acqua al proprio mulino", e:"to look out for one's own interests", lit:"to carry water to one's own mill", hint:"steering things to one's own advantage"},
  {t:"Sputare nel piatto in cui si mangia", e:"to bite the hand that feeds you", lit:"to spit in the plate one eats from", hint:"ingratitude toward one's benefactor"},
  {t:"L'abito non fa il monaco", e:"clothes don't make the man / don't judge a book by its cover", lit:"the habit doesn't make the monk", hint:"proverb about appearances"},
  {t:"Tra il dire e il fare c'è di mezzo il mare", e:"easier said than done", lit:"between saying and doing there is the sea in between", hint:"rhyming proverb: dire/fare/mare"},
  {t:"Il lupo perde il pelo ma non il vizio", e:"a leopard can't change its spots", lit:"the wolf loses its fur but not its vice", hint:"people don't really change"},
  {t:"Can che abbaia non morde", e:"his bark is worse than his bite", lit:"a dog that barks doesn't bite", hint:"loud threats are usually empty"},
  {t:"A caval donato non si guarda in bocca", e:"don't look a gift horse in the mouth", lit:"one doesn't look a gifted horse in the mouth", hint:"same as English — accept gifts graciously"},
  {t:"Meglio un uovo oggi che una gallina domani", e:"a bird in the hand is worth two in the bush", lit:"better an egg today than a hen tomorrow", hint:"certainty beats promises"},
  {t:"Non è tutto oro quello che luccica", e:"all that glitters is not gold", lit:"not everything that glitters is gold", hint:"same as English"},
  {t:"Paese che vai, usanza che trovi", e:"when in Rome, do as the Romans do", lit:"country you go to, custom you find", hint:"adapt to local ways"},
  {t:"Tutte le strade portano a Roma", e:"all roads lead to Rome", lit:"all roads lead to Rome", hint:"many ways reach the same result"},
  {t:"Fatto trenta, facciamo trentuno", e:"we've come this far, let's finish the job", lit:"having done thirty, let's do thirty-one", hint:"attributed to Pope Leo X naming cardinals"},
  {t:"Roma non è stata costruita in un giorno", e:"Rome wasn't built in a day", lit:"Rome was not built in a day", hint:"big things take time"},
  {t:"Detto fatto", e:"no sooner said than done", lit:"said done", hint:"instant execution of a request"},
  {t:"L'erba del vicino è sempre più verde", e:"the grass is always greener on the other side", lit:"the neighbor's grass is always greener", hint:"universal envy, Italian edition"},
  {t:"A mali estremi, estremi rimedi", e:"desperate times call for desperate measures", lit:"for extreme evils, extreme remedies", hint:"drastic problems, drastic fixes"},
  {t:"Affogare in un bicchier d'acqua", e:"to be overwhelmed by small problems", lit:"to drown in a glass of water", hint:"panic over trifles"},
  {t:"I frutti proibiti sono i più dolci", e:"forbidden fruit is sweetest", lit:"forbidden fruits are the sweetest", hint:"wanting what you can't have"},
  {t:"Conosco i miei polli", e:"I know who I'm dealing with", lit:"I know my chickens", hint:"quiet confidence about people's habits"},
  {t:"Minestra riscaldata", e:"a rekindled relationship (never as good)", lit:"reheated soup", hint:"reviving what went cold rarely works"},
  {t:"Trovarsi fra l'incudine e il martello", e:"to be between a rock and a hard place", lit:"to be between the anvil and the hammer", hint:"two bad options, no exit"},
  {t:"Hai voluto la bicicletta? Allora pedala!", e:"you made your bed, now lie in it", lit:"you wanted the bicycle? then pedal", hint:"face the consequences of your choice"},
  {t:"Dire pane al pane e vino al vino", e:"to call a spade a spade", lit:"to call bread bread and wine wine", hint:"plain speaking"},
  {t:"Essere tutto pepe", e:"to be full of life", lit:"to be all pepper", hint:"vibrant, spirited person — a compliment"},
  {t:"Stare a pennello", e:"to fit like a glove", lit:"to fit like a paintbrush", hint:"clothes that fit perfectly: ti sta a pennello"},
  {t:"Essere colto con le mani nel sacco", e:"to be caught red-handed", lit:"caught with one's hands in the sack", hint:"no talking your way out"},
  {t:"Morto un papa, se ne fa un altro", e:"life goes on / no one is irreplaceable", lit:"one pope dies, another is made", hint:"consolation after any loss"},
  {t:"Togliti dai piedi!", e:"get out of my way!", lit:"take yourself off my feet", hint:"brusque; also figurative"},
  {t:"Attaccare il cappello", e:"to hang up one's hat / retire", lit:"to hang the hat", hint:"also: marry into money and stop working"},
  {t:"Cadere dalle nuvole", e:"to be taken completely by surprise", lit:"to fall from the clouds", hint:"feigned or genuine astonishment"},
  {t:"Mal comune, mezzo gaudio", e:"a trouble shared is a trouble halved", lit:"shared misfortune, half a joy", hint:"misery loves company"},
  {t:"Farsene un baffo", e:"to not care in the slightest", lit:"to make a mustache of it", hint:"shrugging something off"},
  {t:"Tale padre, tale figlio", e:"like father, like son", lit:"such father, such son", hint:"also: tale madre, tale figlia"},
  {t:"Calare le brache", e:"to chicken out", lit:"to lower one's trousers", hint:"caving in, surrendering"},
  {t:"Avere un cervello di gallina", e:"to be a birdbrain", lit:"to have a hen's brain", hint:"poor judgment, small brain"},
  {t:"Cane non mangia cane", e:"honor among thieves", lit:"dog does not eat dog", hint:"the opposite of the English dog-eat-dog"},
  {t:"Avere le braccine corte", e:"to be a cheapskate", lit:"to have short little arms", hint:"arms too short to reach the wallet"},
  {t:"Essere un pesce fuor d'acqua", e:"to be a fish out of water", lit:"to be a fish out of water", hint:"out of one's element"},
  {t:"Avere le mani in pasta", e:"to have a finger in every pie", lit:"to have one's hands in the dough", hint:"connections everywhere"},
  {t:"Fare il finto tonto", e:"to play dumb", lit:"to play the fake fool", hint:"pretending not to know; informal"},
  {t:"Avere una fame da lupi", e:"to be ravenous", lit:"to have a wolves' hunger", hint:"starving after exertion"},
  {t:"Quando il gatto non c'è, i topi ballano", e:"when the cat's away, the mice will play", lit:"when the cat isn't there, the mice dance", hint:"supervision gone, rules gone"},
  {t:"Avere fegato", e:"to have guts", lit:"to have liver", hint:"courage lives in the liver, not the stomach"},
  {t:"Parlare a quattr'occhi", e:"to talk in private", lit:"to speak at four eyes", hint:"one-on-one, confidential"},
  {t:"Togliersi un sassolino dalla scarpa", e:"to get something off one's chest", lit:"to take a little stone out of one's shoe", hint:"finally saying what's bothered you"},
  {t:"Passare una notte in bianco", e:"to have a sleepless night", lit:"to spend a night in white", hint:"in bianco, not in nero"},
  {t:"Di punto in bianco", e:"out of the blue", lit:"from a point in white", hint:"suddenly, without warning"},
  {t:"Vedere tutto nero", e:"to be pessimistic about everything", lit:"to see everything black", hint:"gloom as a worldview"},
  {t:"Il principe azzurro", e:"Prince Charming", lit:"the blue prince", hint:"the fairy-tale ideal man"},
  {t:"Alzare il gomito", e:"to drink too much", lit:"to raise the elbow", hint:"one glass too many; informal"},
];
window.QUIZ_PHRASES = window.QUIZ_PHRASES || {};
window.QUIZ_PHRASES.italian = [
  {id:"restaurant", title:"Ordering at a restaurant", items:[
    {t:"Vorrei vedere il menù, per favore.", e:"I would like to see the menu, please."},
    {t:"Avete un tavolo per due?", e:"Do you have a table for two?"},
    {t:"Ho prenotato a nome Rossi.", e:"I have a reservation under the name Rossi."},
    {t:"Che cosa mi consiglia?", e:"What do you recommend?"},
    {t:"Qual è il piatto del giorno?", e:"What is the dish of the day?"},
    {t:"Per me una pasta alla carbonara, grazie.", e:"I'll have a pasta carbonara, thanks."},
    {t:"Sono allergico alle noci.", e:"I am allergic to nuts."},
    {t:"Avete piatti vegetariani?", e:"Do you have vegetarian dishes?"},
    {t:"Un litro di acqua naturale, per favore.", e:"A liter of still water, please."},
    {t:"Potrei avere ancora un po' di pane?", e:"Could I have some more bread?"},
    {t:"Era tutto buonissimo, complimenti al cuoco!", e:"Everything was delicious, compliments to the chef!"},
    {t:"Il conto, per favore.", e:"The check, please."},
    {t:"Possiamo pagare separatamente?", e:"Can we pay separately?"},
    {t:"È incluso il coperto?", e:"Is the cover charge included?"}
  ]},
  {id:"directions", title:"Directions & transport", items:[
    {t:"Scusi, dov'è la stazione?", e:"Excuse me, where is the station?"},
    {t:"Come arrivo al centro storico?", e:"How do I get to the old town?"},
    {t:"È lontano da qui?", e:"Is it far from here?"},
    {t:"Si può andare a piedi?", e:"Can you walk there?"},
    {t:"Vada sempre dritto.", e:"Go straight ahead."},
    {t:"Giri a destra al semaforo.", e:"Turn right at the traffic light."},
    {t:"Giri a sinistra dopo la piazza.", e:"Turn left after the square."},
    {t:"Quale autobus va all'aeroporto?", e:"Which bus goes to the airport?"},
    {t:"Dove posso comprare i biglietti dell'autobus?", e:"Where can I buy bus tickets?"},
    {t:"A che ora passa il prossimo treno?", e:"What time does the next train come?"},
    {t:"Deve scendere alla prossima fermata.", e:"You have to get off at the next stop."},
    {t:"Mi può chiamare un taxi, per favore?", e:"Can you call me a taxi, please?"},
    {t:"Quanto costa la corsa fino al centro?", e:"How much is the ride to the center?"},
    {t:"Mi sono perso. Può aiutarmi?", e:"I am lost. Can you help me?"}
  ]},
  {id:"shopping", title:"Shopping", items:[
    {t:"Quanto costa questo?", e:"How much does this cost?"},
    {t:"Sto solo dando un'occhiata, grazie.", e:"I'm just looking, thanks."},
    {t:"Posso provarlo?", e:"Can I try it on?"},
    {t:"Dove sono i camerini?", e:"Where are the fitting rooms?"},
    {t:"Avete una taglia più grande?", e:"Do you have a bigger size?"},
    {t:"Ce l'avete in un altro colore?", e:"Do you have it in another color?"},
    {t:"È troppo caro per me.", e:"It's too expensive for me."},
    {t:"C'è uno sconto?", e:"Is there a discount?"},
    {t:"Lo prendo.", e:"I'll take it."},
    {t:"Posso pagare con la carta?", e:"Can I pay by card?"},
    {t:"Mi può fare lo scontrino, per favore?", e:"Can you give me the receipt, please?"},
    {t:"Vorrei fare un cambio: non è la taglia giusta.", e:"I would like to exchange this: it's not the right size."},
    {t:"A che ora chiudete?", e:"What time do you close?"},
    {t:"Mi può fare un pacchetto regalo?", e:"Can you gift-wrap it for me?"}
  ]},
  {id:"hotel", title:"Hotel & accommodation", items:[
    {t:"Ho una prenotazione a nome Riordan.", e:"I have a reservation under the name Riordan."},
    {t:"Avete una camera libera per stanotte?", e:"Do you have a room available for tonight?"},
    {t:"Quanto costa una camera doppia a notte?", e:"How much is a double room per night?"},
    {t:"La colazione è inclusa?", e:"Is breakfast included?"},
    {t:"A che ora è il check-out?", e:"What time is check-out?"},
    {t:"C'è il Wi-Fi in camera?", e:"Is there Wi-Fi in the room?"},
    {t:"Qual è la password del Wi-Fi?", e:"What is the Wi-Fi password?"},
    {t:"L'aria condizionata non funziona.", e:"The air conditioning doesn't work."},
    {t:"Potrei avere un altro asciugamano?", e:"Could I have another towel?"},
    {t:"Può svegliarmi alle sette, per favore?", e:"Can you wake me at seven, please?"},
    {t:"Posso lasciare i bagagli qui fino a mezzogiorno?", e:"Can I leave my luggage here until noon?"},
    {t:"Vorrei prolungare il soggiorno di una notte.", e:"I would like to extend my stay by one night."},
    {t:"C'è un parcheggio per gli ospiti?", e:"Is there parking for guests?"},
    {t:"Vorrei fare il check-out, per favore.", e:"I would like to check out, please."}
  ]},
  {id:"smalltalk", title:"Greetings & small talk", items:[
    {t:"Buongiorno! Come sta?", e:"Good morning! How are you? (formal)"},
    {t:"Ciao! Come va?", e:"Hi! How's it going? (informal)"},
    {t:"Tutto bene, grazie. E Lei?", e:"All good, thanks. And you? (formal)"},
    {t:"Piacere di conoscerLa.", e:"Pleased to meet you. (formal)"},
    {t:"Mi chiamo James. E tu?", e:"My name is James. And you?"},
    {t:"Di dove sei?", e:"Where are you from? (informal)"},
    {t:"Sono americano, vengo dalla California.", e:"I'm American, I come from California."},
    {t:"Che lavoro fa?", e:"What do you do for a living? (formal)"},
    {t:"Sto imparando l'italiano da un anno.", e:"I have been learning Italian for a year."},
    {t:"Può parlare più lentamente, per favore?", e:"Can you speak more slowly, please?"},
    {t:"Che tempo farà domani?", e:"What will the weather be like tomorrow?"},
    {t:"È stata una bella serata, grazie.", e:"It was a lovely evening, thank you."},
    {t:"Ci vediamo presto!", e:"See you soon!"},
    {t:"Buona giornata!", e:"Have a nice day!"},
    {t:"Salutami la tua famiglia.", e:"Say hello to your family for me."}
  ]},
  {id:"emergency", title:"Emergencies & health", items:[
    {t:"Aiuto!", e:"Help!"},
    {t:"Chiamate un'ambulanza, presto!", e:"Call an ambulance, quickly!"},
    {t:"Chiamate la polizia!", e:"Call the police!"},
    {t:"C'è stato un incidente.", e:"There has been an accident."},
    {t:"Non mi sento bene.", e:"I don't feel well."},
    {t:"Mi fa male qui.", e:"It hurts here."},
    {t:"Ho la febbre e mal di gola.", e:"I have a fever and a sore throat."},
    {t:"Dov'è la farmacia più vicina?", e:"Where is the nearest pharmacy?"},
    {t:"Ho bisogno di un medico che parli inglese.", e:"I need a doctor who speaks English."},
    {t:"Sono allergico alla penicillina.", e:"I am allergic to penicillin."},
    {t:"Prendo queste medicine ogni giorno.", e:"I take these medicines every day."},
    {t:"Mi hanno rubato il portafoglio.", e:"My wallet has been stolen."},
    {t:"Ho perso il passaporto.", e:"I have lost my passport."},
    {t:"Dov'è il pronto soccorso?", e:"Where is the emergency room?"}
  ]},
  {id:"phone", title:"Phone & appointments", items:[
    {t:"Pronto, chi parla?", e:"Hello, who is speaking? (on the phone)"},
    {t:"Buongiorno, sono James Riordan.", e:"Good morning, this is James Riordan."},
    {t:"Potrei parlare con il signor Bianchi?", e:"Could I speak with Mr. Bianchi?"},
    {t:"Le passo il mio collega.", e:"I'll put you through to my colleague."},
    {t:"Vorrei prendere un appuntamento.", e:"I would like to make an appointment."},
    {t:"Quando sarebbe possibile?", e:"When would it be possible?"},
    {t:"Le va bene giovedì alle dieci?", e:"Does Thursday at ten work for you?"},
    {t:"Devo spostare l'appuntamento di domani.", e:"I need to move tomorrow's appointment."},
    {t:"Purtroppo devo disdire.", e:"Unfortunately I have to cancel."},
    {t:"Può richiamarmi più tardi?", e:"Can you call me back later?"},
    {t:"La linea è disturbata, non La sento bene.", e:"The line is bad, I can't hear you well."},
    {t:"Le lascio il mio numero di telefono.", e:"I'll leave you my phone number."},
    {t:"Le mando una mail di conferma.", e:"I'll send you a confirmation email."},
    {t:"Grazie della chiamata, arrivederci.", e:"Thank you for the call, goodbye."}
  ]},
  {id:"opinions", title:"Opinions & feelings", items:[
    {t:"Secondo me hai ragione.", e:"In my opinion you are right."},
    {t:"Non sono d'accordo con te.", e:"I don't agree with you."},
    {t:"Penso che sia una buona idea.", e:"I think it's a good idea."},
    {t:"Mi sembra un po' esagerato.", e:"It seems a bit exaggerated to me."},
    {t:"Dipende dal punto di vista.", e:"It depends on the point of view."},
    {t:"Sono sicuro al cento per cento.", e:"I am one hundred percent sure."},
    {t:"Non ne sono convinto.", e:"I'm not convinced of it."},
    {t:"Mi piace moltissimo questa città.", e:"I like this city very much."},
    {t:"Questo film non mi è piaciuto per niente.", e:"I didn't like this movie at all."},
    {t:"Sono molto contento di essere qui.", e:"I am very happy to be here."},
    {t:"Mi sento un po' stanco oggi.", e:"I feel a bit tired today."},
    {t:"Ero preoccupato per te.", e:"I was worried about you."},
    {t:"Che ne pensi?", e:"What do you think about it?"},
    {t:"Hai perfettamente ragione.", e:"You are absolutely right."},
    {t:"Non importa, non è un problema.", e:"It doesn't matter, it's not a problem."}
  ]},
  {id:"travel", title:"Travel & tickets", items:[
    {t:"Vorrei un biglietto per Firenze, per favore.", e:"I would like a ticket to Florence, please."},
    {t:"Solo andata o andata e ritorno?", e:"One way or round trip?"},
    {t:"Quanto costa il biglietto?", e:"How much is the ticket?"},
    {t:"C'è una riduzione per studenti?", e:"Is there a student discount?"},
    {t:"Da quale binario parte il treno per Roma?", e:"Which platform does the train to Rome leave from?"},
    {t:"Il treno è in ritardo di venti minuti.", e:"The train is twenty minutes late."},
    {t:"Devo cambiare treno a Bologna?", e:"Do I have to change trains in Bologna?"},
    {t:"Questo posto è libero?", e:"Is this seat free?"},
    {t:"Ricordati di convalidare il biglietto.", e:"Remember to validate the ticket."},
    {t:"A che ora è l'imbarco?", e:"What time is boarding?"},
    {t:"Il mio volo è stato cancellato.", e:"My flight has been cancelled."},
    {t:"Dove si ritirano i bagagli?", e:"Where do you pick up the luggage?"},
    {t:"Ho solo un bagaglio a mano.", e:"I only have a carry-on bag."},
    {t:"Vorrei noleggiare una macchina per tre giorni.", e:"I would like to rent a car for three days."}
  ]}
];
