// Japanese idioms for the Idioms Test. Sources: Rosetta Stone blog (33 idioms),
// Japonin/JOI 30-idiom list, Tofugu yojijukugo guide — curated, readings added.
// k = kana reading (the typed answer; romaji converts via WanaKana).
window.QUIZ_IDIOMS = window.QUIZ_IDIOMS || {};
window.QUIZ_IDIOMS.japanese = [
  {t:"空気を読む", k:"くうきをよむ", e:"to read the room", lit:"to read the air", hint:"so core it's abbreviated KY (kūki o yomenai) for people who can't"},
  {t:"調子に乗る", k:"ちょうしにのる", e:"to get carried away", lit:"to ride the mood", hint:"often a warning: 調子に乗るな — don't push it"},
  {t:"暇潰し", k:"ひまつぶし", e:"killing time", lit:"smashing free time", hint:"noun; 暇潰しをする = to kill time"},
  {t:"バラ色", k:"ばらいろ", e:"rosy / wonderful", lit:"rose-colored", hint:"バラ色の未来 = a bright future — no irony, genuinely good"},
  {t:"赤い糸で結ばれる", k:"あかいいとでむすばれる", e:"to be destined for each other", lit:"to be tied by a red string", hint:"soulmates joined at the pinky by the red string of fate"},
  {t:"花より団子", k:"はなよりだんご", e:"substance over style", lit:"dango (dumplings) over flowers", hint:"choose the useful over the pretty; famous as a manga title pun"},
  {t:"一石二鳥", k:"いっせきにちょう", e:"to kill two birds with one stone", lit:"one stone, two birds", hint:"yojijukugo (four-character idiom), borrowed from English"},
  {t:"一か八か", k:"いちかばちか", e:"all or nothing / take a gamble", lit:"one or eight", hint:"from Edo-period dice gambling"},
  {t:"後塵を拝する", k:"こうじんをはいする", e:"to be left in someone's dust", lit:"to worship the dust behind someone", hint:"formal; respect (or envy) toward someone far ahead"},
  {t:"腹が立つ", k:"はらがたつ", e:"to get angry", lit:"one's belly stands up", hint:"everyday anger; 腹立つ！ = that makes me mad!"},
  {t:"腕を磨く", k:"うでをみがく", e:"to polish one's skills", lit:"to polish one's arms", hint:"腕 (arm) stands for skill: 腕がいい = skilled"},
  {t:"首を切る", k:"くびをきる", e:"to fire someone", lit:"to cut the neck", hint:"首になる = to get fired"},
  {t:"間一髪", k:"かんいっぱつ", e:"a close call", lit:"the width of a single hair", hint:"間一髪で助かった = saved by a hair"},
  {t:"口が悪い", k:"くちがわるい", e:"sharp-tongued", lit:"one's mouth is bad", hint:"blunt or rude way of speaking"},
  {t:"口に合う", k:"くちにあう", e:"to suit one's taste (food)", lit:"to match one's mouth", hint:"polite host phrase: お口に合いましたか？"},
  {t:"足を引っ張る", k:"あしをひっぱる", e:"to hold someone back", lit:"to pull someone's leg", hint:"NOT joking like English — it means dragging the team down"},
  {t:"胸に落ちる", k:"むねにおちる", e:"to sink in / be convinced", lit:"to fall into one's chest", hint:"also 腑に落ちる; 腑に落ちない = it doesn't add up"},
  {t:"寝耳に水", k:"ねみみにみず", e:"a bolt from the blue", lit:"water in a sleeping ear", hint:"shocking news out of nowhere"},
  {t:"耳にたこができる", k:"みみにたこができる", e:"sick of hearing it", lit:"calluses grow on one's ears", hint:"after the hundredth repetition of the same story"},
  {t:"喉から手が出る", k:"のどからてがでる", e:"to want something desperately", lit:"a hand comes out of one's throat", hint:"usually 喉から手が出るほど欲しい"},
  {t:"肩で風を切る", k:"かたでかぜをきる", e:"to swagger", lit:"to cut the wind with one's shoulders", hint:"strutting with confidence"},
  {t:"猫舌", k:"ねこじた", e:"sensitive to hot food", lit:"cat tongue", hint:"can't drink hot tea; cats won't touch hot food either"},
  {t:"猫の手も借りたい", k:"ねこのてもかりたい", e:"swamped — need all the help one can get", lit:"would even borrow a cat's paws", hint:"a cat's help is useless, and you'd still take it"},
  {t:"猿も木から落ちる", k:"さるもきからおちる", e:"even experts make mistakes", lit:"even monkeys fall from trees", hint:"proverb (ことわざ)"},
  {t:"泣き面に蜂", k:"なきつらにはち", e:"adding insult to injury", lit:"a bee to a crying face", hint:"when it rains, it pours"},
  {t:"トカゲの尻尾切り", k:"とかげのしっぽきり", e:"making a scapegoat", lit:"cutting off the lizard's tail", hint:"the organization survives; the underling takes the blame"},
  {t:"二兎を追う者は一兎をも得ず", k:"にとをおうものはいっとをもえず", e:"chase two rabbits, catch neither", lit:"one who chases two rabbits gains not even one", hint:"proverb — divide your effort and lose everything"},
  {t:"前門の虎、後門の狼", k:"ぜんもんのとら、こうもんのおおかみ", e:"between a rock and a hard place", lit:"a tiger at the front gate, a wolf at the back", hint:"two dangers, no way out"},
  {t:"大きなお世話", k:"おおきなおせわ", e:"none of your business", lit:"a great big favor", hint:"sarcastic rejection of unwanted help"},
  {t:"へそくり", k:"へそくり", e:"secret savings", lit:"navel savings", hint:"the stash your spouse doesn't know about"},
  {t:"大目に見る", k:"おおめにみる", e:"to let it slide", lit:"to look with big eyes", hint:"to overlook a fault this once"},
  {t:"目が高い", k:"めがたかい", e:"to have a discerning eye", lit:"one's eyes are high", hint:"compliment: お目が高いですね — you have great taste"},
  {t:"ああ言えばこう言う", k:"ああいえばこういう", e:"always talking back", lit:"if I say this, you say that", hint:"a comeback for every remark"},
  {t:"見栄っ張り", k:"みえっぱり", e:"a show-off", lit:"a stretcher of appearances", hint:"spending to keep up appearances"},
  {t:"枕を高くする", k:"まくらをたかくする", e:"to sleep easy", lit:"to raise one's pillow high", hint:"枕を高くして眠る — with worries gone"},
  {t:"赤の他人", k:"あかのたにん", e:"a complete stranger", lit:"a red stranger", hint:"赤 intensifies: utterly unrelated person"},
  {t:"持ちつ持たれつ", k:"もちつもたれつ", e:"give and take", lit:"holding and being held", hint:"mutual support — we all lean on each other"},
  {t:"言うことなし", k:"いうことなし", e:"nothing to complain about", lit:"nothing to say", hint:"perfect — no notes"},
  {t:"ずば抜ける", k:"ずばぬける", e:"to stand head and shoulders above", lit:"to shoot way past", hint:"ずば抜けて上手い = exceptionally good"},
  {t:"気が散る", k:"きがちる", e:"to be distracted", lit:"one's spirit scatters", hint:"うるさくて気が散る — the noise breaks my focus"},
  {t:"すっぽかす", k:"すっぽかす", e:"to stand someone up", lit:"(to leave something undone)", hint:"casual: blowing off an appointment entirely"},
  {t:"高嶺の花", k:"たかねのはな", e:"out of one's league", lit:"a flower on a high peak", hint:"beautiful, visible, unreachable"},
  {t:"お裾分け", k:"おすそわけ", e:"sharing a portion (of a gift or windfall)", lit:"sharing the hem", hint:"neighborly: here, we got too many apples"},
  {t:"出不精", k:"でぶしょう", e:"a homebody", lit:"lazy about going out", hint:"休日は出不精 — won't leave the house on weekends"},
  {t:"サバを読む", k:"さばをよむ", e:"to fudge the numbers", lit:"to count the mackerel", hint:"especially lying about one's age; from fishmongers' fast counting"},
  {t:"元も子もない", k:"もともこもない", e:"to lose everything / defeat the purpose", lit:"neither principal nor interest", hint:"無理して倒れたら元も子もない — ruin your health and all is lost"},
  {t:"虫が好かない", k:"むしがすかない", e:"can't stand someone", lit:"one's bugs don't like them", hint:"instinctive dislike you can't explain"},
  {t:"図に乗る", k:"ずにのる", e:"to push one's luck", lit:"to ride the plan", hint:"getting cocky after success — close kin of 調子に乗る"},
  {t:"鼻が曲がる", k:"はながまがる", e:"an unbearable stench", lit:"one's nose bends", hint:"鼻が曲がるような臭い — a smell that bends your nose"},
  {t:"道草を食う", k:"みちくさをくう", e:"to dawdle on the way", lit:"to eat roadside grass", hint:"like a horse grazing instead of walking — dawdling en route"},
  {t:"負けず嫌い", k:"まけずぎらい", e:"hates to lose", lit:"a hater of losing", hint:"fiercely competitive by nature"},
  {t:"慣れっこ", k:"なれっこ", e:"used to it by now", lit:"a creature of habit (to it)", hint:"騒音には慣れっこ — the noise doesn't register anymore"},
  {t:"すっからかん", k:"すっからかん", e:"flat broke / completely empty", lit:"(empty rattling sound)", hint:"wallet, tank, or head — nothing left at all"},
  {t:"出るところに出る", k:"でるところにでる", e:"to take it to court", lit:"to go where one must go", hint:"a threat to settle it officially"},
  {t:"ちやほやする", k:"ちやほやする", e:"to fawn over someone", lit:"(flattering sounds)", hint:"spoiling with attention and praise"},
  {t:"一期一会", k:"いちごいちえ", e:"a once-in-a-lifetime encounter", lit:"one time, one meeting", hint:"tea-ceremony spirit: treasure this meeting, it won't recur"},
  {t:"以心伝心", k:"いしんでんしん", e:"understanding without words", lit:"heart-to-heart transmission", hint:"you knew what I meant before I said it"},
  {t:"一生懸命", k:"いっしょうけんめい", e:"with all one's might", lit:"risking one's life on it", hint:"originally 一所懸命 — defending one's single fief to the death"},
  {t:"温故知新", k:"おんこちしん", e:"learning from the past", lit:"warm the old, know the new", hint:"study the old to understand the new — from Confucius"},
  {t:"十人十色", k:"じゅうにんといろ", e:"to each their own", lit:"ten people, ten colors", hint:"everyone's different — tastes can't be argued"},
  {t:"日進月歩", k:"にっしんげっぽ", e:"rapid, constant progress", lit:"daily advance, monthly progress", hint:"technology marches on: 技術は日進月歩"},
  {t:"不言実行", k:"ふげんじっこう", e:"actions, not words", lit:"no words, real action", hint:"doing without announcing"},
  {t:"臨機応変", k:"りんきおうへん", e:"adapting on the fly", lit:"meet the moment, respond to change", hint:"playing it by ear — prized in job interviews"},
  {t:"切磋琢磨", k:"せっさたくま", e:"honing each other through friendly rivalry", lit:"cut, grind, polish, hone", hint:"rivals who sharpen each other"},
  {t:"花鳥風月", k:"かちょうふうげつ", e:"the beauties of nature", lit:"flower, bird, wind, moon", hint:"the classical set of elegant subjects"},
  {t:"四面楚歌", k:"しめんそか", e:"surrounded by enemies", lit:"Chu songs on all four sides", hint:"from a Chinese siege — hearing your homeland's songs from the enemy camp"},
  {t:"天真爛漫", k:"てんしんらんまん", e:"innocent and carefree", lit:"natural brilliance overflowing", hint:"childlike openness, no pretense"},
  {t:"粉骨砕身", k:"ふんこつさいしん", e:"working oneself to the bone", lit:"pulverize bones, shatter body", hint:"total devotion to the task"},
  {t:"悠々自適", k:"ゆうゆうじてき", e:"a life of comfortable leisure", lit:"calm and self-content", hint:"the retirement dream: 悠々自適の生活"}
];
