// Spanish (Latin American) quiz data — authored from the standard A1–B1
// curriculum, Latin American conventions throughout: ustedes (never vosotros),
// LatAm vocabulary (computadora, carro, jugo, celular, papa), tú (no vos forms).
window.QUIZ_DATA = window.QUIZ_DATA || {};
window.QUIZ_DATA.spanish = {
  name: "Spanish",
  flag: "🇲🇽",
  ttsLang: "es-US",
  courses: [
    {
      id: "es_core",
      title: "Spanish Essentials (A1–A2)",
      units: [
        { id: "es_v1", type: "vocab", title: "Vocab: Greetings & essentials", items: [
          {t:"hola", e:"hello"}, {t:"buenos días", e:"good morning"},
          {t:"buenas tardes", e:"good afternoon"}, {t:"buenas noches", e:"good evening / night"},
          {t:"adiós", e:"goodbye"}, {t:"hasta luego", e:"see you later"},
          {t:"hasta mañana", e:"see you tomorrow"}, {t:"nos vemos", e:"see you"},
          {t:"por favor", e:"please"}, {t:"gracias", e:"thank you"},
          {t:"muchas gracias", e:"thank you very much"}, {t:"de nada", e:"you're welcome"},
          {t:"con permiso", e:"excuse me (passing by)"}, {t:"perdón", e:"pardon / sorry"},
          {t:"lo siento", e:"I'm sorry"}, {t:"¿cómo estás?", e:"how are you?"},
          {t:"estoy bien", e:"I'm fine"}, {t:"¿y tú?", e:"and you?"},
          {t:"¿cómo te llamas?", e:"what's your name?"}, {t:"me llamo…", e:"my name is…"},
          {t:"mucho gusto", e:"nice to meet you"}, {t:"¿de dónde eres?", e:"where are you from?"},
          {t:"soy de Estados Unidos", e:"I'm from the United States"},
          {t:"no entiendo", e:"I don't understand"},
          {t:"más despacio, por favor", e:"slower, please"}, {t:"¡bienvenido!", e:"welcome!"}
        ]},
        { id: "es_v2", type: "vocab", title: "Vocab: Numbers, days & time", items: [
          {t:"uno", e:"one"}, {t:"dos", e:"two"}, {t:"tres", e:"three"},
          {t:"cuatro", e:"four"}, {t:"cinco", e:"five"}, {t:"seis", e:"six"},
          {t:"siete", e:"seven"}, {t:"ocho", e:"eight"}, {t:"nueve", e:"nine"},
          {t:"diez", e:"ten"}, {t:"veinte", e:"twenty"}, {t:"treinta", e:"thirty"},
          {t:"cincuenta", e:"fifty"}, {t:"cien", e:"one hundred"}, {t:"mil", e:"one thousand"},
          {t:"el lunes", e:"Monday"}, {t:"el martes", e:"Tuesday"}, {t:"el miércoles", e:"Wednesday"},
          {t:"el jueves", e:"Thursday"}, {t:"el viernes", e:"Friday"}, {t:"el sábado", e:"Saturday"},
          {t:"el domingo", e:"Sunday"}, {t:"hoy", e:"today"}, {t:"ayer", e:"yesterday"},
          {t:"mañana", e:"tomorrow"}, {t:"ahora", e:"now"}, {t:"la semana", e:"the week"},
          {t:"el mes", e:"the month"}, {t:"el año", e:"the year"},
          {t:"¿qué hora es?", e:"what time is it?"}
        ]},
        { id: "es_v3", type: "vocab", title: "Vocab: Family & people", items: [
          {t:"la familia", e:"family"}, {t:"la madre", e:"mother"},
          {t:"el padre", e:"father"}, {t:"mamá", e:"mom"}, {t:"papá", e:"dad"},
          {t:"el hermano", e:"brother"}, {t:"la hermana", e:"sister"},
          {t:"el hijo", e:"son"}, {t:"la hija", e:"daughter"},
          {t:"el abuelo", e:"grandfather"}, {t:"la abuela", e:"grandmother"},
          {t:"el tío", e:"uncle"}, {t:"la tía", e:"aunt"},
          {t:"el primo", e:"cousin (male)"}, {t:"el esposo", e:"husband"},
          {t:"la esposa", e:"wife"}, {t:"el hombre", e:"man"}, {t:"la mujer", e:"woman"},
          {t:"el niño", e:"boy / child"}, {t:"la niña", e:"girl"},
          {t:"el bebé", e:"baby"}, {t:"el amigo", e:"friend"},
          {t:"la gente", e:"people"}, {t:"la persona", e:"person"},
          {t:"el nombre", e:"name"}, {t:"casado", e:"married"}, {t:"soltero", e:"single"}
        ]},
        { id: "es_v4", type: "vocab", title: "Vocab: Food & drink", items: [
          {t:"la comida", e:"food / meal"}, {t:"el pan", e:"bread"},
          {t:"la mantequilla", e:"butter"}, {t:"el queso", e:"cheese"},
          {t:"la leche", e:"milk"}, {t:"el agua", e:"water"},
          {t:"el jugo", e:"juice"}, {t:"el café", e:"coffee"}, {t:"el té", e:"tea"},
          {t:"la cerveza", e:"beer"}, {t:"el vino", e:"wine"},
          {t:"el arroz", e:"rice"}, {t:"los frijoles", e:"beans"},
          {t:"la papa", e:"potato"}, {t:"el pollo", e:"chicken"},
          {t:"la carne", e:"meat / beef"}, {t:"el pescado", e:"fish (to eat)"},
          {t:"los camarones", e:"shrimp"}, {t:"el huevo", e:"egg"},
          {t:"la manzana", e:"apple"}, {t:"el durazno", e:"peach"},
          {t:"la naranja", e:"orange"}, {t:"la torta", e:"sandwich (Mexico) / cake"},
          {t:"el pastel", e:"cake"}, {t:"la sopa", e:"soup"},
          {t:"el desayuno", e:"breakfast"}, {t:"el almuerzo", e:"lunch"},
          {t:"la cena", e:"dinner"}, {t:"tengo hambre", e:"I'm hungry"},
          {t:"tengo sed", e:"I'm thirsty"}
        ]},
        { id: "es_v5", type: "vocab", title: "Vocab: Home & everyday objects", items: [
          {t:"la casa", e:"house"}, {t:"el apartamento", e:"apartment"},
          {t:"la sala", e:"living room"}, {t:"la cocina", e:"kitchen"},
          {t:"el baño", e:"bathroom"}, {t:"la recámara", e:"bedroom (Mexico)"},
          {t:"la puerta", e:"door"}, {t:"la ventana", e:"window"},
          {t:"la mesa", e:"table"}, {t:"la silla", e:"chair"},
          {t:"la cama", e:"bed"}, {t:"el sofá", e:"sofa"},
          {t:"la televisión", e:"television"}, {t:"la computadora", e:"computer"},
          {t:"el celular", e:"cell phone"}, {t:"el carro", e:"car"},
          {t:"la licuadora", e:"blender"}, {t:"el refrigerador", e:"refrigerator"},
          {t:"la estufa", e:"stove"}, {t:"la lámpara", e:"lamp"},
          {t:"la llave", e:"key"}, {t:"el espejo", e:"mirror"},
          {t:"los lentes", e:"glasses"}, {t:"la cuchara", e:"spoon"},
          {t:"el cuchillo", e:"knife"}, {t:"el tenedor", e:"fork"},
          {t:"el vaso", e:"glass (drinking)"}, {t:"el plato", e:"plate / dish"}
        ]},
        { id: "es_v6", type: "vocab", title: "Vocab: City, travel & transport", items: [
          {t:"la ciudad", e:"city"}, {t:"el pueblo", e:"town / village"},
          {t:"la calle", e:"street"}, {t:"la plaza", e:"square / plaza"},
          {t:"el centro", e:"downtown"}, {t:"el banco", e:"bank"},
          {t:"la tienda", e:"store"}, {t:"el mercado", e:"market"},
          {t:"el supermercado", e:"supermarket"}, {t:"el restaurante", e:"restaurant"},
          {t:"la iglesia", e:"church"}, {t:"el hospital", e:"hospital"},
          {t:"el aeropuerto", e:"airport"}, {t:"el avión", e:"airplane"},
          {t:"el autobús", e:"bus"}, {t:"el tren", e:"train"},
          {t:"el taxi", e:"taxi"}, {t:"el metro", e:"subway"},
          {t:"el boleto", e:"ticket"}, {t:"el viaje", e:"trip"},
          {t:"viajar", e:"to travel"}, {t:"manejar", e:"to drive"},
          {t:"caminar", e:"to walk"}, {t:"la esquina", e:"corner"},
          {t:"a la derecha", e:"to the right"}, {t:"a la izquierda", e:"to the left"},
          {t:"derecho", e:"straight ahead"}, {t:"¿dónde está…?", e:"where is…?"},
          {t:"cerca", e:"near"}, {t:"lejos", e:"far"}
        ]},
        { id: "es_v7", type: "vocab", title: "Vocab: Work & school", items: [
          {t:"el trabajo", e:"work / job"}, {t:"trabajar", e:"to work"},
          {t:"la oficina", e:"office"}, {t:"el jefe", e:"boss"},
          {t:"el empleado", e:"employee"}, {t:"la reunión", e:"meeting"},
          {t:"el dinero", e:"money"}, {t:"el sueldo", e:"salary"},
          {t:"la empresa", e:"company"}, {t:"la escuela", e:"school"},
          {t:"la universidad", e:"university"}, {t:"el estudiante", e:"student"},
          {t:"el maestro", e:"teacher"}, {t:"la clase", e:"class"},
          {t:"la tarea", e:"homework"}, {t:"el examen", e:"exam"},
          {t:"el libro", e:"book"}, {t:"el cuaderno", e:"notebook"},
          {t:"la pluma", e:"pen (LatAm)"}, {t:"el lápiz", e:"pencil"},
          {t:"aprender", e:"to learn"}, {t:"estudiar", e:"to study"},
          {t:"enseñar", e:"to teach"}, {t:"leer", e:"to read"},
          {t:"escribir", e:"to write"}, {t:"la palabra", e:"word"},
          {t:"la pregunta", e:"question"}, {t:"la respuesta", e:"answer"}
        ]},
        { id: "es_v8", type: "vocab", title: "Vocab: Clothing & colors", items: [
          {t:"la ropa", e:"clothing"}, {t:"la camisa", e:"shirt"},
          {t:"la playera", e:"t-shirt (Mexico)"}, {t:"el pantalón", e:"pants"},
          {t:"los jeans", e:"jeans"}, {t:"el vestido", e:"dress"},
          {t:"la falda", e:"skirt"}, {t:"el suéter", e:"sweater"},
          {t:"la chamarra", e:"jacket (Mexico)"}, {t:"el abrigo", e:"coat"},
          {t:"los zapatos", e:"shoes"}, {t:"los tenis", e:"sneakers"},
          {t:"los calcetines", e:"socks"}, {t:"el sombrero", e:"hat"},
          {t:"la gorra", e:"cap"}, {t:"la bolsa", e:"bag / purse"},
          {t:"llevar", e:"to wear / carry"}, {t:"ponerse", e:"to put on"},
          {t:"el color", e:"color"}, {t:"rojo", e:"red"},
          {t:"azul", e:"blue"}, {t:"verde", e:"green"},
          {t:"amarillo", e:"yellow"}, {t:"negro", e:"black"},
          {t:"blanco", e:"white"}, {t:"gris", e:"gray"},
          {t:"café", e:"brown (LatAm)"}, {t:"rosado", e:"pink"},
          {t:"morado", e:"purple"}, {t:"anaranjado", e:"orange (color)"}
        ]},
        { id: "es_v9", type: "vocab", title: "Vocab: Body & health", items: [
          {t:"el cuerpo", e:"body"}, {t:"la cabeza", e:"head"},
          {t:"la cara", e:"face"}, {t:"el ojo", e:"eye"},
          {t:"la nariz", e:"nose"}, {t:"la boca", e:"mouth"},
          {t:"el diente", e:"tooth"}, {t:"la oreja", e:"ear"},
          {t:"el pelo", e:"hair"}, {t:"el cuello", e:"neck"},
          {t:"el brazo", e:"arm"}, {t:"la mano", e:"hand"},
          {t:"el dedo", e:"finger"}, {t:"la pierna", e:"leg"},
          {t:"el pie", e:"foot"}, {t:"la espalda", e:"back"},
          {t:"el estómago", e:"stomach"}, {t:"el corazón", e:"heart"},
          {t:"la sangre", e:"blood"}, {t:"enfermo", e:"sick"},
          {t:"sano", e:"healthy"}, {t:"el dolor", e:"pain"},
          {t:"me duele la cabeza", e:"my head hurts"}, {t:"la fiebre", e:"fever"},
          {t:"la gripa", e:"flu (LatAm)"}, {t:"la medicina", e:"medicine"},
          {t:"el médico", e:"doctor"}, {t:"la farmacia", e:"pharmacy"},
          {t:"la cita", e:"appointment"}
        ]},
        { id: "es_v10", type: "vocab", title: "Vocab: Weather, nature & animals", items: [
          {t:"el clima", e:"weather / climate"}, {t:"hace calor", e:"it's hot"},
          {t:"hace frío", e:"it's cold"}, {t:"hace sol", e:"it's sunny"},
          {t:"hace viento", e:"it's windy"}, {t:"está nublado", e:"it's cloudy"},
          {t:"llover", e:"to rain"}, {t:"la lluvia", e:"rain"},
          {t:"nevar", e:"to snow"}, {t:"la nieve", e:"snow"},
          {t:"la tormenta", e:"storm"}, {t:"el cielo", e:"sky"},
          {t:"el sol", e:"sun"}, {t:"la luna", e:"moon"},
          {t:"la estrella", e:"star"}, {t:"el árbol", e:"tree"},
          {t:"la flor", e:"flower"}, {t:"el río", e:"river"},
          {t:"el lago", e:"lake"}, {t:"el mar", e:"sea"},
          {t:"la playa", e:"beach"}, {t:"la montaña", e:"mountain"},
          {t:"el perro", e:"dog"}, {t:"el gato", e:"cat"},
          {t:"el pájaro", e:"bird"}, {t:"el caballo", e:"horse"},
          {t:"la vaca", e:"cow"}, {t:"la primavera", e:"spring"},
          {t:"el verano", e:"summer"}, {t:"el otoño", e:"fall / autumn"},
          {t:"el invierno", e:"winter"}
        ]},
        { id: "es_g1", type: "grammar", title: "Grammar: Gender & articles", lesson: "Every Spanish noun has a gender: masculine nouns take el/los and un/unos, feminine take la/las and una/unas — el carro (the car), Quiero una manzana (I want an apple). Endings usually help (-o masculine, -a feminine), but memorize the traps: Greek-origin words ending in -ma are masculine (el problema, el clima, el mapa), as is el día (Es un día bonito — It's a beautiful day), while la mano, la foto and la moto are feminine despite their endings. Feminine nouns starting with a STRESSED a- sound (agua, águila) take el in the singular purely for pronunciation, yet remain feminine: el agua fría, las aguas. Adjectives always agree with the true gender: El agua está fría (The water is cold).", items: [
          {q:"Which definite article goes with masculine singular nouns?", c:["el","la","los","las"], a:0, x:"Articles agree in gender and number: masculine singular takes el — el carro, el libro. La is feminine singular and los/las are plural, so only el fits a masculine singular noun.", ex:"El carro es nuevo.", tr:"The car is new."},
          {q:"Feminine nouns beginning with a stressed a- (agua, águila) take which singular article?", c:["el (el agua, but adjectives stay feminine)","la","los","un only"], a:0, x:"Feminine nouns beginning with a STRESSED a- sound take el in the singular purely for easier pronunciation: el agua. The noun stays feminine — adjectives and plurals prove it: el agua fría, las aguas.", ex:"El agua está fría.", tr:"The water is cold."},
          {q:"___ problema es difícil.", c:["El","La","Los","Las"], a:0, x:"Greek-origin nouns ending in -ma are masculine despite the -a: el problema, el programa, el clima. The -a ending is the trap — gender follows the word's origin, not its final letter.", tr:"The problem is difficult."},
          {q:"Me lastimé ___ mano.", c:["la","el","los","las"], a:0, x:"Endings usually signal gender, but mano is a memorized exception: it ends in -o yet is feminine — la mano. Choosing el because of the -o is exactly the trap this word sets.", tr:"I hurt my hand."},
          {q:"Es ___ día bonito.", c:["un","una","unos","la"], a:0, x:"Día is masculine despite its -a ending: el día, un día bonito. It is one of the classic exceptions (like the -ma words) where the ending would steer you to the wrong article.", tr:"It is a beautiful day."},
          {q:"___ mapas están en la mesa.", c:["Los","Las","El","La"], a:0, x:"Mapa is masculine (a Greek-origin -ma exception): el mapa → plural los mapas. Las is the trap if you read the final -a as feminine — agreement follows true gender, not spelling.", tr:"The maps are on the table."},
          {q:"Quiero ___ manzana.", c:["una","un","unas","el"], a:0, x:"Indefinite articles agree with the noun: manzana is a regular feminine -a noun, so 'an apple' is una manzana. Un would be masculine, and unas would wrongly make it plural.", tr:"I want an apple."},
          {q:"___ foto es vieja.", c:["La","El","Los","Un"], a:0, x:"Foto is short for fotografía, so it keeps the full word's feminine gender despite ending in -o: la foto. Moto (motocicleta) works the same way — the original word's gender wins.", tr:"The photo is old."},
          {q:"El agua está ___.", c:["fría","frío","frías","fríos"], a:0, x:"Even though agua takes el in the singular, it is truly feminine, so adjectives must agree feminine: el agua está fría. Frío is the trap — the article el does not change the noun's gender.", tr:"The water is cold."}
        ]},
        { id: "es_g2", type: "grammar", title: "Grammar: Present tense — regular verbs", lesson: "Regular present-tense verbs come in three families: -ar, -er, -ir. Drop the ending and add the person endings: hablar → hablo, hablas, habla, hablamos, hablan; comer → como, comes, come, comemos, comen; vivir → vivo, vives, vive, vivimos, viven. The yo form always ends in -o: Yo hablo español (I speak Spanish), Yo escribo un correo (I write an email). In Latin American Spanish there is NO vosotros: the plural of tú is ustedes, and it always takes third-person plural verbs — ¿Ustedes hablan inglés? (Do you all speak English?), never habláis. Él, ella and usted share one form: Ella bebe mucho café (She drinks a lot of coffee); ellos/ellas use the -n form: Mis amigos viven en México (My friends live in Mexico).", items: [
          {q:"Regular verbs with yo end in:", c:["-o (hablo, como, vivo)","-a","-as","-e always"], a:0, x:"Rule: in the present tense every regular verb — -ar, -er and -ir alike — ends in -o with yo: hablo, como, vivo. The family vowels only show up in the other persons, never in yo.", ex:"Yo hablo español.", tr:"I speak Spanish."},
          {q:"In Latin America, the plural of tú is:", c:["ustedes (with third-person plural verbs)","vosotros","vos","tú también"], a:0, x:"In Latin American Spanish the plural of tú is always ustedes, and it takes third-person plural verbs: ustedes hablan. Vosotros (with its -áis/-éis endings) is used only in Spain.", ex:"¿Ustedes hablan inglés?", tr:"Do you all speak English?"},
          {q:"Yo ___ español.", c:["hablo","habla","hablas","hablan"], a:0, x:"Regular -ar verbs drop -ar and add the person ending; yo takes -o: hablar → yo hablo. Habla and hablas belong to él/ella/usted and tú — the ending must match the subject.", tr:"I speak Spanish."},
          {q:"Tú ___ en la ciudad.", c:["vives","vive","vivo","viven"], a:0, x:"Regular -ir verbs take -es with tú: vivir → tú vives. Vive is the él/ella/usted form and vivo is yo — in Spanish the verb ending itself marks who is acting.", tr:"You live in the city."},
          {q:"Ella ___ mucho café.", c:["bebe","bebes","bebo","beben"], a:0, x:"Regular -er verbs take -e in the third-person singular: beber → ella bebe. Bebes would be tú and bebo yo; él, ella and usted always share this single form.", tr:"She drinks a lot of coffee."},
          {q:"Nosotros ___ tacos los martes.", c:["comemos","comen","comimos","come"], a:0, x:"Nosotros keeps the family vowel: -er verbs take -emos — comer → comemos. Watch the trap comimos: that -imos form is the PRETERITE of comer, not the present.", tr:"We eat tacos on Tuesdays."},
          {q:"¿Ustedes ___ inglés?", c:["hablan","habláis","habla","hablamos"], a:0, x:"Ustedes always pairs with third-person plural verbs: ¿Ustedes hablan inglés? Habláis is the vosotros form used in Spain — in Latin American Spanish it never appears.", tr:"Do you all speak English?"},
          {q:"Mis amigos ___ en México.", c:["viven","vive","vivimos","vives"], a:0, x:"A plural subject (mis amigos = ellos) needs the third-person plural ending -en: viven. Vive is singular and vivimos means 'we live' — the verb must agree in person and number.", tr:"My friends live in Mexico."},
          {q:"Yo ___ un correo a mi jefe.", c:["escribo","escribe","escribes","escriben"], a:0, x:"Escribir is a regular -ir verb, so yo takes -o: escribo. Escribe and escribes belong to other persons; whatever the family (-ar/-er/-ir), the yo present always ends in -o.", tr:"I write an email to my boss."}
        ]},
        { id: "es_g3", type: "grammar", title: "Grammar: Ser vs estar", lesson: "Spanish has two verbs 'to be'. Ser (soy, eres, es, somos, son) covers what something IS by nature: origin, profession, and inherent traits — Somos de Colombia (We are from Colombia), Ella es doctora (She is a doctor), Ustedes son muy amables (You all are very kind). Estar (estoy, estás, está, estamos, están) covers temporary states, current conditions and locations: Estoy cansado hoy (I am tired today), El café está caliente (The coffee is hot), ¿Dónde está el baño? (Where is the bathroom?). One famous exception: EVENTS use ser for where they take place — La fiesta es en mi casa (The party is at my house).", items: [
          {q:"Which verb describes temporary states and locations?", c:["estar","ser","tener","haber"], a:0, x:"Rule: estar covers temporary states, current conditions and location — estoy cansado, está en casa. Ser describes what something inherently IS; swapping them changes or breaks the meaning.", ex:"Estoy cansado hoy.", tr:"I am tired today."},
          {q:"Which verb is used for origin, profession, and inherent traits?", c:["ser","estar","hacer","ir"], a:0, x:"Ser covers what someone or something IS by nature: origin (soy de Perú), profession (es doctora) and inherent traits (es alta). Estar would recast these as passing conditions.", ex:"Soy de México.", tr:"I am from Mexico."},
          {q:"Yo ___ cansado hoy.", c:["estoy","soy","está","eres"], a:0, x:"Tiredness is a temporary state, so estar: estoy cansado hoy. Soy cansado is the trap — with ser it would describe a permanent characteristic ('I am a tiresome person'), not how you feel today.", tr:"I am tired today."},
          {q:"Ella ___ doctora.", c:["es","está","estás","son"], a:0, x:"Professions classify what a person IS, so they take ser: ella es doctora. Está is the trap — estar would suggest a temporary condition, and Spanish treats occupation as identity.", tr:"She is a doctor."},
          {q:"Nosotros ___ de Colombia.", c:["somos","estamos","son","sois"], a:0, x:"Origin — where you are from — is permanent identity, so ser: somos de Colombia. Estamos would instead state where you are located right now, not where you come from.", tr:"We are from Colombia."},
          {q:"El café ___ caliente.", c:["está","es","son","eres"], a:0, x:"The coffee's temperature is a current, changeable condition, so estar: el café está caliente. Es caliente would claim heat as its defining nature rather than its state right now.", tr:"The coffee is hot."},
          {q:"¿Dónde ___ el baño?", c:["está","es","son","estás"], a:0, x:"The location of people and things always takes estar: ¿Dónde está el baño? Ser is the trap — es marks identity, and locates only events (la fiesta es en…), never objects or rooms.", tr:"Where is the bathroom?"},
          {q:"La fiesta ___ en mi casa.", c:["es","está","estás","estamos"], a:0, x:"The famous exception: EVENTS use ser for where they take place — la fiesta es en mi casa. Estar locates objects and people; for a party, meeting or concert, 'is held at' = ser.", tr:"The party is at my house."},
          {q:"Ustedes ___ muy amables.", c:["son","están","es","somos"], a:0, x:"Kindness as a personality trait is inherent, so ser: ustedes son muy amables. Están amables would mean they are acting unusually nice right now — estar turns traits into momentary states.", tr:"You all are very kind."}
        ]},
        { id: "es_c1", type: "conj", title: "Conjugate: Present — regular -ar/-er/-ir", tense: "Present (Presente)", items: [
          {inf:"hablar", en:"to speak", forms:["hablo","hablas","habla","hablamos","hablan","hablan"]},
          {inf:"trabajar", en:"to work", forms:["trabajo","trabajas","trabaja","trabajamos","trabajan","trabajan"]},
          {inf:"estudiar", en:"to study", forms:["estudio","estudias","estudia","estudiamos","estudian","estudian"]},
          {inf:"comer", en:"to eat", forms:["como","comes","come","comemos","comen","comen"]},
          {inf:"beber", en:"to drink", forms:["bebo","bebes","bebe","bebemos","beben","beben"]},
          {inf:"vivir", en:"to live", forms:["vivo","vives","vive","vivimos","viven","viven"]},
          {inf:"escribir", en:"to write", forms:["escribo","escribes","escribe","escribimos","escriben","escriben"]}
        ]},
        { id: "es_c2", type: "conj", title: "Conjugate: Present — irregular & stem-changing", tense: "Present (Presente)", items: [
          {inf:"ser", irr:1, en:"to be (permanent)", forms:["soy","eres","es","somos","son","son"]},
          {inf:"estar", irr:1, en:"to be (state/place)", forms:["estoy","estás","está","estamos","están","están"]},
          {inf:"ir", irr:1, en:"to go", forms:["voy","vas","va","vamos","van","van"]},
          {inf:"tener", irr:1, en:"to have", forms:["tengo","tienes","tiene","tenemos","tienen","tienen"]},
          {inf:"hacer", irr:1, en:"to do / make", forms:["hago","haces","hace","hacemos","hacen","hacen"]},
          {inf:"querer", irr:1, en:"to want (e→ie)", forms:["quiero","quieres","quiere","queremos","quieren","quieren"]},
          {inf:"poder", irr:1, en:"to be able (o→ue)", forms:["puedo","puedes","puede","podemos","pueden","pueden"]}
        ]}
      ]
    },
    {
      id: "es_gram",
      title: "Spanish Grammar (A2–B1)",
      units: [
        { id: "es_g4", type: "grammar", title: "Grammar: Stem-changing & reflexive verbs", lesson: "Stem-changing verbs shift their vowel in every present-tense form EXCEPT nosotros — the 'boot' pattern. e→ie: empezar → La clase empieza (The class starts); o→ue: dormir → Ella duerme (She sleeps); e→i: vestirse → El niño se viste (The boy dresses himself). Nosotros keeps the original stem: podemos, nos acostamos — never puedemos or nos acuestamos. Reflexive verbs add a pronoun that matches the subject (me, te, se, nos, se) BEFORE the conjugated verb: Me levanto a las seis (I get up at six), Ella se baña todos los días (She bathes every day). With an infinitive the pronoun may attach to the end instead: voy a levantarme (I'm going to get up).", items: [
          {q:"In stem-changing verbs like querer (e→ie), the stem does NOT change in:", c:["the nosotros form","the yo form","the tú form","the usted form"], a:0, x:"Stem changes follow the 'boot': every present-tense form shifts the vowel EXCEPT nosotros — quiero, quieres, quiere, quieren, but queremos. The unstressed nosotros stem keeps the original vowel.", ex:"Queremos comer tacos hoy.", tr:"We want to eat tacos today."},
          {q:"Reflexive pronouns (me, te, se, nos, se) go:", c:["before a conjugated verb (me levanto)","after every verb","at the end of the sentence","only with tú"], a:0, x:"Rule: reflexive pronouns go immediately BEFORE a conjugated verb — me levanto. With an infinitive they may instead attach to its end: voy a levantarme. They never float to the end of the sentence.", ex:"Me levanto a las seis.", tr:"I get up at six."},
          {q:"Ella ___ hasta tarde los domingos. (dormir)", c:["duerme","dorme","duermes","dormimos"], a:0, x:"Dormir is an o→ue stem-changer, and ella falls inside the boot, so the vowel shifts: duerme. 'Dorme' misses the change; duermes is tú, and dormimos is the unchanged nosotros form.", tr:"She sleeps late on Sundays."},
          {q:"Nosotros ___ ayudar mañana. (poder)", c:["podemos","puedemos","pueden","podamos"], a:0, x:"Nosotros sits outside the boot, so the stem does NOT change: podemos. 'Puedemos' wrongly extends the o→ue shift — the change only happens where the stem vowel is stressed, and nosotros stresses the ending.", tr:"We can help tomorrow."},
          {q:"¿A qué hora ___ la clase? (empezar)", c:["empieza","empeza","empiezan","empezamos"], a:0, x:"Empezar is e→ie: in the third-person singular the stressed stem vowel diphthongizes — la clase empieza. 'Empeza' skips the required change; only nosotros (empezamos) keeps the plain e.", tr:"What time does the class start?"},
          {q:"Yo ___ a las seis de la mañana. (levantarse)", c:["me levanto","levanto","se levanta","me levanta"], a:0, x:"Levantarse is reflexive, so the pronoun must match the subject: yo → me levanto. Bare levanto means lifting something else, and se levanta belongs to él/ella — pronoun and verb must agree together.", tr:"I get up at six in the morning."},
          {q:"Ella ___ todos los días. (bañarse)", c:["se baña","baña","se bañas","me baña"], a:0, x:"The reflexive pronoun for él/ella/usted is se: ella se baña. Without se, baña means she bathes someone else, and me baña would make ME the one bathed — the pronoun mirrors the subject.", tr:"She bathes every day."},
          {q:"Nosotros ___ temprano. (acostarse)", c:["nos acostamos","nos acuestamos","se acostamos","acostamos"], a:0, x:"Two rules meet: nosotros takes the reflexive nos, AND the o→ue change is suspended outside the boot — nos acostamos. 'Nos acuestamos' wrongly keeps the stem change in the nosotros form.", tr:"We go to bed early."},
          {q:"El niño ___ solo. (vestirse)", c:["se viste","se veste","viste","se visten"], a:0, x:"Vestirse is an e→i stem-changer: the stem e narrows to i inside the boot — el niño se viste. 'Se veste' misses the change, and the reflexive se is required because he dresses himself.", tr:"The boy dresses himself."}
        ]},
        { id: "es_g5", type: "grammar", title: "Grammar: Preterite vs imperfect", lesson: "Spanish has two simple past tenses. The preterite reports COMPLETED events, often with a time stamp: Ayer comí tacos (Yesterday I ate tacos), Ellos fueron al cine el sábado (They went to the movies on Saturday) — even a closed period counts: Vivimos en Lima por cinco años (We lived in Lima for five years). The imperfect paints the background: descriptions, actions in progress and habits — Cuando era niño, jugaba fútbol todos los días (As a kid I played soccer every day); Mientras yo leía, sonó el teléfono (While I was reading, the phone rang — the interruption is preterite). Telling time in the past is always imperfect: Eran las diez (It was ten o'clock). Some verbs change meaning in the preterite: conocí = I met, supe = I found out, pude = I managed to.", items: [
          {q:"Which past tense describes background states, descriptions, and habitual actions?", c:["the imperfect","the preterite","the future","the subjunctive"], a:0, x:"The imperfect paints the background: descriptions, states in progress and habitual actions (jugaba todos los días). The preterite instead reports events completed at a definite point (jugué ayer).", ex:"Jugaba fútbol todos los días.", tr:"I used to play soccer every day."},
          {q:"Conocí a María (preterite of conocer) means:", c:["I met María for the first time","I used to know María","I know María","I will meet María"], a:0, x:"A few verbs change meaning in the preterite because it marks a completed onset: conocí = I met (first contact), supe = I found out, pude = I managed to. 'I used to know her' would be the imperfect conocía.", ex:"Conocí a María en junio.", tr:"I met María in June."},
          {q:"Ayer ___ tacos al pastor. (comer, yo)", c:["comí","comía","como","comió"], a:0, x:"Ayer stamps a single completed event, so the preterite: comí. Comía (imperfect) is the trap — it would turn the meal into a habit or background scene rather than what happened yesterday.", tr:"Yesterday I ate tacos al pastor."},
          {q:"Cuando era niño, ___ fútbol todos los días. (jugar, yo)", c:["jugaba","jugué","juego","jugará"], a:0, x:"Cuando era niño plus todos los días signals a repeated, habitual past action, so the imperfect: jugaba. Jugué (preterite) would report one finished occurrence, not what used to happen.", tr:"When I was a kid, I played soccer every day."},
          {q:"Anoche ella ___ tarde a casa. (llegar)", c:["llegó","llegaba","llega","llegaste"], a:0, x:"Anoche marks one completed event at a specific time, so the preterite: llegó. Llegaba would paint an ongoing background action — but arriving home is a one-time, finished act.", tr:"Last night she got home late."},
          {q:"___ las diez cuando llamaste. (ser)", c:["Eran","Fueron","Es","Era yo"], a:0, x:"Time and dates in the past are pure background, so they ALWAYS take the imperfect: eran las diez. Fueron is the trap — the preterite never tells what time it was, only what happened at that time.", tr:"It was ten o'clock when you called."},
          {q:"Nosotros ___ en Lima por cinco años. (vivir)", c:["vivimos","vivíamos","viviremos","viven"], a:0, x:"A period with clear boundaries ('for five years', now finished) counts as one completed whole, so the preterite: vivimos. Vivíamos would leave the stay as open-ended background — the closed span decides it.", tr:"We lived in Lima for five years."},
          {q:"Mientras yo ___, sonó el teléfono. (leer)", c:["leía","leí","leo","leyó"], a:0, x:"Mientras marks an action in progress that gets interrupted: the ongoing one takes the imperfect (leía) and the interrupting event the preterite (sonó). Leí would wrongly present the reading as finished first.", tr:"While I was reading, the phone rang."},
          {q:"Ellos ___ al cine el sábado pasado. (ir)", c:["fueron","iban","van","irán"], a:0, x:"El sábado pasado dates one completed trip, so the preterite of ir: fueron (irregular: fui, fuiste, fue, fuimos, fueron). Iban would describe what they habitually did, not that one Saturday.", tr:"They went to the movies last Saturday."}
        ]},
        { id: "es_g6", type: "grammar", title: "Grammar: Por vs para", lesson: "Para looks FORWARD to a goal: purpose (Estudio para ser doctora — I study in order to be a doctor), recipient (Este regalo es para ti — This gift is for you), destination, deadline (La tarea es para el lunes — The homework is due Monday), and opinion (Para mí, el español es fácil — For me, Spanish is easy). Por looks at the cause or the path: reason (Gracias por tu ayuda — Thanks for your help), exchange or price (Pagué veinte dólares por el libro — I paid twenty dollars for the book), movement through or along a place (Caminamos por el parque — We walked through the park), and duration (Viajamos por dos semanas — We traveled for two weeks). When stuck, ask: goal ahead → para; cause, trade, route or time span → por.", items: [
          {q:"Which preposition expresses purpose, destination, recipient, or deadline?", c:["para","por","de","en"], a:0, x:"Rule of thumb: para points FORWARD to a goal — purpose, destination, recipient, deadline, opinion. Por points at cause, exchange, duration and route. Same English 'for', two Spanish directions.", ex:"Este regalo es para ti.", tr:"This gift is for you."},
          {q:"Este regalo es ___ ti.", c:["para","por","de","a"], a:0, x:"The gift's intended recipient is a goal, so para: este regalo es para ti. Por ti is the trap — it would mean 'because of you / on your behalf', a cause rather than a destination.", tr:"This gift is for you."},
          {q:"Caminamos ___ el parque.", c:["por","para","en","sobre"], a:0, x:"Movement through or along a place takes por: caminamos por el parque. Para el parque would make the park a destination ('headed to the park') instead of the route of the walk.", tr:"We walked through the park."},
          {q:"Gracias ___ tu ayuda.", c:["por","para","de","con"], a:0, x:"Gracias always pairs with por because thanks answer a CAUSE — you thank because of the help: gracias por tu ayuda. Para would point to a future goal, which thanks never express.", tr:"Thanks for your help."},
          {q:"Estudio ___ ser doctora.", c:["para","por","a","que"], a:0, x:"Purpose before an infinitive ('in order to') is para: estudio para ser doctora. Por + infinitive is the trap — it gives a cause/motive reading, not the goal the studying aims at.", tr:"I study in order to be a doctor."},
          {q:"Pagué veinte dólares ___ el libro.", c:["por","para","a","en"], a:0, x:"Price is an exchange — money traded for the thing — and exchanges take por: pagué veinte dólares por el libro. Para would make the money a gift destined for the book, which makes no sense.", tr:"I paid twenty dollars for the book."},
          {q:"La tarea es ___ el lunes.", c:["para","por","hasta","desde"], a:0, x:"A deadline is a target point in the future, so para: la tarea es para el lunes. Por is the trap — por el lunes would suggest an approximate time or duration, not a due date.", tr:"The homework is due Monday."},
          {q:"Viajamos ___ dos semanas.", c:["por","para","en","desde"], a:0, x:"How LONG something lasts (duration) takes por: viajamos por dos semanas. Para dos semanas would set a goal or deadline; the time span a trip covers is por territory.", tr:"We traveled for two weeks."},
          {q:"___ mí, el español es fácil.", c:["Para","Por","De","A"], a:0, x:"Personal opinion — 'in the view of' — uses para: para mí, el español es fácil. Por mí is the trap: it leans toward 'for my sake / fine by me', a concession rather than a stated opinion.", tr:"For me, Spanish is easy."}
        ]},
        { id: "es_g7", type: "grammar", title: "Grammar: Direct & indirect object pronouns", lesson: "Direct object pronouns (lo, la, los, las) replace the thing acted on and match its gender and number: ¿Viste la película? — Sí, la vi (Yes, I saw it). Indirect object pronouns (me, te, le, nos, les) mark TO or FOR whom: Le escribí una carta a mi abuela (I wrote my grandmother a letter); plural → les: Les dije la verdad a mis padres (I told my parents the truth). Pronouns go before the conjugated verb — Te puedo ayudar (I can help you) — or attach to an infinitive: puedo ayudarte. With two pronouns, indirect comes BEFORE direct: te lo doy (I'll give it to you) — and le/les changes to se before lo/la: se lo di (I gave it to him/her). Latin American speech also adds a 'dative of interest': Ya me lo tomé (I already drank it up).", items: [
          {q:"Lo, la, los, las are which kind of object pronoun?", c:["direct","indirect","reflexive","possessive"], a:0, x:"Lo, la, los, las are DIRECT object pronouns: they replace the thing acted on and copy its gender and number — lo veo = I see it/him. 'To/for whom' takes the indirect set: me, te, le, nos, les.", ex:"Compré el libro y lo leí.", tr:"I bought the book and read it."},
          {q:"When le/les comes before lo/la, le becomes:", c:["se (se lo di)","lo","la","te"], a:0, x:"Rule: when le/les would stand before lo/la/los/las, it changes to se — 'le lo' is impossible: se lo di = I gave it to him/her. This se is a sound-driven substitute, not the reflexive pronoun.", ex:"Se lo di a mi hermana.", tr:"I gave it to my sister."},
          {q:"¿Viste la película? — Sí, ___ vi anoche.", c:["la","lo","le","las"], a:0, x:"A direct object pronoun copies its noun's gender and number: la película is feminine singular, so la vi. Lo would be masculine, and le is reserved for indirect objects — agreement picks la.", tr:"Did you see the movie? — Yes, I saw it last night."},
          {q:"___ escribí una carta a mi abuela.", c:["Le","La","Lo","Se"], a:0, x:"The carta is the thing written (direct object); a mi abuela is TO WHOM — the indirect object — so le: Le escribí una carta. La is the trap: it would treat grandma as the thing being written.", tr:"I wrote a letter to my grandmother."},
          {q:"¿Me puedes ayudar? — Sí, ___ puedo ayudar.", c:["te","me","le","lo"], a:0, x:"The person helped is the object, so the pronoun is te (you): te puedo ayudar. Me would answer with the wrong person ('I can help myself'); te may also attach to the infinitive: puedo ayudarte.", tr:"Can you help me? — Yes, I can help you."},
          {q:"Compré los boletos y ___ pagué en línea.", c:["los","les","las","lo"], a:0, x:"Los boletos is a masculine plural direct object, so the pronoun is los: los pagué en línea. Les is the trap — that is the indirect-object plural, and the tickets are what was paid for, not a recipient.", tr:"I bought the tickets and paid for them online."},
          {q:"El libro, ___ doy mañana.", c:["te lo","lo te","te la","se te"], a:0, x:"With two object pronouns the order is fixed: indirect BEFORE direct — te (to you) + lo (el libro): te lo doy. 'Lo te' is impossible, and te la breaks agreement with masculine libro.", tr:"The book — I'll give it to you tomorrow."},
          {q:"___ dije la verdad a mis padres.", c:["Les","Los","Le","Las"], a:0, x:"A mis padres names plural recipients of the telling — an indirect object — so les: Les dije la verdad. Los is the direct-object form (wrong role), and le is singular (wrong number).", tr:"I told my parents the truth."},
          {q:"¿Y el jugo? — Ya me ___ tomé.", c:["lo","la","le","los"], a:0, x:"El jugo is masculine singular, so the direct object pronoun is lo: me LO tomé. The me is a Latin American 'dative of interest' adding 'up/completely' — it doesn't change which pronoun the juice needs.", tr:"And the juice? — I already drank it."}
        ]},
        { id: "es_g8", type: "grammar", title: "Grammar: Gustar & similar verbs", lesson: "Gustar works backwards: the thing liked is the grammatical SUBJECT, so the verb agrees with IT, and the person who likes it is an indirect object (me, te, le, nos, les). Singular thing → gusta: Nos gusta esta ciudad (We like this city); plural thing → gustan: Me gustan los tacos (I like tacos). Name the liker with a + noun or pronoun, keeping the pronoun anyway: A ella le gusta bailar (She likes to dance), A mis padres les gusta viajar (My parents like to travel) — an infinitive keeps the verb singular. Many verbs copy this pattern: doler — Me duele el brazo (My arm hurts) — and encantar — Me encanta el chocolate (I love chocolate), A Juan le encantan los deportes (Juan loves sports).", items: [
          {q:"With gustar, the verb agrees with:", c:["the thing liked","the person who likes","nothing — always singular","the pronoun yo"], a:0, x:"Gustar works backwards: the thing liked is the grammatical subject, so the VERB agrees with IT — me gusta el café, me gustan los tacos. The person liking is only an indirect object (me, te, le…).", ex:"Me gustan los tacos.", tr:"I like tacos."},
          {q:"Me ___ los tacos.", c:["gustan","gusta","gusto","gustas"], a:0, x:"The verb agrees with the thing liked, not with the liker: los tacos is plural, so gustan — me gustan los tacos. Gusta is the trap of making 'I' the subject, as English does.", tr:"I like tacos."},
          {q:"A ella ___ gusta bailar.", c:["le","la","se","me"], a:0, x:"The liker is expressed as an INDIRECT object, so ella needs le: a ella le gusta bailar. La is the direct-object trap; the a ella phrase only clarifies who — the le is still required.", tr:"She likes to dance."},
          {q:"Nos ___ mucho esta ciudad.", c:["gusta","gustan","gustamos","gusto"], a:0, x:"Agreement runs to the subject, esta ciudad — singular — so gusta: nos gusta esta ciudad. Gustamos is the trap: it would make US the subject, meaning 'we are pleasing', not 'we like'.", tr:"We really like this city."},
          {q:"¿Te ___ las películas de terror?", c:["gustan","gusta","gustas","gusten"], a:0, x:"Las películas de terror is plural and is the grammatical subject, so the verb is plural: te gustan. Gusta would need a singular subject or an infinitive (te gusta ver películas).", tr:"Do you like horror movies?"},
          {q:"A mis padres ___ gusta viajar.", c:["les","los","le","se"], a:0, x:"Mis padres are plural likers, so the indirect pronoun is les. The verb stays singular because its subject is the infinitive viajar: a mis padres les gusta viajar. Los would be a direct-object error.", tr:"My parents like to travel."},
          {q:"Me ___ el brazo.", c:["duele","duelen","dolo","dueles"], a:0, x:"Doler follows the gustar pattern: the hurting part is the subject — el brazo, singular, so duele: me duele el brazo. Duelen would need a plural subject, as in me duelen los pies.", tr:"My arm hurts."},
          {q:"___ encanta el chocolate.", c:["Me","Yo","Mi","Se"], a:0, x:"Encantar copies gustar's structure: the lover is an indirect object pronoun — me encanta el chocolate = chocolate delights me. Yo is the trap: the person cannot be the subject here, and mi is possessive.", tr:"I love chocolate."},
          {q:"A Juan le ___ los deportes.", c:["encantan","encanta","encantas","encanto"], a:0, x:"Encantar agrees with what is loved: los deportes is plural, so encantan — a Juan le encantan los deportes. Encanta is the trap of taking Juan (the indirect object) for the subject.", tr:"Juan loves sports."}
        ]},
        { id: "es_g9", type: "grammar", title: "Grammar: Future & conditional", lesson: "The simple future adds -é, -ás, -á, -emos, -án to the FULL infinitive: Mañana hablaré con el jefe (Tomorrow I will speak with the boss). A handful of verbs use irregular stems: tendr- (tener), har- (hacer → ¿Qué harás? — What will you do?), podr-, dir-, sabr-, vendr- (Vendrán a la fiesta — They will come to the party). The conditional adds -ía, -ías, -ía, -íamos, -ían to the SAME stems and means 'would': Yo que tú, estudiaría más (If I were you, I would study more); it also makes polite requests: Me gustaría un café (I would like a coffee). Two extra uses: the future expresses present guesses — Tendrá unos treinta años (She is probably about thirty) — and the conditional is the future-in-the-past after reporting verbs: Dijo que llegaría tarde (He said he would arrive late).", items: [
          {q:"The simple future endings (-é, -ás, -á, -emos, -án) attach to:", c:["the full infinitive","the yo form","the stem minus -ar","the past participle"], a:0, x:"Unlike other tenses, the simple future keeps the WHOLE infinitive and adds the endings to it: hablar + é = hablaré. Only a short list of verbs swaps in an irregular stem: tendr-, har-, podr-, dir-, sabr-, vendr-.", ex:"Mañana hablaré con ella.", tr:"Tomorrow I will speak with her."},
          {q:"Mañana ___ con el jefe. (hablar, yo)", c:["hablaré","hablo","hablaría","hablaba"], a:0, x:"Mañana calls for the simple future: full infinitive + é → hablaré. Hablaría (conditional) means 'would speak', and hablo/hablaba are present and past — the -ré ending is what says 'will'.", tr:"Tomorrow I will speak with the boss."},
          {q:"¿Qué ___ este fin de semana? (hacer, tú)", c:["harás","hacerás","harías","haces"], a:0, x:"Hacer is one of the irregular-stem futures: the infinitive shrinks to har-, then takes the normal endings — harás. 'Hacerás' is the trap of applying the regular rule to an irregular verb.", tr:"What will you do this weekend?"},
          {q:"Ellos ___ a la fiesta. (venir)", c:["vendrán","venirán","vienen","vendrían"], a:0, x:"Venir builds its future on the irregular stem vendr- (a d replaces the i): vendrán a la fiesta. 'Venirán' wrongly keeps the full infinitive, and vendrían is the conditional 'would come'.", tr:"They will come to the party."},
          {q:"Yo que tú, ___ más. (estudiar)", c:["estudiaría","estudiaré","estudio","estudiara"], a:0, x:"Yo que tú ('if I were you') frames a hypothesis, and hypothetical outcomes take the conditional -ía: estudiaría. Estudiaré (future) states what WILL happen — wrong for advice about an unreal situation.", tr:"If I were you, I would study more."},
          {q:"Me ___ un café, por favor. (gustar)", c:["gustaría","gusta","gustará","gustaba"], a:0, x:"The conditional softens statements into polite requests: me gustaría un café = I would like a coffee. Me gusta is the trap — the present just declares that you like coffee instead of asking for one.", tr:"I would like a coffee, please."},
          {q:"Con más dinero, ___ por Sudamérica. (viajar, nosotros)", c:["viajaríamos","viajaremos","viajamos","viajábamos"], a:0, x:"Con más dinero sets up an unreal condition, and its imagined result takes the conditional: viajaríamos. Viajaremos (future) would promise a real upcoming trip instead of a daydream.", tr:"With more money, we would travel around South America."},
          {q:"___ unos treinta años. (tener, ella)", c:["Tendrá","Tiene que","Tenía siempre","Tuvo"], a:0, x:"The future tense doubles as present conjecture: Tendrá unos treinta años = she is PROBABLY about thirty. It is a guess about now, not a prediction — tiene would state her age as known fact.", tr:"She is probably about thirty years old."},
          {q:"Dijo que ___ tarde. (llegar, él)", c:["llegaría","llegará","llega","llegaba"], a:0, x:"After a past reporting verb (dijo que…), a future seen from that past moment goes into the conditional: llegaría — the 'future in the past'. Llegará clashes with the past frame; llega drops the forward reference.", tr:"He said he would arrive late."}
        ]},
        { id: "es_g10", type: "grammar", title: "Grammar: Present subjunctive — introduction", lesson: "The present subjunctive appears in que-clauses after triggers of Wishes, Emotions, Impersonal expressions, Requests, Doubt and Ojalá (the WEIRDO list), usually with a change of subject: Quiero que tú vengas conmigo (I want you to come with me), Espero que ustedes estén bien (I hope you all are well), Es importante que él estudie (It is important that he study). Form it from the yo form and swap the vowel — -ar verbs take -e, -er/-ir verbs take -a — keeping yo irregularities: tengo → tengan, and irregular sea from ser. Doubt and negated belief take it: Dudo que sea verdad (I doubt it's true), No creo que tengan tiempo (I don't think they have time) — but affirmative belief keeps the indicative: Creo que es verdad. Ojalá ALWAYS takes the subjunctive: Ojalá que no llueva mañana (Hopefully it won't rain tomorrow).", items: [
          {q:"The present subjunctive is triggered by expressions of:", c:["wishes, doubt, emotion, and influence","completed facts","certainty","past habits"], a:0, x:"The subjunctive appears in que-clauses after WEIRDO triggers: Wishes, Emotions, Impersonal expressions, Requests, Doubt and Ojalá. Statements of certainty or plain fact stay in the indicative.", ex:"Quiero que vengas conmigo.", tr:"I want you to come with me."},
          {q:"Creo que es verdad uses the indicative because:", c:["affirmative belief signals certainty","creer always takes subjunctive","es is irregular","it is a question"], a:0, x:"Affirmative belief counts as certainty, so creo que takes the indicative: creo que es verdad. Negating it introduces doubt and flips the clause to the subjunctive: no creo que sea verdad.", ex:"Creo que es verdad.", tr:"I think it is true."},
          {q:"Quiero que tú ___ conmigo. (venir)", c:["vengas","vienes","vendrás","venir"], a:0, x:"A wish imposed on ANOTHER person (querer que + change of subject) triggers the subjunctive: quiero que tú vengas. Vienes (indicative) states fact; with no subject change you would just use quiero venir.", tr:"I want you to come with me."},
          {q:"Espero que ustedes ___ bien. (estar)", c:["estén","están","estarán","estaban"], a:0, x:"Esperar que expresses a hope — a WEIRDO wish — so its que-clause takes the subjunctive: espero que ustedes estén bien. Están (indicative) would report their condition as known fact, not a hoped-for one.", tr:"I hope you all are well."},
          {q:"Es importante que él ___ para el examen. (estudiar)", c:["estudie","estudia","estudiará","estudió"], a:0, x:"Impersonal value judgments (es importante/necesario/mejor que…) trigger the subjunctive: es importante que él estudie. Estudia (indicative) is the trap — the clause expresses influence, not established fact.", tr:"It is important that he study for the exam."},
          {q:"Dudo que ___ verdad. (ser)", c:["sea","es","será","era"], a:0, x:"Dudar que casts doubt, a core subjunctive trigger: dudo que sea verdad. Ser has the irregular subjunctive sea; es (indicative) would assert the very fact the sentence doubts.", tr:"I doubt it is true."},
          {q:"Ojalá que no ___ mañana. (llover)", c:["llueva","llueve","lloverá","llovía"], a:0, x:"Ojalá (from Arabic, 'God willing') ALWAYS takes the subjunctive, with or without que: ojalá que no llueva. Llover is o→ue, giving llueva; the indicative llueve is impossible after ojalá.", tr:"Hopefully it won't rain tomorrow."},
          {q:"Me alegra que te ___ la comida. (gustar)", c:["guste","gusta","gustará","gustaba"], a:0, x:"Emotion verbs (me alegra que…) trigger the subjunctive in the que-clause: me alegra que te guste la comida. Gusta (indicative) misses the trigger — feelings ABOUT an event demand the subjunctive.", tr:"I'm glad you like the food."},
          {q:"No creo que ellos ___ tiempo. (tener)", c:["tengan","tienen","tendrán","tenían"], a:0, x:"Negated belief (no creo que) expresses doubt, so the subjunctive: tengan. Form it from yo tengo — drop the -o, add -a endings: tenga, tengan. Tienen (indicative) would only follow affirmative creo que.", tr:"I don't think they have time."}
        ]},
        { id: "es_c3", type: "conj", title: "Conjugate: Simple past (Pretérito) — regular & key irregulars", tense: "Simple past (Pretérito)", items: [
          {inf:"hablar", en:"to speak", forms:["hablé","hablaste","habló","hablamos","hablaron","hablaron"]},
          {inf:"comer", en:"to eat", forms:["comí","comiste","comió","comimos","comieron","comieron"]},
          {inf:"vivir", en:"to live", forms:["viví","viviste","vivió","vivimos","vivieron","vivieron"]},
          {inf:"ser", irr:1, en:"to be (same as ir)", forms:["fui","fuiste","fue","fuimos","fueron","fueron"]},
          {inf:"ir", irr:1, en:"to go (same as ser)", forms:["fui","fuiste","fue","fuimos","fueron","fueron"]},
          {inf:"hacer", irr:1, en:"to do / make", forms:["hice","hiciste","hizo","hicimos","hicieron","hicieron"]},
          {inf:"tener", irr:1, en:"to have", forms:["tuve","tuviste","tuvo","tuvimos","tuvieron","tuvieron"]}
        ]},
        { id: "es_c4", type: "conj", title: "Conjugate: Imperfect (Imperfecto) — only three irregulars", tense: "Imperfect (Imperfecto)", items: [
          {inf:"hablar", en:"to speak", forms:["hablaba","hablabas","hablaba","hablábamos","hablaban","hablaban"]},
          {inf:"comer", en:"to eat", forms:["comía","comías","comía","comíamos","comían","comían"]},
          {inf:"vivir", en:"to live", forms:["vivía","vivías","vivía","vivíamos","vivían","vivían"]},
          {inf:"ser", irr:1, en:"to be (irregular)", forms:["era","eras","era","éramos","eran","eran"]},
          {inf:"ir", irr:1, en:"to go (irregular)", forms:["iba","ibas","iba","íbamos","iban","iban"]},
          {inf:"ver", irr:1, en:"to see (irregular)", forms:["veía","veías","veía","veíamos","veían","veían"]}
        ]},
        { id: "es_c5", type: "conj", title: "Conjugate: Future (Futuro) — infinitive + endings", tense: "Future (Futuro)", items: [
          {inf:"hablar", en:"to speak", forms:["hablaré","hablarás","hablará","hablaremos","hablarán","hablarán"]},
          {inf:"comer", en:"to eat", forms:["comeré","comerás","comerá","comeremos","comerán","comerán"]},
          {inf:"vivir", en:"to live", forms:["viviré","vivirás","vivirá","viviremos","vivirán","vivirán"]},
          {inf:"tener", irr:1, en:"to have (tendr-)", forms:["tendré","tendrás","tendrá","tendremos","tendrán","tendrán"]},
          {inf:"hacer", irr:1, en:"to do / make (har-)", forms:["haré","harás","hará","haremos","harán","harán"]},
          {inf:"poder", irr:1, en:"to be able (podr-)", forms:["podré","podrás","podrá","podremos","podrán","podrán"]}
        ]},
        { id: "es_c6", type: "conj", title: "Conjugate: Conditional (Condicional) — same stems as the future", tense: "Conditional (Condicional)", items: [
          {inf:"hablar", en:"to speak", forms:["hablaría","hablarías","hablaría","hablaríamos","hablarían","hablarían"]},
          {inf:"comer", en:"to eat", forms:["comería","comerías","comería","comeríamos","comerían","comerían"]},
          {inf:"vivir", en:"to live", forms:["viviría","vivirías","viviría","viviríamos","vivirían","vivirían"]},
          {inf:"tener", irr:1, en:"to have (tendr-)", forms:["tendría","tendrías","tendría","tendríamos","tendrían","tendrían"]},
          {inf:"hacer", irr:1, en:"to do / make (har-)", forms:["haría","harías","haría","haríamos","harían","harían"]}
        ]},
        { id: "es_v_idioms", type: "vocab", title: "Vocab: Idioms & expressions (modismos)", items: [
          {t:"¡Qué padre!", e:"how cool! (Mexico)"},
          {t:"¡Qué chévere!", e:"how cool! (Caribbean/Andes)"},
          {t:"¿Qué onda?", e:"what's up? (Mexico)"},
          {t:"¡Órale!", e:"wow! / come on! (Mexico)"},
          {t:"¡Aguas!", e:"watch out! (Mexico, lit. waters)"},
          {t:"¡No manches!", e:"no way! (Mexico)"},
          {t:"¿Mande?", e:"pardon? / what? (Mexico)"},
          {t:"ahorita", e:"right now / in a bit (LatAm)"},
          {t:"no hay de qué", e:"you're welcome / don't mention it"},
          {t:"buena onda", e:"cool / good vibes"},
          {t:"me da flojera", e:"I can't be bothered / too lazy"},
          {t:"estar crudo", e:"to be hungover (Mexico, lit. raw)"},
          {t:"tomar el pelo", e:"to pull someone's leg (lit. take the hair)"},
          {t:"costar un ojo de la cara", e:"to cost an arm and a leg (lit. an eye of the face)"},
          {t:"estar en las nubes", e:"to daydream (lit. be in the clouds)"},
          {t:"meter la pata", e:"to mess up (lit. stick in the paw)"},
          {t:"no tener pelos en la lengua", e:"to speak bluntly (lit. no hairs on the tongue)"},
          {t:"ser pan comido", e:"to be a piece of cake (lit. eaten bread)"},
          {t:"dar en el clavo", e:"to hit the nail on the head"},
          {t:"al mal tiempo, buena cara", e:"grin and bear it (lit. to bad weather, a good face)"},
          {t:"más vale tarde que nunca", e:"better late than never"},
          {t:"el que madruga, Dios lo ayuda", e:"the early bird gets the worm (lit. God helps the early riser)"},
          {t:"camarón que se duerme, se lo lleva la corriente", e:"you snooze, you lose (lit. the sleeping shrimp is swept away)"}
        ]}
      ]
    }
  ]
};
