// German quiz data — mirrors the two Udemy courses:
//  1. "German for Beginners - A1 Grammar Made Easy & 100+ Exercises" (Esther Hartwig)
//  2. "German for You A2/B1: Grammar, Elementary to Intermediate"
// Vocab units follow the A1 course's Exercises Parts 1-8 themes.
// Grammar units follow the course section titles.
window.QUIZ_DATA = window.QUIZ_DATA || {};
window.QUIZ_DATA.german = {
  name: "German",
  flag: "🇩🇪",
  ttsLang: "de-DE",
  courses: [
    {
      id: "de_a1",
      title: "German for Beginners – A1 Grammar Made Easy",
      units: [
        // ---------- VOCAB (from Exercises Parts 1-8 themes) ----------
        { id: "de_a1_v1", type: "vocab", title: "Vocab: People, family & hobbies (Ex. Part 1)", items: [
          {t:"der Mann", e:"the man"}, {t:"die Frau", e:"the woman"}, {t:"das Kind", e:"the child"},
          {t:"der Freund", e:"the (male) friend"}, {t:"die Freundin", e:"the (female) friend"},
          {t:"die Familie", e:"the family"}, {t:"die Mutter", e:"the mother"}, {t:"der Vater", e:"the father"},
          {t:"die Eltern", e:"the parents"}, {t:"der Bruder", e:"the brother"}, {t:"die Schwester", e:"the sister"},
          {t:"der Sohn", e:"the son"}, {t:"die Tochter", e:"the daughter"}, {t:"die Großmutter", e:"the grandmother"},
          {t:"der Großvater", e:"the grandfather"}, {t:"der Name", e:"the name"},
          {t:"das Hobby", e:"the hobby"}, {t:"lesen", e:"to read"}, {t:"schwimmen", e:"to swim"},
          {t:"tanzen", e:"to dance"}, {t:"singen", e:"to sing"}, {t:"kochen", e:"to cook"},
          {t:"reisen", e:"to travel"}, {t:"Fußball spielen", e:"to play soccer"},
          {t:"Musik hören", e:"to listen to music"}, {t:"sprechen", e:"to speak"},
          {t:"arbeiten", e:"to work"}, {t:"wohnen", e:"to live / reside"},
          {t:"heißen", e:"to be called"}, {t:"kommen", e:"to come"}
        ]},
        { id: "de_a1_v2", type: "vocab", title: "Vocab: Numbers, days & time (Ex. Part 1)", items: [
          {t:"eins", e:"one"}, {t:"zwei", e:"two"}, {t:"drei", e:"three"}, {t:"vier", e:"four"},
          {t:"fünf", e:"five"}, {t:"sechs", e:"six"}, {t:"sieben", e:"seven"}, {t:"acht", e:"eight"},
          {t:"neun", e:"nine"}, {t:"zehn", e:"ten"}, {t:"elf", e:"eleven"}, {t:"zwölf", e:"twelve"},
          {t:"zwanzig", e:"twenty"}, {t:"dreißig", e:"thirty"}, {t:"hundert", e:"one hundred"},
          {t:"tausend", e:"one thousand"}, {t:"der Montag", e:"Monday"}, {t:"der Dienstag", e:"Tuesday"},
          {t:"der Mittwoch", e:"Wednesday"}, {t:"der Donnerstag", e:"Thursday"}, {t:"der Freitag", e:"Friday"},
          {t:"der Samstag", e:"Saturday"}, {t:"der Sonntag", e:"Sunday"}, {t:"heute", e:"today"},
          {t:"morgen", e:"tomorrow"}, {t:"gestern", e:"yesterday"}, {t:"die Woche", e:"the week"},
          {t:"das Jahr", e:"the year"}, {t:"die Uhr", e:"the clock / o'clock"}, {t:"die Zeit", e:"the time"}
        ]},
        { id: "de_a1_v3", type: "vocab", title: "Vocab: Food & drink (Ex. Part 4)", items: [
          {t:"das Essen", e:"the food"}, {t:"das Brot", e:"the bread"}, {t:"das Brötchen", e:"the bread roll"},
          {t:"der Käse", e:"the cheese"}, {t:"die Butter", e:"the butter"}, {t:"das Ei", e:"the egg"},
          {t:"die Milch", e:"the milk"}, {t:"das Wasser", e:"the water"}, {t:"der Saft", e:"the juice"},
          {t:"der Kaffee", e:"the coffee"}, {t:"der Tee", e:"the tea"}, {t:"das Bier", e:"the beer"},
          {t:"der Wein", e:"the wine"}, {t:"der Apfel", e:"the apple"}, {t:"die Banane", e:"the banana"},
          {t:"die Orange", e:"the orange"}, {t:"die Kartoffel", e:"the potato"}, {t:"die Tomate", e:"the tomato"},
          {t:"das Fleisch", e:"the meat"}, {t:"der Fisch", e:"the fish"}, {t:"das Hähnchen", e:"the chicken"},
          {t:"der Reis", e:"the rice"}, {t:"die Nudeln", e:"the noodles / pasta"}, {t:"die Suppe", e:"the soup"},
          {t:"der Kuchen", e:"the cake"}, {t:"das Frühstück", e:"the breakfast"},
          {t:"das Mittagessen", e:"the lunch"}, {t:"das Abendessen", e:"the dinner"},
          {t:"essen", e:"to eat"}, {t:"trinken", e:"to drink"}, {t:"schmecken", e:"to taste"},
          {t:"bestellen", e:"to order"}, {t:"bezahlen", e:"to pay"}, {t:"der Hunger", e:"the hunger"},
          {t:"der Durst", e:"the thirst"}
        ]},
        { id: "de_a1_v4", type: "vocab", title: "Vocab: Daily routine & work (Ex. Part 5)", items: [
          {t:"aufstehen", e:"to get up"}, {t:"aufwachen", e:"to wake up"}, {t:"sich duschen", e:"to shower"},
          {t:"sich anziehen", e:"to get dressed"}, {t:"frühstücken", e:"to have breakfast"},
          {t:"zur Arbeit gehen", e:"to go to work"}, {t:"anfangen", e:"to begin"}, {t:"aufhören", e:"to stop"},
          {t:"einkaufen", e:"to shop / buy groceries"}, {t:"fernsehen", e:"to watch TV"},
          {t:"schlafen", e:"to sleep"}, {t:"schlafen gehen", e:"to go to bed"},
          {t:"die Arbeit", e:"the work / job"}, {t:"der Beruf", e:"the profession"},
          {t:"das Büro", e:"the office"}, {t:"der Lehrer", e:"the (male) teacher"},
          {t:"die Lehrerin", e:"the (female) teacher"}, {t:"der Arzt", e:"the (male) doctor"},
          {t:"die Ärztin", e:"the (female) doctor"}, {t:"der Schüler", e:"the pupil / student"},
          {t:"die Schule", e:"the school"}, {t:"die Universität", e:"the university"},
          {t:"lernen", e:"to learn / study"}, {t:"die Pause", e:"the break"},
          {t:"früh", e:"early"}, {t:"spät", e:"late"}, {t:"immer", e:"always"},
          {t:"oft", e:"often"}, {t:"manchmal", e:"sometimes"}, {t:"nie", e:"never"}
        ]},
        { id: "de_a1_v5", type: "vocab", title: "Vocab: Travelling & transport (Ex. Part 6)", items: [
          {t:"die Reise", e:"the trip / journey"}, {t:"der Urlaub", e:"the vacation"},
          {t:"der Zug", e:"the train"}, {t:"der Bus", e:"the bus"}, {t:"das Auto", e:"the car"},
          {t:"das Flugzeug", e:"the airplane"}, {t:"das Fahrrad", e:"the bicycle"},
          {t:"der Bahnhof", e:"the train station"}, {t:"der Flughafen", e:"the airport"},
          {t:"die Haltestelle", e:"the (bus) stop"}, {t:"die Fahrkarte", e:"the ticket"},
          {t:"der Koffer", e:"the suitcase"}, {t:"die Tasche", e:"the bag"},
          {t:"das Hotel", e:"the hotel"}, {t:"die Stadt", e:"the city"}, {t:"das Land", e:"the country"},
          {t:"das Meer", e:"the sea"}, {t:"der Strand", e:"the beach"}, {t:"der Berg", e:"the mountain"},
          {t:"fahren", e:"to drive / ride"}, {t:"fliegen", e:"to fly"}, {t:"ankommen", e:"to arrive"},
          {t:"abfahren", e:"to depart"}, {t:"buchen", e:"to book"}, {t:"besuchen", e:"to visit"},
          {t:"die Karte", e:"the map / card"}, {t:"links", e:"left"}, {t:"rechts", e:"right"},
          {t:"geradeaus", e:"straight ahead"}, {t:"weit", e:"far"}, {t:"nah", e:"near"}
        ]},
        { id: "de_a1_v6", type: "vocab", title: "Vocab: Home & living (Ex. Part 7)", items: [
          {t:"das Haus", e:"the house"}, {t:"die Wohnung", e:"the apartment"}, {t:"das Zimmer", e:"the room"},
          {t:"die Küche", e:"the kitchen"}, {t:"das Badezimmer", e:"the bathroom"},
          {t:"das Schlafzimmer", e:"the bedroom"}, {t:"das Wohnzimmer", e:"the living room"},
          {t:"der Garten", e:"the garden"}, {t:"der Balkon", e:"the balcony"},
          {t:"die Tür", e:"the door"}, {t:"das Fenster", e:"the window"}, {t:"die Wand", e:"the wall"},
          {t:"der Boden", e:"the floor"}, {t:"der Tisch", e:"the table"}, {t:"der Stuhl", e:"the chair"},
          {t:"das Bett", e:"the bed"}, {t:"der Schrank", e:"the wardrobe / cabinet"},
          {t:"das Sofa", e:"the sofa"}, {t:"die Lampe", e:"the lamp"}, {t:"der Kühlschrank", e:"the refrigerator"},
          {t:"die Miete", e:"the rent"}, {t:"mieten", e:"to rent"}, {t:"umziehen", e:"to move (house)"},
          {t:"wohnen", e:"to live / reside"}, {t:"putzen", e:"to clean"}, {t:"die Nachbarn", e:"the neighbors"},
          {t:"der Schlüssel", e:"the key"}, {t:"die Treppe", e:"the stairs"},
          {t:"oben", e:"upstairs / above"}, {t:"unten", e:"downstairs / below"}
        ]},
        // ---------- GRAMMAR (from course sections) ----------
        { id: "de_a1_g1", type: "grammar", title: "Grammar: The subject – nouns, articles & pronouns", lesson: "Every German noun has a gender shown by its article: der (masculine), die (feminine), das (neuter) — e.g. der Tisch (the table), die Lampe (the lamp), das Fenster (the window). All plural nouns take die in the Nominativ, and many plurals add an umlaut: der Apfel → die Äpfel (apples), das Kind → die Kinder (children).\n\nSome endings reveal the gender reliably: -chen is always neuter (das Mädchen — the girl), and -ung is feminine (die Wohnung — the apartment). In a compound noun, the LAST noun decides the article: die Haustür, because die Tür.\n\nSubjects can be replaced by pronouns matching the gender: Der Mann ist alt → Er ist alt (He is old). Watch out for sie/Sie: lowercase sie = she or they, capitalized Sie = formal you.", items: [
          {q:"Which article goes with 'Frau' (woman)?", c:["die","der","das","den"], a:0, x:"Every German noun has a fixed grammatical gender shown by its article: der (m), die (f), das (n). Frau is feminine, so die Frau. Gender must be memorized with each noun; den is not a Nominativ form at all.", ex:"Die Frau liest ein Buch.", tr:"The woman is reading a book."},
          {q:"Which article goes with 'Mädchen' (girl)?", c:["das","die","der","dem"], a:0, x:"Noun endings can reveal gender: the diminutive -chen is ALWAYS neuter, so das Mädchen — grammatical gender beats natural gender here. Die would only fit a feminine noun or a plural.", ex:"Das Mädchen spielt im Garten.", tr:"The girl is playing in the garden."},
          {q:"What is the plural of 'das Kind'?", c:["die Kinder","die Kinds","die Kinden","das Kinder"], a:0, x:"German plurals use several endings (here -er), and every plural noun takes die in the Nominativ regardless of its singular gender: das Kind → die Kinder. There is no English-style -s plural like 'Kinds'.", ex:"Die Kinder sind heute in der Schule.", tr:"The children are at school today."},
          {q:"Replace the subject with a pronoun: 'Der Mann ist alt.' → ___ ist alt.", c:["Er","Sie","Es","Ihn"], a:0, x:"A pronoun must match the grammatical gender of the noun it replaces: der Mann (masculine) → er. Sie would replace a feminine noun, es a neuter one, and ihn is the Akkusativ of er — wrong for a subject.", tr:"The man is old. → He is old."},
          {q:"In a compound noun like 'die Haustür', which part decides the article?", c:["the last noun (Tür)","the first noun (Haus)","always das","the longer noun"], a:0, x:"In a compound noun, the LAST element decides gender and article: Haus + Tür → die Haustür, because die Tür is feminine. The first noun (das Haus) only adds meaning; its gender is irrelevant.", ex:"Die Haustür ist wieder offen.", tr:"The front door is open again."},
          {q:"'Sie' with a capital S means:", c:["you (formal)","she","they","it"], a:0, x:"Capitalization distinguishes the pronouns: capital Sie is the formal 'you' (singular or plural). Lowercase sie means 'she' or 'they' — the verb ending and context tell those two apart.", ex:"Woher kommen Sie, Herr Müller?", tr:"Where do you come from, Mr. Müller?"},
          {q:"Which noun is masculine?", c:["der Tisch","die Lampe","das Fenster","die Tür"], a:0, x:"Article gender is arbitrary and must be memorized per noun: der marks masculine, so der Tisch. Lampe and Tür are feminine (die), Fenster is neuter (das) — household objects follow no logical pattern.", ex:"Der Tisch steht in der Küche.", tr:"The table is in the kitchen."},
          {q:"Nouns ending in -ung (e.g. die Wohnung) are usually:", c:["feminine","masculine","neuter","plural only"], a:0, x:"Certain suffixes fix a noun's gender: -ung nouns are reliably feminine — die Wohnung, die Zeitung, die Übung. Other feminine endings are -heit, -keit, -schaft; -chen and -lein are always neuter.", ex:"Die Wohnung ist groß und hell.", tr:"The apartment is big and bright."},
          {q:"What is the plural of 'der Apfel'?", c:["die Äpfel","die Apfels","die Apfeln","die Apfel"], a:0, x:"Many masculine nouns ending in -el/-er form the plural with just an umlaut and no added ending: der Apfel → die Äpfel. All plurals take die in the Nominativ, and German never adds an English-style -s here.", ex:"Die Äpfel schmecken sehr gut.", tr:"The apples taste very good."}
        ]},
        { id: "de_a1_g2", type: "grammar", title: "Grammar: The verb – present tense & Nominativ", lesson: "Present-tense verbs take endings that match the subject: ich mache, du machst, er/sie/es macht, wir machen, ihr macht, sie machen. If the stem ends in -t or -d, an extra e is inserted for du/er: du arbeitest (you work).\n\nMany strong verbs change their vowel ONLY in the du and er/sie/es forms: e→i as in er spricht (he speaks), e→ie as in du liest (you read), a→ä as in er fährt (he drives). Sein (to be) is fully irregular: ich bin, du bist, er ist, wir sind, ihr seid, sie sind.\n\nIn a normal statement the conjugated verb always stands in position 2: Ich trinke Kaffee (I drink coffee). The subject of the sentence is always in the Nominativ case.", items: [
          {q:"Conjugate: ich ___ (machen)", c:["mache","machst","macht","machen"], a:0, x:"Present-tense endings must match the subject: ich takes -e → ich mache (du machst, er macht). Machst and macht belong to du and er/ihr — using them with ich is the classic mix-up.", tr:"I do / I make."},
          {q:"Conjugate: du ___ (arbeiten)", c:["arbeitest","arbeitst","arbeitet","arbeiten"], a:0, x:"If a verb stem ends in -t or -d, an extra -e- is inserted before the du/er/ihr endings so it can be pronounced: du arbeitest, er arbeitet. Plain 'arbeitst' is unpronounceable and wrong.", tr:"You work."},
          {q:"Conjugate: er ___ (sprechen)", c:["spricht","sprecht","sprichst","sprecht"], a:0, x:"Many strong verbs change e→i, but ONLY in the du and er/sie/es forms: sprechen → du sprichst, er spricht. The other persons keep e (wir sprechen); 'er sprecht' uses the ihr ending and skips the required vowel change.", tr:"He speaks."},
          {q:"Conjugate: du ___ (lesen)", c:["liest","lest","lese","liesst"], a:0, x:"Strong verbs with long e change e→ie in the du and er forms: lesen → du liest, er liest. Because the stem ends in -s, the -st ending reduces to -t: liest, not 'liesst'; 'lest' is the ihr-form.", tr:"You read."},
          {q:"Conjugate: wir ___ (sein)", c:["sind","seid","bin","ist"], a:0, x:"Sein (to be) is fully irregular and must be memorized: ich bin, du bist, er ist, wir sind, ihr seid, sie sind. Wir pairs with sind; seid is the ihr-form — those two are the classic mix-up.", tr:"We are."},
          {q:"Conjugate: ihr ___ (haben)", c:["habt","habet","haben","hat"], a:0, x:"Haben is irregular only in du hast and er hat (the b drops); the ihr-form is regular stem + -t: ihr habt. Haben would be the wir/sie-form, hat the er-form.", tr:"You (all) have."},
          {q:"Which sentence is a correct statement?", c:["Ich trinke Kaffee.","Trinke ich Kaffee.","Kaffee ich trinke.","Ich Kaffee trinke."], a:0, x:"In a German main-clause statement, the conjugated verb must be the SECOND element: Ich (1) trinke (2) Kaffee. Verb-first order makes a yes/no question, and verb-last order belongs only in subclauses.", ex:"Ich trinke jeden Morgen Kaffee.", tr:"I drink coffee every morning."},
          {q:"The Nominativ case is used for:", c:["the subject of the sentence","the direct object","the indirect object","possession"], a:0, x:"The Nominativ marks the subject — who or what performs the action (Ich trinke Kaffee). The direct object takes the Akkusativ, the indirect object the Dativ, and possession the Genitiv.", ex:"Der Hund schläft auf dem Sofa.", tr:"The dog is sleeping on the sofa."},
          {q:"Conjugate: er ___ (fahren)", c:["fährt","fahrt","fahret","fährst"], a:0, x:"Strong verbs with stem vowel a add an umlaut in the du and er/sie/es forms only: fahren → du fährst, er fährt (but wir fahren, ihr fahrt). 'Er fahrt' misses the required umlaut.", tr:"He drives."}
        ]},
        { id: "de_a1_g3", type: "grammar", title: "Grammar: The Akkusativ", lesson: "The Akkusativ is the case of the direct object — the thing or person the action happens to. The key rule: only the MASCULINE articles change. Der becomes den and ein becomes einen; feminine, neuter and plural stay the same: Ich sehe den Mann (I see the man), Ich habe einen Hund (I have a dog), but Er kauft eine Lampe (He buys a lamp).\n\nPossessives follow the same pattern: Das ist mein Bruder (Nominativ) → Ich besuche meinen Bruder (I visit my brother).\n\nPronouns also change: er → ihn (Siehst du ihn? — Do you see him?), du → dich (Ich liebe dich — I love you). Most verbs, like haben and sehen, take an Akkusativ object; sein, werden and bleiben take the Nominativ instead.", items: [
          {q:"Ich sehe ___ Mann.", c:["den","der","dem","das"], a:0, x:"The direct object stands in the Akkusativ, where only the MASCULINE article changes: der → den. So Ich sehe den Mann. Dem is the Dativ (for indirect objects or verbs like helfen), not for a direct object.", tr:"I see the man."},
          {q:"Which article changes in the Akkusativ?", c:["only the masculine","all of them","feminine and neuter","only the plural"], a:0, x:"Key Akkusativ rule: only the masculine changes (der→den, ein→einen). Feminine die/eine, neuter das/ein and plural die are identical to the Nominativ — that's why masculine objects need special attention.", ex:"Er kauft den Tisch und das Sofa.", tr:"He buys the table and the sofa."},
          {q:"Ich habe ___ Hund. (ein)", c:["einen","ein","einem","einer"], a:0, x:"Hund is masculine, and a masculine direct object changes ein → einen: Ich habe einen Hund. Plain ein would only be right for a neuter object (ein Buch); einem is the Dativ form.", tr:"I have a dog."},
          {q:"Er kauft ___ Lampe.", c:["eine","einen","einem","ein"], a:0, x:"Only masculine articles change in the Akkusativ; feminine stays identical to the Nominativ. Lampe is feminine, so: Er kauft eine Lampe. Einen would be the masculine form (einen Tisch).", tr:"He buys a lamp."},
          {q:"Siehst du ___? (er)", c:["ihn","er","ihm","sie"], a:0, x:"Personal pronouns decline too: as a direct object, er becomes ihn in the Akkusativ — Siehst du ihn? Ihm is the Dativ form (Ich helfe ihm), and er itself can only be the subject.", tr:"Do you see him?"},
          {q:"Ich liebe ___. (du)", c:["dich","dir","du","dein"], a:0, x:"Lieben takes a direct object, so du takes its Akkusativ form dich: Ich liebe dich. Dir is the Dativ form, reserved for Dativ verbs like helfen or danken (Ich helfe dir).", tr:"I love you."},
          {q:"Das ist ___ Bruder. (mein) — Ich besuche ___ Bruder. (mein)", c:["mein / meinen","meinen / mein","mein / meinem","meiner / meinen"], a:0, x:"Possessives decline like ein: after sein the predicate stays Nominativ (Das ist mein Bruder), but as direct object of besuchen, masculine adds -en: Ich besuche meinen Bruder. Only the masculine shows this change.", tr:"That is my brother. — I am visiting my brother."},
          {q:"Which verb typically takes an Akkusativ object?", c:["haben","sein","werden","bleiben"], a:0, x:"Most transitive verbs, including haben, put their object in the Akkusativ: Ich habe einen Hund. Sein, werden and bleiben are linking verbs — what follows them stays in the Nominativ (Das ist ein Hund).", ex:"Ich habe einen neuen Computer.", tr:"I have a new computer."}
        ]},
        { id: "de_a1_g4", type: "grammar", title: "Grammar: Special verbs – modal & separable", lesson: "Modal verbs (können, müssen, wollen, dürfen, sollen, mögen) express ability, obligation, desire or permission. Their ich- and er-forms are identical and take NO ending: ich kann, er will, ich darf. The modal sits in position 2 and the other verb goes to the END as an infinitive: Ich kann heute nicht kommen (I can't come today). Möchte expresses a polite wish: Ich möchte einen Kaffee (I would like a coffee).\n\nSeparable verbs like aufstehen and einkaufen split in the present tense — the prefix jumps to the end: Ich stehe um 7 Uhr auf (I get up at 7), Wir kaufen heute ein (We're shopping today).\n\nTo say you like doing something, add gern after the verb: Ich schwimme gern (I like swimming).", items: [
          {q:"Ich ___ schwimmen. (können)", c:["kann","könne","kannst","könnt"], a:0, x:"Modal verbs drop the usual endings in the singular: the ich- and er-forms are identical with NO ending — ich kann, er kann. Kannst is the du-form; 'könne' is not a present-indicative form.", tr:"I can swim."},
          {q:"Du ___ jetzt gehen. (müssen)", c:["musst","muss","müsst","müssen"], a:0, x:"Müssen, like all modals, changes its vowel in the singular: ich muss, du musst, er muss. The du-form adds -st to the singular stem muss-; müsst (with umlaut) is the ihr-form.", tr:"You have to go now."},
          {q:"Where does the infinitive go with a modal verb?", c:["at the end of the sentence","right after the modal","in position 2","at the beginning"], a:0, x:"Modal sentences form a verb bracket: the conjugated modal takes position 2 and the main verb goes to the END as an infinitive — Ich kann heute nicht kommen. Placing the infinitive right after the modal copies English order and is wrong.", ex:"Ich kann heute leider nicht kommen.", tr:"Unfortunately, I can't come today."},
          {q:"Er ___ Deutsch lernen. (wollen)", c:["will","wollt","willst","wolle"], a:0, x:"Wollen changes o→i in the singular, and the er-form of a modal never takes -t: er will. Wollt is the ihr-form, willst the du-form — modals always have identical ich- and er-forms.", tr:"He wants to learn German."},
          {q:"___ ich hier rauchen? (dürfen)", c:["Darf","Dürfe","Dürft","Darfst"], a:0, x:"Dürfen expresses permission and changes ü→a in the singular: ich darf, du darfst. In a yes/no question the conjugated verb comes first: Darf ich hier rauchen? Dürft is the ihr-form.", tr:"May I smoke here?"},
          {q:"'Ich stehe um 7 Uhr auf.' The infinitive of this verb is:", c:["aufstehen","stehen","aufsteigen","anstehen"], a:0, x:"Separable verbs split in the present tense: the stem is conjugated in position 2 and the prefix moves to the very end. 'Ich stehe … auf' can only come from aufstehen — spot the stranded prefix to identify the verb.", ex:"Ich stehe um 7 Uhr auf.", tr:"I get up at 7 o'clock."},
          {q:"Separable verb: 'einkaufen' — Wir ___ heute ___.", c:["kaufen … ein","einkaufen … -","kaufen ein … -","ein … kaufen"], a:0, x:"Separable prefixes detach in a main clause: conjugated stem in position 2, prefix at the very end — Wir kaufen heute ein. The verb stays together only as an infinitive or at the end of a subclause.", tr:"We are going shopping today."},
          {q:"How do you say 'I like swimming' with 'gern'?", c:["Ich schwimme gern.","Ich gern schwimme.","Ich schwimme mögen.","Ich mag schwimme."], a:0, x:"To say you like doing something, use the normal verb + the adverb gern right after it: Ich schwimme gern. Gern is not a verb, so it can't be conjugated, and mögen + a conjugated verb ('Ich mag schwimme') is impossible.", ex:"Ich schwimme gern im Meer.", tr:"I like swimming in the sea."},
          {q:"'Ich möchte einen Kaffee' expresses:", c:["a polite wish","an obligation","a permission","an ability"], a:0, x:"Möchte is the Konjunktiv II of mögen and expresses a polite wish: Ich möchte einen Kaffee = I would like a coffee. It is softer than will (want); obligation is müssen and permission dürfen.", ex:"Ich möchte einen Kaffee.", tr:"I would like a coffee."}
        ]},
        { id: "de_a1_g5", type: "grammar", title: "Grammar: The Dativ", lesson: "The Dativ marks the indirect object — usually the person who receives something: Ich gebe der Frau das Buch (I give the woman the book). The articles change like this: masculine and neuter der/das → dem, feminine die → der, plural die → den, and plural nouns themselves add -n: mit den Kindern (with the children).\n\nSome verbs take ONLY a Dativ object even though they feel like they should take a direct object: helfen, danken, gefallen. So: Ich helfe dem Mann (I help the man), Er dankt mir (He thanks me), Das gefällt mir (I like that).\n\nCertain prepositions always take the Dativ too, e.g. mit: Wir sprechen mit der Lehrerin (We talk with the teacher). Pronouns: ich → mir, du → dir.", items: [
          {q:"Ich helfe ___ Mann.", c:["dem","den","der","das"], a:0, x:"A few verbs — helfen, danken, gefallen — take their object in the Dativ instead of the Akkusativ. Masculine der → dem: Ich helfe dem Mann. Den (Akkusativ) would fit sehen but never helfen.", tr:"I help the man."},
          {q:"Masculine and neuter articles in the Dativ become:", c:["dem","den","der","des"], a:0, x:"In the Dativ, masculine and neuter share one article: der/das → dem (dem Mann, dem Kind). Den is the masculine Akkusativ — and, confusingly, also the Dativ PLURAL article (den Kindern).", ex:"Ich gebe dem Kind einen Apfel.", tr:"I give the child an apple."},
          {q:"The feminine article in the Dativ is:", c:["der","die","dem","den"], a:0, x:"Feminine die becomes der in the Dativ: mit der Frau, der Lehrerin. Don't confuse it with masculine Nominativ der — the noun's gender plus the case context tell you which der you're seeing.", ex:"Er dankt der Lehrerin für alles.", tr:"He thanks the teacher for everything."},
          {q:"Ich gebe ___ Frau das Buch.", c:["der","die","dem","den"], a:0, x:"The recipient (indirect object) stands in the Dativ: Ich gebe der Frau das Buch. Frau is feminine, so die → der; das Buch is the thing given and stays in the Akkusativ.", tr:"I give the woman the book."},
          {q:"Er dankt ___. (ich)", c:["mir","mich","ich","mein"], a:0, x:"Danken is a Dativ verb, so the person thanked takes the Dativ pronoun: ich → mir — Er dankt mir. Mich is the Akkusativ form, which danken never governs.", tr:"He thanks me."},
          {q:"Which verb takes only a Dativ object?", c:["gefallen","sehen","kaufen","lieben"], a:0, x:"Gefallen belongs to the Dativ-only verbs (with helfen and danken): the person pleased is in the Dativ — Das gefällt mir. Sehen, kaufen and lieben all take ordinary Akkusativ objects.", ex:"Das neue Auto gefällt mir sehr.", tr:"I like the new car a lot."},
          {q:"Plural nouns in the Dativ usually add:", c:["-n","-e","-s","nothing"], a:0, x:"The Dativ plural changes both words: the article die → den AND the noun itself adds -n (unless its plural already ends in -n or -s): mit den Kindern, von den Freunden.", ex:"Sie spielt mit den Kindern.", tr:"She is playing with the children."},
          {q:"Wir sprechen mit ___ Lehrerin.", c:["der","die","dem","den"], a:0, x:"Mit belongs to the fixed Dativ prepositions (aus, bei, mit, nach, seit, von, zu) — the case never varies. Lehrerin is feminine, and feminine die → der in the Dativ: mit der Lehrerin.", tr:"We are speaking with the teacher."}
        ]},
        { id: "de_a1_g6", type: "grammar", title: "Grammar: Questions", lesson: "German has two question types. Yes/no questions start with the verb: Kommst du aus Berlin? (Do you come from Berlin?). W-questions start with a question word, and the verb stays in position 2: Wann kommst du? (When are you coming?).\n\nLearn the key W-words: wie (how — Wie heißt du? What's your name?), wo (where, location — Wo wohnst du?), woher (where from — Woher kommst du?), wohin (where to — Wohin gehst du?), wann (when — Wann beginnt der Film?), was (what — Was kostet das Buch? What does the book cost?), wer (who).\n\nNote the wo/woher/wohin trio: wo asks about a place you're AT, woher about origin, wohin about destination.", items: [
          {q:"Turn into a yes/no question: 'Du kommst aus Berlin.'", c:["Kommst du aus Berlin?","Du kommst aus Berlin?","Aus Berlin kommst du?","Woher kommst du?"], a:0, x:"Yes/no questions put the conjugated verb FIRST and the subject second: Kommst du aus Berlin? Statement order with a question mark ('Du kommst aus Berlin?') only works as a surprised echo, and woher would change the question type.", ex:"Kommst du aus Berlin?", tr:"You come from Berlin. → Do you come from Berlin?"},
          {q:"___ heißt du? (What's your name?)", c:["Wie","Was","Wer","Wo"], a:0, x:"German asks for names with wie (how), not was: Wie heißt du? — literally 'How are you called?'. Was is for things (Was ist das?); 'Was heißt du' is the classic English-driven error.", tr:"What's your name?"},
          {q:"___ wohnst du?", c:["Wo","Woher","Wohin","Wann"], a:0, x:"The wo-trio splits English 'where' by direction: wo = location (where AT), woher = origin, wohin = destination. Living somewhere is a location, so: Wo wohnst du?", tr:"Where do you live?"},
          {q:"___ kommst du? — Aus Italien.", c:["Woher","Wo","Wohin","Wie"], a:0, x:"Woher asks about origin — where someone comes FROM — which matches the answer aus Italien: Woher kommst du? Plain wo asks about current location, wohin about the destination.", tr:"Where do you come from? — From Italy."},
          {q:"___ gehst du? — Nach Hause.", c:["Wohin","Wo","Woher","Wer"], a:0, x:"Wohin asks about the destination — where someone is going TO — matching nach Hause: Wohin gehst du? Wo would ask where you are now, woher where you come from.", tr:"Where are you going? — Home."},
          {q:"___ kostet das Buch?", c:["Was","Wie viel Uhr","Wer","Wessen"], a:0, x:"Was (what) asks about a thing, here the price: Was kostet das Buch? (Wie viel kostet… also works.) Wer asks about a person and wessen about possession — neither fits a price.", tr:"What does the book cost?"},
          {q:"___ beginnt der Film? — Um 20 Uhr.", c:["Wann","Wo","Wie","Was"], a:0, x:"Wann asks about a point in time, matching the answer um 20 Uhr: Wann beginnt der Film? As in every W-question, the verb stays in position 2 right after the question word.", tr:"When does the movie start? — At 8 p.m."},
          {q:"In a W-question, the verb is in position:", c:["2","1","last","3"], a:0, x:"In a W-question the question word fills position 1 and the conjugated verb keeps position 2: Wann (1) kommst (2) du? Only yes/no questions move the verb to position 1; verb-final order is for subclauses.", ex:"Wann beginnt der Film heute?", tr:"When does the movie start today?"}
        ]},
        { id: "de_a1_g7", type: "grammar", title: "Grammar: Prepositions", lesson: "German prepositions come in three groups. Always Dativ: aus, bei, mit, nach, seit, von, zu — Er fährt mit dem Bus (He goes by bus). Always Akkusativ: durch, für, gegen, ohne, um — Das Geschenk ist für den Mann (The gift is for the man).\n\nThe third group (in, an, auf, über, unter, vor, hinter, neben, zwischen) are two-way prepositions: they take the Akkusativ for movement toward a place (wohin?) and the Dativ for a fixed location (wo?). Compare: Ich gehe ins Kino (in das — I'm going TO the movies) vs. Ich bin im Kino (in dem — I'm AT the movies); Das Buch liegt auf dem Tisch (The book lies on the table — location, Dativ).\n\nFor countries without an article, use nach: Wir fahren nach Deutschland (We're going to Germany).", items: [
          {q:"Which prepositions ALWAYS take the Dativ?", c:["aus, bei, mit, nach, von, zu","durch, für, gegen, ohne, um","an, auf, in","über, unter, vor"], a:0, x:"Aus, bei, mit, nach, seit, von, zu ALWAYS govern the Dativ, motion or not: mit dem Bus, zu dem Arzt. Durch/für/gegen/ohne/um form the fixed Akkusativ group, and in/an/auf are two-way prepositions.", ex:"Er fährt mit dem Bus zur Schule.", tr:"He takes the bus to school."},
          {q:"Which prepositions ALWAYS take the Akkusativ?", c:["durch, für, gegen, ohne, um","aus, bei, mit","in, an, auf","seit, von, zu"], a:0, x:"Durch, für, gegen, ohne, um always govern the Akkusativ: für den Mann, ohne einen Freund. Aus/bei/mit are fixed Dativ, and in/an/auf are two-way prepositions that switch case with meaning.", ex:"Das Geschenk ist für den Mann.", tr:"The gift is for the man."},
          {q:"Two-way prepositions take the Akkusativ when there is:", c:["movement toward a place (wohin?)","a fixed location (wo?)","a person involved","a plural noun"], a:0, x:"The nine two-way prepositions (in, an, auf, über, unter, vor, hinter, neben, zwischen) take the Akkusativ for movement toward a goal (wohin?) and the Dativ for a fixed location (wo?). Ask the question word to pick the case.", ex:"Ich hänge das Bild an die Wand.", tr:"I am hanging the picture on the wall."},
          {q:"Ich gehe ___ Kino. (in + das)", c:["ins","im","in dem","in den"], a:0, x:"Gehen expresses movement toward a goal (wohin?), so the two-way preposition in takes the Akkusativ: in das Kino = ins Kino. Im (in dem) is the Dativ and would mean you are already inside.", tr:"I am going to the movies."},
          {q:"Ich bin ___ Kino. (in + das)", c:["im","ins","in den","an das"], a:0, x:"Sein describes a fixed location (wo?), so in takes the Dativ: in dem Kino = im Kino. Ins (in das) is the Akkusativ contraction, correct only with movement verbs like gehen.", tr:"I am at the movies."},
          {q:"Das Buch liegt ___ Tisch.", c:["auf dem","auf den","auf der","auf das"], a:0, x:"Liegen describes location (wo?), so the two-way preposition auf takes the Dativ: auf dem Tisch. Auf den (Akkusativ) would be right only for movement onto the table, e.g. with legen.", tr:"The book is lying on the table."},
          {q:"Er fährt ___ Bus zur Arbeit.", c:["mit dem","mit den","mit der","ohne dem"], a:0, x:"Mit is a fixed Dativ preposition; Bus is masculine, so der → dem: mit dem Bus. Mit den would be Dativ plural and mit der feminine — the noun's gender picks the form.", tr:"He takes the bus to work."},
          {q:"Wir fahren ___ Deutschland.", c:["nach","in","zu","bei"], a:0, x:"Destinations without an article — most countries and all cities — take nach: nach Deutschland, nach Berlin. In die/den is for countries WITH an article (in die Schweiz); zu is for people and institutions.", tr:"We are traveling to Germany."}
        ]},
        { id: "de_a1_g8", type: "grammar", title: "Grammar: Adjectives & comparison", lesson: "An adjective before a noun needs an ending. After der/die/das in the Nominativ it is -e: der alte Mann (the old man). After ein, the adjective shows the gender itself: ein schönes Haus (a beautiful house — neuter -es). In the Akkusativ masculine, both article and adjective take -en: Ich sehe einen neuen Film (I'm watching a new movie).\n\nThe comparative adds -er (often with umlaut): groß → größer (bigger). German never uses 'mehr' for this. The superlative uses am + -sten: am größten. Irregular sets to memorize: gut – besser – am besten; gern – lieber – am liebsten.\n\nFor comparing, use als for inequality: Berlin ist größer als München (Berlin is bigger than Munich), and so … wie for equality: Er ist so groß wie ich (He is as tall as I am).", items: [
          {q:"Der ___ Mann wohnt hier. (alt)", c:["alte","alter","alten","altes"], a:0, x:"After a definite article the adjective takes a weak ending, in the Nominativ singular just -e: der alte Mann. The article already signals gender and case; 'alter' is the strong form used when no article does that job.", tr:"The old man lives here."},
          {q:"Ich sehe einen ___ Film. (neu)", c:["neuen","neue","neuer","neues"], a:0, x:"In the Akkusativ masculine, article AND adjective both take -en: einen neuen Film. Masculine is the only gender that changes in the Akkusativ; neue/neuer are Nominativ endings and don't fit a direct object.", tr:"I am watching a new movie."},
          {q:"Das ist ein ___ Haus. (schön)", c:["schönes","schöne","schönen","schöner"], a:0, x:"After ein the article shows no gender, so the adjective must show it: neuter takes -es — ein schönes Haus. Schöner would signal masculine (ein schöner Mann), schöne feminine.", tr:"That is a beautiful house."},
          {q:"The comparative of 'groß' is:", c:["größer","mehr groß","größte","am großten"], a:0, x:"German forms every comparative with -er, usually adding an umlaut to a/o/u: groß → größer. Unlike English, German NEVER uses mehr before the adjective — 'mehr groß' is impossible even for long words.", ex:"Mein Bruder ist größer als ich.", tr:"My brother is taller than I am."},
          {q:"The superlative of 'gut' is:", c:["am besten","am gutesten","besser","am gutsten"], a:0, x:"The superlative pattern is am + adjective + -sten: am größten. Gut is irregular through both steps — gut, besser, am besten (like good/better/best) — so a regular 'am gutesten' does not exist.", ex:"Dieser Kuchen schmeckt am besten.", tr:"This cake tastes the best."},
          {q:"Berlin ist größer ___ München.", c:["als","wie","dann","von"], a:0, x:"After a comparative, 'than' is als: Berlin ist größer als München. Wie is the classic trap — it belongs only to equality (so groß wie); 'größer wie' is heard colloquially but is not standard.", tr:"Berlin is bigger than Munich."},
          {q:"Er ist so groß ___ ich.", c:["wie","als","dann","so"], a:0, x:"Equality uses so + basic adjective + wie: Er ist so groß wie ich. Als would require a comparative (größer als ich), and the adjective never takes -er inside the so … wie pattern.", tr:"He is as tall as I am."},
          {q:"The comparative of 'gern' is:", c:["lieber","gerner","mehr gern","am liebsten"], a:0, x:"Gern compares irregularly: gern – lieber – am liebsten. Ich schwimme lieber = I prefer swimming. 'Gerner' doesn't exist, and am liebsten is the superlative (liking to do something most of all).", ex:"Ich trinke lieber Tee als Kaffee.", tr:"I prefer tea to coffee."}
        ]},
        { id: "de_a1_g9", type: "grammar", title: "Grammar: The past (Perfekt & Präteritum)", lesson: "The Perfekt (spoken past) = haben or sein + Partizip II at the end. Most verbs use haben: Ich habe Pizza gegessen (I ate pizza). Verbs of movement or change use sein: Wir sind nach Berlin gefahren (We drove to Berlin).\n\nBuilding the Partizip II: regular verbs take ge- + stem + -t (machen → gemacht); irregular verbs take ge- + -en, often with a vowel change (sehen → gesehen). Separable verbs put ge in the middle: einkaufen → eingekauft. Verbs with inseparable prefixes (be-, ver-, er-) take NO ge-: besuchen → besucht.\n\nSein, haben and the modal verbs are normally used in the Präteritum instead: ich war (I was), er hatte (he had), ich konnte nicht kommen (I couldn't come).", items: [
          {q:"Ich ___ gestern Pizza gegessen.", c:["habe","bin","hatte","war"], a:0, x:"The Perfekt = auxiliary in position 2 + Partizip II at the end. Essen involves no movement or change of state, so it takes haben: Ich habe gegessen. Bin (sein) is reserved for verbs like fahren or gehen.", tr:"I ate pizza yesterday."},
          {q:"Wir ___ nach Berlin gefahren.", c:["sind","haben","waren","hatten"], a:0, x:"Verbs of movement from A to B (fahren, gehen, fliegen) and of change of state form the Perfekt with sein: Wir sind gefahren. Haben suits most other verbs; waren gefahren would be the Plusquamperfekt.", tr:"We drove to Berlin."},
          {q:"The Partizip II of 'machen' is:", c:["gemacht","gemachen","macht","gemakt"], a:0, x:"Regular (weak) verbs build the Partizip II as ge- + stem + -t: machen → gemacht. The -en ending ('gemachen') belongs to strong verbs like sehen → gesehen — machen isn't one of them.", ex:"Ich habe meine Hausaufgaben gemacht.", tr:"I have done my homework."},
          {q:"The Partizip II of 'sehen' is:", c:["gesehen","gesieht","geseht","sah"], a:0, x:"Strong (irregular) verbs build the Partizip II with ge- + -en, often changing the vowel: sehen → gesehen. The weak pattern ge-…-t ('geseht') doesn't apply, and sah is the Präteritum, not a participle.", ex:"Wir haben gestern einen Film gesehen.", tr:"We watched a movie yesterday."},
          {q:"The Partizip II of 'einkaufen' is:", c:["eingekauft","geeinkauft","einkauft","eingekaufen"], a:0, x:"Separable verbs insert -ge- BETWEEN prefix and stem: ein + ge + kauft → eingekauft. Putting ge- before the prefix ('geeinkauft') is the classic error; the prefix always stays at the front.", ex:"Sie hat am Samstag eingekauft.", tr:"She went shopping on Saturday."},
          {q:"The Partizip II of 'besuchen' is:", c:["besucht","gebesucht","besuchen","besuchte"], a:0, x:"Verbs with inseparable, unstressed prefixes (be-, ver-, er-, ent-, zer-) form the Partizip II with NO ge-: besuchen → besucht. 'Gebesucht' is impossible; only the -t ending marks the participle.", ex:"Er hat seine Großmutter besucht.", tr:"He visited his grandmother."},
          {q:"The Präteritum of 'sein' (ich) is:", c:["war","bin gewesen","wäre","seite"], a:0, x:"Sein and haben normally appear in the one-word Präteritum even in speech: ich war, du warst. 'Bin gewesen' exists but sounds heavy; wäre is Konjunktiv II (would be), not a plain past.", ex:"Ich war gestern sehr müde.", tr:"I was very tired yesterday."},
          {q:"The Präteritum of 'haben' (er) is:", c:["hatte","habte","hat","hätte"], a:0, x:"Haben has an irregular Präteritum stem hatt-: ich hatte, er hatte. 'Habte' wrongly applies the regular pattern, hat is present tense, and hätte (umlaut!) is the Konjunktiv II 'would have'.", ex:"Er hatte keine Zeit für uns.", tr:"He had no time for us."},
          {q:"Ich ___ gestern nicht kommen. (können, past)", c:["konnte","kann","könnte","gekonnt"], a:0, x:"Like sein and haben, modal verbs normally use the Präteritum for the past: ich konnte nicht kommen. Watch the umlaut: konnte = could (past fact), könnte = could (Konjunktiv II, hypothetical).", tr:"I couldn't come yesterday."}
        ]},
        { id: "de_a1_g10", type: "grammar", title: "Grammar: The imperative", lesson: "The imperative gives commands and has three forms. For du: drop the -st ending AND the pronoun: du kommst → Komm! (Come!). For ihr: use the normal ihr-form without the pronoun: Geht! (Go!). For formal Sie: verb + Sie: Warten Sie, bitte! (Please wait!).\n\nTwo tricky rules for the du-form: verbs with an e→i/ie vowel change KEEP it — Lies das Buch! (Read the book!) — but a→ä verbs do NOT keep the umlaut: Fahr langsam! (Drive slowly!), not 'Fähr'.\n\nSein is irregular: Sei leise! (Be quiet!), ihr: Seid!, formal: Seien Sie! Also remember that some verbs take a Dativ object even in commands: Antworte mir! (Answer me!) — antworten takes the Dativ.", items: [
          {q:"Informal singular (du) of 'kommen':", c:["Komm!","Kommst!","Kommen!","Komme du!"], a:0, x:"The du-imperative removes both the pronoun and the -st ending: du kommst → Komm! Keeping -st ('Kommst!') or adding du ('Komme du!') is wrong; a final -e (Komme!) is possible but old-fashioned.", ex:"Komm bitte schnell nach Hause!", tr:"Please come home quickly!"},
          {q:"Formal (Sie) of 'warten':", c:["Warten Sie!","Warte Sie!","Sie warten!","Wartet Sie!"], a:0, x:"The formal imperative is verb + Sie, i.e. the infinitive form with inverted pronoun: Warten Sie, bitte! Sie must appear and must FOLLOW the verb — 'Sie warten' in that order is just a statement.", ex:"Warten Sie bitte einen Moment!", tr:"Please wait a moment!"},
          {q:"Informal plural (ihr) of 'gehen':", c:["Geht!","Gehen!","Geh!","Gehet!"], a:0, x:"The ihr-imperative is simply the present ihr-form minus the pronoun: ihr geht → Geht! No extra ending is added ('Gehet' is archaic); Geh! would be the du-form.", ex:"Geht jetzt bitte ins Bett!", tr:"Please go to bed now!"},
          {q:"Imperative (du) of 'lesen':", c:["Lies!","Les!","Lese!","Liest!"], a:0, x:"Verbs with an e→i/ie vowel change KEEP it in the du-imperative: du liest → Lies! (likewise Sprich!, Nimm!). Forms without the change ('Les!', 'Lese!') are wrong, and Liest keeps the -st that must drop.", ex:"Lies das Buch bis morgen!", tr:"Read the book by tomorrow!"},
          {q:"Imperative (du) of 'fahren':", c:["Fahr!","Fähr!","Fährst!","Fahre du!"], a:0, x:"Unlike the e→i change, the a→ä umlaut is NOT kept in the imperative: du fährst, but Fahr langsam! 'Fähr!' is the classic overgeneralization — only e-verbs carry their vowel change into the command.", ex:"Fahr bitte langsamer!", tr:"Please drive more slowly!"},
          {q:"Imperative (du) of 'sein':", c:["Sei!","Bist!","Sein!","Seid du!"], a:0, x:"Sein has its own irregular imperative built on sei-: du → Sei leise!, ihr → Seid!, formal → Seien Sie! It is not formed from the present-tense forms, so 'Bist!' is impossible.", ex:"Sei leise, das Baby schläft!", tr:"Be quiet, the baby is sleeping!"},
          {q:"'Antworte mir!' — why 'mir'?", c:["antworten takes the Dativ","it's Akkusativ","it's a possessive","mir is the subject"], a:0, x:"Verb case government survives in commands: antworten takes a Dativ object, so the person answered is mir — Antworte mir! Mich (Akkusativ) would be wrong; antworten never governs that case.", ex:"Antworte mir!", tr:"Answer me!"}
        ]}
      ]
    },
    {
      id: "de_a2b1",
      title: "German for You – A2/B1 Grammar",
      units: [
        { id: "de_b1_g1", type: "grammar", title: "Grammar: Reflexive verbs & pronouns", lesson: "Reflexive verbs point back at the subject with a reflexive pronoun: mich, dich, sich, uns, euch, sich. In the 3rd person (er/sie/es/sie-plural) it is always sich: Er interessiert sich für Musik (He is interested in music). Many combine with a fixed preposition: Ich freue mich auf das Wochenende (I'm looking forward to the weekend), Erinnerst du dich an den Urlaub? (Do you remember the vacation?).\n\nKey rule: when the sentence also has a direct object (often a body part or clothing), the reflexive pronoun switches to the DATIV: Du wäschst dir die Hände (You wash your hands), Ich ziehe mir eine Jacke an (I put on a jacket).\n\n'Real' (echte) reflexive verbs like sich beeilen (to hurry) exist ONLY with the pronoun — you can't 'beeilen' someone else.", items: [
          {q:"Ich freue ___ auf das Wochenende.", c:["mich","mir","sich","mein"], a:0, x:"Reflexive verbs use a pronoun mirroring the subject, normally in the Akkusativ: sich freuen auf → ich freue mich. Mir is the Dativ form, used only when another direct object is present (Ich wasche mir die Hände).", tr:"I am looking forward to the weekend."},
          {q:"Du wäschst ___ die Hände.", c:["dir","dich","sich","dein"], a:0, x:"When a reflexive verb also has a direct object — typically a body part or clothing — the reflexive pronoun switches to the DATIV: Du wäschst dir die Hände. Dich (Akkusativ) is right only without that object: Du wäschst dich.", tr:"You are washing your hands."},
          {q:"Er interessiert ___ für Musik.", c:["sich","ihm","ihn","seiner"], a:0, x:"In the 3rd person (er/sie/es and plural sie) the reflexive pronoun is ALWAYS sich: Er interessiert sich für Musik. Ihm/ihn are ordinary personal pronouns and would point to someone else, not back to the subject.", tr:"He is interested in music."},
          {q:"Wir treffen ___ um acht.", c:["uns","sich","euch","wir"], a:0, x:"The reflexive/reciprocal pronoun matches the subject: wir → uns — Wir treffen uns um acht (we meet each other). Sich is reserved for 3rd-person subjects, and euch would pair with ihr.", tr:"We are meeting at eight."},
          {q:"A 'real' (echt) reflexive verb is one that:", c:["only exists with a reflexive pronoun","can drop the pronoun","takes the Genitiv","has no infinitive"], a:0, x:"'Real' (echte) reflexive verbs exist ONLY with their reflexive pronoun: sich beeilen has no version without it — you cannot 'beeilen' someone else. Verbs like waschen, by contrast, are only optionally reflexive.", ex:"Wir müssen uns jetzt beeilen.", tr:"We have to hurry now."},
          {q:"Erinnerst du ___ an den Urlaub?", c:["dich","dir","sich","dein"], a:0, x:"Sich erinnern an is reflexive with an Akkusativ pronoun: du → dich — Erinnerst du dich an den Urlaub? Dir is the Dativ form, used only when the sentence also contains a separate direct object.", tr:"Do you remember the vacation?"},
          {q:"Ich ziehe ___ eine Jacke an.", c:["mir","mich","sich","meine"], a:0, x:"Because the sentence has a direct object (eine Jacke), the reflexive pronoun moves to the Dativ: Ich ziehe mir eine Jacke an. Without that object it stays Akkusativ: Ich ziehe mich an (I get dressed).", tr:"I am putting on a jacket."}
        ]},
        { id: "de_b1_g2", type: "grammar", title: "Grammar: Verbs with prepositions", lesson: "Many German verbs come with a FIXED preposition that you must memorize together with its case — the combination often can't be guessed from English. With Akkusativ: warten auf (Ich warte auf den Bus — I'm waiting for the bus), denken an (Sie denkt an ihre Familie — She thinks of her family), sprechen über, sich interessieren für, sich ärgern über.\n\nWith Dativ: träumen von (Ich träume von einem Haus am Meer — I dream of a house by the sea) and abhängen von (Das hängt von dem Wetter ab — That depends on the weather).\n\nBest strategy: always learn verb + preposition + case as one chunk, e.g. \"warten auf + Akk\". Also useful: etwas = something, nichts = nothing (jemand/niemand = someone/no one).", items: [
          {q:"Ich warte ___ den Bus.", c:["auf","für","an","um"], a:0, x:"German verbs carry FIXED prepositions that must be learned as a chunk with their case: warten auf + Akkusativ = to wait for → Ich warte auf den Bus. Für is the trap from English 'wait for' — 'warten für' doesn't exist.", tr:"I am waiting for the bus."},
          {q:"Sie denkt oft ___ ihre Familie.", c:["an","auf","über","von"], a:0, x:"Denken an + Akkusativ = to think of someone/something: Sie denkt an ihre Familie. Fixed verb–preposition pairs can't be guessed from English 'think of/about' — an is simply what denken takes.", tr:"She often thinks of her family."},
          {q:"Wir sprechen ___ das Problem.", c:["über","auf","an","für"], a:0, x:"Sprechen über + Akkusativ = to talk about: Wir sprechen über das Problem. Each verb owns its preposition — auf belongs to warten, an to denken; memorize the pair rather than translating 'about'.", tr:"We are talking about the problem."},
          {q:"Er interessiert sich ___ Geschichte.", c:["für","an","auf","in"], a:0, x:"Sich interessieren für + Akkusativ = to be interested in: Er interessiert sich für Geschichte. English 'interested IN' makes in tempting, but the German pairing is fixed with für.", tr:"He is interested in history."},
          {q:"Ich träume ___ einem Haus am Meer.", c:["von","über","an","auf"], a:0, x:"Träumen von + Dativ = to dream of: Ich träume von einem Haus (the Dativ shows in einem). English 'dream about' suggests über, but the fixed German pairing is von.", tr:"I dream of a house by the sea."},
          {q:"Sie ärgert sich ___ den Lärm.", c:["über","auf","an","mit"], a:0, x:"Sich ärgern über + Akkusativ = to be annoyed about: Sie ärgert sich über den Lärm (den = Akkusativ masculine). Auf belongs to other verbs (warten auf, sich freuen auf) — the pairing is verb-specific.", tr:"She is annoyed about the noise."},
          {q:"Das hängt ___ dem Wetter ab.", c:["von","an","auf","mit"], a:0, x:"Abhängen von + Dativ = to depend on: Das hängt von dem Wetter ab — note the separable prefix at the end. English 'depend ON' tempts an or auf, but German fixes this verb with von.", tr:"That depends on the weather."},
          {q:"'Etwas' and 'nichts' mean:", c:["something / nothing","someone / no one","always / never","everything / anything"], a:0, x:"The indefinite pronouns come in pairs: etwas/nichts for THINGS (something/nothing) and jemand/niemand for PEOPLE (someone/no one). They stand alone and don't change form in everyday German.", ex:"Möchtest du etwas trinken?", tr:"Would you like something to drink?"}
        ]},
        { id: "de_b1_g3", type: "grammar", title: "Grammar: Subclauses (weil, dass, wenn, obwohl)", lesson: "Subordinating conjunctions — weil (because), dass (that), wenn (if/when), obwohl (although), ob (whether) — push the conjugated verb to the END of their clause: Ich bleibe zu Hause, weil ich krank bin (I'm staying home because I'm sick); Ich weiß, dass du müde bist (I know that you're tired). In the Perfekt, the auxiliary goes last: …, weil er spät aufgestanden ist.\n\nFor indirect yes/no questions use ob: Ich frage mich, ob er kommt (I wonder whether he's coming). For the past, als marks a ONE-TIME situation (Als ich Kind war — when I was a child), while wenn is for repeated events or conditions.\n\nContrast trotzdem (nevertheless), which is an adverb linking two MAIN clauses, with obwohl, which starts a subclause. Also: kennen = to be familiar with places/people (Ich kenne Berlin), wissen = to know facts.", items: [
          {q:"Ich bleibe zu Hause, weil ich krank ___.", c:["bin","ist","sein","werde"], a:0, x:"Weil is a subordinating conjunction, so the conjugated verb moves to the END of its clause: …, weil ich krank bin. The subject ich demands bin; main-clause order ('weil ich bin krank') is the classic spoken-German error.", tr:"I am staying home because I am sick."},
          {q:"In a subclause, the conjugated verb goes:", c:["to the end","to position 2","to position 1","before the subject"], a:0, x:"All subordinating conjunctions (weil, dass, wenn, obwohl, ob) push the conjugated verb to the final position of their clause. Position 2 is main-clause order; denn is the one 'because' that keeps it.", ex:"Ich bleibe zu Hause, weil es heute regnet.", tr:"I am staying home because it is raining today."},
          {q:"Ich weiß, ___ du müde bist.", c:["dass","weil","ob","denn"], a:0, x:"After verbs of knowing, saying or thinking, the content clause is introduced by dass: Ich weiß, dass du müde bist. Weil would give a reason, ob asks 'whether', and denn connects two main clauses without moving the verb.", tr:"I know that you are tired."},
          {q:"___ es regnet, gehen wir spazieren.", c:["Obwohl","Weil","Dass","Denn"], a:0, x:"Obwohl (although) concedes a contrast: despite the rain, we walk anyway. Weil would absurdly make the rain the REASON for the walk. As a subordinating conjunction, obwohl sends the verb to the end of its clause.", tr:"Although it is raining, we are going for a walk."},
          {q:"'Als' vs 'wenn' for the past: 'Als ich Kind war…' means:", c:["a single period/event in the past","a repeated event","a future event","a condition"], a:0, x:"For the past, als covers a single event or ONE continuous period (like a whole childhood): Als ich Kind war. Wenn in the past means 'whenever' (repeated) or states a condition — the two are not interchangeable.", ex:"Als ich Kind war, spielte ich oft draußen.", tr:"When I was a child…"},
          {q:"Ich frage mich, ___ er kommt.", c:["ob","dass","weil","wann denn"], a:0, x:"Indirect yes/no questions use ob (whether): Ich frage mich, ob er kommt. Dass would present his coming as an established fact rather than an open question; like all subclauses, the ob-clause is verb-final.", tr:"I wonder whether he is coming."},
          {q:"'kennen' vs 'wissen': Ich ___ Berlin gut.", c:["kenne","weiß","wisse","kennt"], a:0, x:"Kennen = to be familiar with people, places or things through experience; wissen = to know facts. A city is something you know by acquaintance: Ich kenne Berlin gut — 'Ich weiß Berlin' is impossible.", tr:"I know Berlin well."},
          {q:"Er kommt nicht mit. Ich gehe trotzdem. — 'trotzdem' is:", c:["an adverb connecting two main clauses","a subordinating conjunction","a preposition","a modal particle"], a:0, x:"Trotzdem (nevertheless) is an ADVERB linking two main clauses, so the verb stays in position 2: Ich gehe trotzdem. Obwohl expresses the same contrast but opens a verb-final subclause — that's the key difference.", ex:"Er kommt nicht mit. Ich gehe trotzdem.", tr:"He isn't coming along. I am going anyway."},
          {q:"Weil er spät aufgestanden ___, hat er den Bus verpasst.", c:["ist","hat","war","wird"], a:0, x:"Aufstehen is a movement verb, so its Perfekt takes sein, and in a weil-clause the auxiliary moves to the very end: …, weil er spät aufgestanden ist. Hat is impossible because aufstehen never uses haben.", tr:"Because he got up late, he missed the bus."}
        ]},
        { id: "de_b1_g4", type: "grammar", title: "Grammar: Präteritum & two-verb combinations", lesson: "The Präteritum is the simple one-word past. Regular verbs add -te to the stem: machen → er machte (he did), spielen → er spielte (he played). Irregular verbs change the stem vowel and take no -te: gehen → ich ging (I went), kommen → wir kamen (we came), wissen → sie wusste (she knew).\n\nIn everyday SPOKEN German, the past is usually the Perfekt; the Präteritum dominates in written narration and with sein, haben and the modal verbs.\n\nWhen a modal verb goes into the Perfekt together with another verb, use the double infinitive instead of a participle: Ich habe schwimmen können (I was able to swim) — NOT 'gekonnt'.", items: [
          {q:"The Präteritum of 'gehen' (ich) is:", c:["ging","gehte","gegangen","gang"], a:0, x:"Strong verbs form the Präteritum by changing the stem vowel with NO -te: gehen → ich ging. 'Gehte' wrongly applies the weak pattern; gegangen is the Partizip II and needs an auxiliary (ich bin gegangen).", ex:"Gestern ging ich früh nach Hause.", tr:"Yesterday I went home early."},
          {q:"The Präteritum of 'machen' (er) is:", c:["machte","machtete","macht","gemacht"], a:0, x:"Weak (regular) verbs form the Präteritum with stem + -te: machen → er machte. There is no vowel change and the er-form adds no extra -t; gemacht is the participle, not a stand-alone past form.", ex:"Er machte gestern das Abendessen.", tr:"He made dinner yesterday."},
          {q:"In everyday spoken German, the past is usually expressed with:", c:["the Perfekt","the Präteritum","the Plusquamperfekt","the Futur II"], a:0, x:"Spoken German prefers the Perfekt for past events (Ich habe … gemacht). The Präteritum rules written narration — and even in speech it is the norm for sein, haben and the modals (war, hatte, konnte).", ex:"Ich habe gestern Pizza gegessen.", tr:"I ate pizza yesterday."},
          {q:"The Präteritum of 'kommen' (wir) is:", c:["kamen","kommten","kamten","gekommen"], a:0, x:"Kommen is strong: the Präteritum changes the vowel (o→a) and takes plain endings — wir kamen. 'Kommten/kamten' smuggle the weak -te into a strong verb; gekommen is the participle, not a finite past.", ex:"Wir kamen sehr spät nach Hause.", tr:"We came home very late."},
          {q:"Ich habe schwimmen ___. (Perfekt of 'können' with verb)", c:["können","gekonnt","konnte","kann"], a:0, x:"A modal in the Perfekt with another verb uses the DOUBLE INFINITIVE: Ich habe schwimmen können — both verbs stand as infinitives at the end. The participle gekonnt appears only when the modal is alone (Ich habe es gekonnt).", tr:"I was able to swim."},
          {q:"The Präteritum of 'wissen' (sie/sg.) is:", c:["wusste","wisste","weißte","gewusst"], a:0, x:"Wissen is a mixed verb: its Präteritum changes the vowel like a strong verb yet keeps the weak -te ending — sie wusste. 'Wisste' and 'weißte' keep the wrong stem; gewusst is the Partizip II.", ex:"Sie wusste die Antwort nicht.", tr:"She didn't know the answer."},
          {q:"Er ___ als Kind jeden Tag Fußball. (spielen, Präteritum)", c:["spielte","spielt","gespielt","spielen"], a:0, x:"A habitual action in past narration takes the Präteritum; spielen is weak, so stem + -te: er spielte jeden Tag. Spielt is present tense, and gespielt would need an auxiliary (hat gespielt).", tr:"As a child, he played soccer every day."}
        ]},
        { id: "de_b1_g5", type: "grammar", title: "Grammar: Adjectives & articles without nouns", lesson: "When there is NO article before the noun, the adjective must carry the 'strong' ending that shows gender and case itself: Ich trinke schwarzen Kaffee (I drink black coffee — Akkusativ masculine -en), Schönes Wetter heute! (Beautiful weather — neuter -es), Frische Äpfel sind gesund (Fresh apples are healthy — plural -e).\n\nArticles and adjectives can also stand alone, replacing a noun that is already known: Welches Auto möchtest du? — Das rote. (Which car would you like? — The red one.)\n\nEin-words used as pronouns keep their case ending: Hast du einen Stift? — Ja, ich habe einen (Yes, I have one). Finally, welcher/welche/welches asks 'which one' of a known set; was für ein asks 'what kind of'.", items: [
          {q:"Ich trinke gern ___ Kaffee. (schwarz, no article)", c:["schwarzen","schwarzer","schwarze","schwarz"], a:0, x:"With no article present, the adjective takes the STRONG ending and shows case and gender itself. Kaffee is masculine and the direct object (Akkusativ), so -en: schwarzen Kaffee. Schwarzer would be the Nominativ form.", tr:"I like drinking black coffee."},
          {q:"___ Wetter heute! (schön, no article, neuter)", c:["Schönes","Schöne","Schönen","Schöner"], a:0, x:"Without an article, the adjective carries the ending the article would have shown: neuter Nominativ (das) → -es, hence Schönes Wetter! Schöne would signal feminine or plural, schönen a masculine Akkusativ or a Dativ.", tr:"Beautiful weather today!"},
          {q:"Welches Auto möchtest du? — ___ (the red one)", c:["Das rote.","Das rotes.","Der rote.","Rotes das."], a:0, x:"An article + adjective can replace a noun that is already known, keeping exactly the ending used before the noun: das rote (Auto) — weak -e after das. 'Das rotes' wrongly piles the strong -es on top of the article.", tr:"Which car would you like? — The red one."},
          {q:"'Welcher, welche, welches' is used to ask:", c:["which one (of a known set)","what kind of","whose","how many"], a:0, x:"Welcher/welche/welches asks 'which one' out of a known, limited set — like choosing among specific cars. Was für ein asks 'what kind of' in general; whose = wessen, how many = wie viele.", ex:"Welches Auto gefällt dir am besten?", tr:"Which car do you like best?"},
          {q:"Hast du einen Stift? — Ja, ich habe ___.", c:["einen","ein","eins","einer"], a:0, x:"Ein-words used as stand-alone pronouns keep their full case ending: Stift is masculine Akkusativ → Ja, ich habe einen. Bare 'ein' cannot stand alone; the neuter stand-alone form is eins (ein Auto → eins).", tr:"Do you have a pen? — Yes, I have one."},
          {q:"Frische ___ sind gesund. (Äpfel, no article + adjective ending)", c:["Äpfel","Äpfeln","Äpfels","Apfel"], a:0, x:"In the plural with no article, the adjective takes the strong Nominativ ending -e: Frische Äpfel sind gesund. The noun itself adds -n only in the Dativ plural (mit frischen Äpfeln), not here in the Nominativ.", tr:"Fresh apples are healthy."}
        ]},
        { id: "de_b1_g6", type: "grammar", title: "Grammar: Prepositional phrases (da-/wo-)", lesson: "When a verb has a fixed preposition and you refer back to a THING, replace 'preposition + it' with da(r)- + preposition: Interessierst du dich für Sport? — Ja, ich interessiere mich dafür (Yes, I'm interested in it); Wir sprechen darüber (We're talking about it).\n\nTo ASK about a thing, use wo(r)- + preposition: Worauf wartest du? — Auf den Bus (What are you waiting for? — The bus); Woran erinnerst du dich? (What do you remember?).\n\nThe -r- is inserted whenever the preposition starts with a vowel: daran, darauf, darüber, worauf. Crucial exception: for PEOPLE you keep the preposition + pronoun or wen: Ich denke oft an sie (I often think of her), and you ask An wen denkst du? — never daran/woran for a person.", items: [
          {q:"Interessierst du dich für Sport? — Ja, ich interessiere mich ___.", c:["dafür","für es","damit","dazu"], a:0, x:"When a preposition verb refers back to a THING, German fuses da(r)- + preposition: sich interessieren für → Ja, ich interessiere mich dafür. 'Für es' is the English-style trap — preposition + es is not used for things.", tr:"Are you interested in sports? — Yes, I am interested in it."},
          {q:"___ wartest du? — Auf den Bus.", c:["Worauf","Auf was","Wofür","Woran"], a:0, x:"To ask about a THING with a preposition verb, fuse wo(r)- + that verb's preposition: warten auf → Worauf wartest du? 'Auf was' is colloquial only, and wofür/woran carry the wrong prepositions for warten.", tr:"What are you waiting for? — For the bus."},
          {q:"Denkst du an deine Oma? — Ja, ich denke oft ___ sie.", c:["an","daran","davon","auf"], a:0, x:"Da-compounds are only for things — for PEOPLE you keep preposition + pronoun: Ich denke oft an sie. Daran would treat Grandma as an object; overusing da-compounds for people is the classic error.", tr:"Do you think about your grandma? — Yes, I often think of her."},
          {q:"Wir sprechen über den Film. → Wir sprechen ___.", c:["darüber","über ihn","damit","dazu"], a:0, x:"Referring back to a thing (der Film), preposition + pronoun collapses into da(r)- + preposition: sprechen über → Wir sprechen darüber. 'Über ihn' is reserved for people; damit and dazu contain the wrong prepositions.", tr:"We are talking about the movie. → We are talking about it."},
          {q:"When does da- become dar- (e.g. daran)?", c:["when the preposition starts with a vowel","with Dativ prepositions","with people","never"], a:0, x:"The linking -r- is inserted purely for pronunciation when the preposition begins with a vowel: daran, darauf, darüber — but damit, davon. The same rule produces woran and worauf in questions.", ex:"Denkst du an den Termin? — Ja, ich denke daran.", tr:"Are you thinking of the appointment? — Yes, I am thinking of it."},
          {q:"___ erinnerst du dich? — An unseren Urlaub.", c:["Woran","Worauf","Wovon","An wen"], a:0, x:"Sich erinnern an + a THING is questioned with wo(r)- + an → Woran erinnerst du dich? The vacation is a thing, so woran fits; asking about a person would instead require An wen erinnerst du dich?", tr:"What do you remember? — Our vacation."}
        ]},
        { id: "de_b1_g7", type: "grammar", title: "Grammar: Genitiv & n-declension", lesson: "The Genitiv expresses possession. Masculine and neuter take des + noun with -s/-es: das Auto des Mannes (the man's car); feminine and plural take der with no ending on the noun: die Tasche der Frau (the woman's bag). In spoken German, von + Dativ often replaces it: das Auto von dem Mann.\n\nThe prepositions wegen (because of), trotz (despite), während (during) and statt (instead of) take the Genitiv: Trotz des Regens gingen wir spazieren (Despite the rain we went for a walk).\n\nSeparately, weak nouns (n-declension) — mostly masculine nouns for people like der Junge, der Student, der Kollege — add -n or -en in EVERY case except the Nominativ: Ich sehe den Jungen (I see the boy), mit dem Studenten.", items: [
          {q:"Das ist das Auto ___ Mannes.", c:["des","dem","der","den"], a:0, x:"Possession uses the Genitiv: masculine and neuter take des and the noun itself adds -s/-es — das Auto des Mannes. Dem is Dativ, den Akkusativ; der would be the feminine/plural Genitiv, wrong for Mann.", tr:"That is the man's car."},
          {q:"The Genitiv of 'die Frau' is:", c:["der Frau","des Frau","der Frauen","dem Frau"], a:0, x:"Feminine nouns take der in the Genitiv and add NO ending: die Tasche der Frau. The -s/-es on the noun belongs only to masculine and neuter Genitivs (des Mannes, des Kindes).", ex:"Die Tasche der Frau ist neu.", tr:"The woman's bag is new."},
          {q:"Colloquial replacement for the Genitiv:", c:["von + Dativ","zu + Dativ","für + Akkusativ","aus + Dativ"], a:0, x:"Spoken German routinely replaces the Genitiv with von + Dativ: das Auto des Mannes → das Auto von dem Mann (vom Mann). Only von expresses possession this way; zu, für and aus change the meaning.", ex:"Das ist das Auto von meinem Bruder.", tr:"That is my brother's car."},
          {q:"Which preposition takes the Genitiv?", c:["wegen","mit","für","bei"], a:0, x:"A small set of prepositions governs the Genitiv: wegen (because of), trotz (despite), während (during), statt (instead of) — wegen des Wetters. Mit and bei are fixed Dativ prepositions, für is Akkusativ.", ex:"Wegen des Wetters bleiben wir zu Hause.", tr:"Because of the weather, we are staying home."},
          {q:"Weak noun (n-declension): Ich sehe den ___. (Junge)", c:["Jungen","Junge","Junges","Jungem"], a:0, x:"Weak nouns (n-declension) — mostly masculine nouns denoting people — add -n/-en in EVERY case except the Nominativ: der Junge → Ich sehe den Jungen, mit dem Jungen. Changing the article alone is not enough.", tr:"I see the boy."},
          {q:"Which noun follows the n-declension?", c:["der Student","der Tisch","das Kind","der Lehrer"], a:0, x:"The n-declension covers masculine person-nouns, typically ending in -e (der Junge, der Kollege) or borrowed like der Student: den Studenten, dem Studenten. Tisch, Kind and Lehrer decline normally with no added -en.", ex:"Ich kenne den Studenten aus Berlin.", tr:"I know the student from Berlin."},
          {q:"Trotz ___ Regens gingen wir spazieren.", c:["des","dem","den","der"], a:0, x:"Trotz governs the Genitiv: masculine Regen → trotz des Regens, with the noun adding -s. Colloquial 'trotz dem Regen' (Dativ) is heard, but standard German keeps the Genitiv after trotz, wegen, während and statt.", tr:"Despite the rain, we went for a walk."}
        ]},
        { id: "de_b1_g8", type: "grammar", title: "Grammar: Relative clauses", lesson: "A relative pronoun takes its GENDER and NUMBER from the noun it describes, but its CASE from its role inside the relative clause. Subject: Der Mann, der dort steht (The man who is standing there). Direct object → Akkusativ: Der Film, den ich gesehen habe (The movie that I saw). Dativ verb → Dativ: Die Frau, der ich geholfen habe (The woman I helped — helfen takes the Dativ).\n\nWith a preposition, the preposition comes first and sets the case: Das Haus, in dem wir wohnen (The house we live in). Possession uses deren/dessen: Die Kinder, deren Eltern arbeiten (The children whose parents work).\n\nAfter alles, nichts and etwas the pronoun is was: Alles, was du sagst, stimmt (Everything you say is true). Relative clauses are subclauses, so the conjugated verb goes to the end.", items: [
          {q:"Der Mann, ___ dort steht, ist mein Lehrer.", c:["der","den","dem","das"], a:0, x:"A relative pronoun takes gender and number from the noun it refers to, but its CASE from its role inside the clause. Here it is the subject of steht: masculine Nominativ → der. Den would wrongly mark it as an object.", tr:"The man who is standing there is my teacher."},
          {q:"Der Film, ___ ich gesehen habe, war toll.", c:["den","der","dem","das"], a:0, x:"Der Film is masculine, and inside the relative clause the pronoun is the object of 'ich gesehen habe', so Akkusativ: den. Der (Nominativ) would make the film the subject — but ich already is.", tr:"The movie that I saw was great."},
          {q:"Die Frau, ___ ich geholfen habe, ist Nachbarin.", c:["der","die","den","dem"], a:0, x:"The case comes from the verb INSIDE the relative clause: helfen governs the Dativ, so feminine die Frau → Dativ der. It looks like a masculine article, but here der is the feminine Dativ form.", tr:"The woman whom I helped is a neighbor."},
          {q:"Das Haus, in ___ wir wohnen, ist alt.", c:["dem","das","den","der"], a:0, x:"When a preposition belongs to the relative clause, it stands before the pronoun and assigns the case: living somewhere is a location, so in + Dativ → in dem (neuter, matching das Haus). In das would imply movement into it.", tr:"The house we live in is old."},
          {q:"Die Kinder, ___ Eltern arbeiten, spielen hier.", c:["deren","denen","die","der"], a:0, x:"Possession inside a relative clause uses dessen (masc./neuter) or deren (feminine/plural). The parents belong to die Kinder (plural), so deren: die Kinder, deren Eltern arbeiten. Denen is the Dativ plural, not possessive.", tr:"The children whose parents work play here."},
          {q:"Alles, ___ du sagst, stimmt.", c:["was","das","dass","wer"], a:0, x:"After the indefinites alles, nichts, etwas (and after a whole clause), the relative pronoun is was, not das: Alles, was du sagst, stimmt. Dass is a conjunction, not a pronoun, so it cannot refer back to alles.", tr:"Everything you say is true."},
          {q:"In a relative clause, the conjugated verb goes:", c:["to the end","to position 2","right after the pronoun","first"], a:0, x:"A relative clause is a subordinate clause, so its conjugated verb moves to the END: Der Film, den ich gesehen habe. Position 2 for the verb applies only in main clauses.", ex:"Das Buch, das ich gerade lese, ist spannend.", tr:"The book I am reading right now is exciting."}
        ]},
        { id: "de_b1_g9", type: "grammar", title: "Grammar: Sentence order & 'nicht'", lesson: "The slot before the verb (position 2) is the Vorfeld and holds exactly ONE element. If something other than the subject stands there, subject and verb invert: Heute habe ich keine Zeit (Today I have no time).\n\nIn the middle of the sentence, adverbials follow the order 'tekamolo': temporal – kausal – modal – lokal (time – cause – manner – place): Ich fahre morgen mit dem Zug nach Berlin (Tomorrow I'm going to Berlin by train).\n\nNegation has two tools. Kein negates nouns with ein or no article: Ich habe kein Auto (I don't have a car). Nicht negates everything else: for the whole sentence it moves toward the end — Ich verstehe das nicht (I don't understand that) — and to negate an adjective it stands directly before it: Das Auto ist nicht neu (The car is not new).", items: [
          {q:"Typical order of adverbials in the Mittelfeld ('tekamolo'):", c:["time – cause – manner – place","place – time – manner","manner – time – place","cause – place – time"], a:0, x:"German orders mid-sentence adverbials te-ka-mo-lo: temporal, kausal, modal, lokal (time – cause – manner – place). English instinct puts place early — in German, place comes LAST: Ich fahre morgen mit dem Zug nach Berlin.", ex:"Ich fahre morgen mit dem Zug nach Berlin.", tr:"Tomorrow I am going to Berlin by train."},
          {q:"Ich fahre ___ nach Berlin. (tomorrow + by train — correct order)", c:["morgen mit dem Zug","mit dem Zug morgen","nach Berlin morgen","morgen nach Berlin mit dem Zug"], a:0, x:"Apply tekamolo: time (morgen) before manner (mit dem Zug), with place (nach Berlin) last: Ich fahre morgen mit dem Zug nach Berlin. Putting the manner or place phrase first copies English order and is wrong.", tr:"Tomorrow I am going to Berlin by train."},
          {q:"Negate the whole sentence: 'Ich verstehe das.'", c:["Ich verstehe das nicht.","Ich nicht verstehe das.","Ich verstehe nicht das.","Nicht ich verstehe das."], a:0, x:"To negate a whole sentence, nicht moves toward the end, after pronouns and definite objects: Ich verstehe das nicht. 'Nicht das' would narrow the negation to that one word (not THAT, but something else).", ex:"Ich verstehe das nicht.", tr:"I understand that. → I don't understand that."},
          {q:"'Ich habe ___ Auto.' (no car)", c:["kein","nicht ein","nicht","keinen"], a:0, x:"Kein negates nouns that have ein or no article, and it declines like ein: Auto is neuter Akkusativ, so kein Auto with no ending. 'Nicht ein' is unidiomatic here, and keinen would be the masculine form.", tr:"I don't have a car."},
          {q:"Where does 'nicht' go to negate an adjective?", c:["directly before it","after it","at the very end","at the start"], a:0, x:"To negate one specific element such as a predicate adjective, nicht stands DIRECTLY BEFORE it: Das Auto ist nicht neu. Only whole-sentence negation pushes nicht toward the end of the clause.", ex:"Das Auto ist nicht neu.", tr:"The car is not new."},
          {q:"Only ONE element can stand before the verb in position 2. This slot is called:", c:["das Vorfeld","das Mittelfeld","das Nachfeld","die Klammer"], a:0, x:"The slot before the conjugated verb is the Vorfeld, and it holds exactly ONE constituent — that is what fixes the verb in position 2. The Mittelfeld lies inside the verb bracket; the Nachfeld follows it.", ex:"Heute habe ich keine Zeit.", tr:"Today I have no time."},
          {q:"Heute ___ ich keine Zeit.", c:["habe","ich habe","haben","hab ich"], a:0, x:"Position 2 is reserved for the verb: when heute fills the Vorfeld, subject and verb invert — Heute habe ich keine Zeit. 'Heute ich habe' keeps English order and illegally pushes the verb to third position.", tr:"Today I have no time."}
        ]},
        { id: "de_b1_g10", type: "grammar", title: "Grammar: Infinitive with 'zu'", lesson: "Many expressions attach an infinitive clause with zu, and the zu + infinitive goes to the end, usually after a comma: Ich habe keine Zeit, ins Kino zu gehen (I have no time to go to the movies). Common triggers: hoffen, versuchen, vergessen, and 'Es ist + adjective': Es ist wichtig, jeden Tag zu üben (It's important to practice every day); Ich hoffe, dich bald zu sehen (I hope to see you soon).\n\nWith separable verbs, zu squeezes BETWEEN prefix and stem: aufstehen → früh aufzustehen (to get up early).\n\nModal verbs (and a few others like lassen, sehen, hören, gehen) take a bare infinitive with NO zu: Ich kann schwimmen. Finally, um … zu expresses purpose (in order to): Ich lerne Deutsch, um in Berlin zu arbeiten (I'm learning German in order to work in Berlin).", items: [
          {q:"Ich habe keine Zeit, ins Kino ___ gehen.", c:["zu","um zu","für","zum"], a:0, x:"Expressions like keine Zeit/Lust haben attach an infinitive clause with zu placed before the infinitive at the end: …, ins Kino zu gehen. Um zu would add purpose ('in order to'), which makes no sense after 'no time'.", tr:"I have no time to go to the movies."},
          {q:"Which verbs do NOT use 'zu' before the infinitive?", c:["modal verbs","versuchen","hoffen","vergessen"], a:0, x:"Modal verbs take a bare infinitive with NO zu (Ich kann schwimmen), as do lassen, sehen, hören and gehen. Versuchen, hoffen and vergessen all require a zu-infinitive: Ich versuche zu schlafen.", ex:"Ich kann sehr gut schwimmen.", tr:"I can swim very well."},
          {q:"Es ist wichtig, jeden Tag ___ üben.", c:["zu","-","um","für zu"], a:0, x:"The pattern 'Es ist + adjective' triggers a zu-infinitive clause: Es ist wichtig, jeden Tag zu üben. Dropping zu is allowed only after modals and verbs like lassen; um … zu would wrongly add a purpose meaning.", tr:"It is important to practice every day."},
          {q:"With separable verbs, 'zu' goes:", c:["between prefix and stem (aufzustehen)","before the whole verb","after the verb","it is dropped"], a:0, x:"With separable verbs, zu slips BETWEEN prefix and stem, all written as one word: aufstehen → früh aufzustehen. Writing 'zu aufstehen' as two words is the classic error; inseparable verbs keep zu in front (zu besuchen).", ex:"Ich versuche, früh aufzustehen.", tr:"I try to get up early."},
          {q:"'Um … zu' expresses:", c:["a purpose (in order to)","a reason (because)","a contrast","a time"], a:0, x:"Um … zu + infinitive expresses purpose — English 'in order to': Ich lerne Deutsch, um in Berlin zu arbeiten. A reason ('because') would instead need a weil-clause with its own subject and conjugated verb.", ex:"Ich lerne Deutsch, um in Berlin zu arbeiten.", tr:"I am learning German in order to work in Berlin."},
          {q:"Ich hoffe, dich bald ___.", c:["zu sehen","sehen","zum Sehen","sehe"], a:0, x:"Hoffen is one of the verbs that take a zu-infinitive clause: Ich hoffe, dich bald zu sehen — zu + infinitive stands at the end. A bare infinitive ('dich bald sehen') is reserved for modals and verbs like lassen or hören.", tr:"I hope to see you soon."}
        ]},
        { id: "de_b1_g11", type: "grammar", title: "Grammar: Konjunktiv (subjunctive)", lesson: "Konjunktiv II expresses unreal situations and politeness. Key forms: sein → wäre, haben → hätte, können → könnte. Unreal condition: Wenn ich reich wäre, würde ich reisen (If I were rich, I would travel). For most other verbs, use würde + infinitive instead of a special form: ich würde gehen.\n\nPoliteness uses the same forms: Könnten Sie mir helfen? (Could you help me?), Ich hätte gern einen Kaffee (I'd like a coffee).\n\nThe unreal PAST combines hätte/wäre with the Partizip II: Wenn ich das gewusst hätte, wäre ich gekommen (If I had known, I would have come). With a modal it becomes a double infinitive: Ich hätte früher kommen sollen (I should have come earlier).\n\nKonjunktiv I (er sagt, er sei krank — he says he is sick) is mainly for indirect speech in formal or news writing.", items: [
          {q:"Polite request: ___ Sie mir helfen?", c:["Könnten","Konnten","Können würden","Gekonnt"], a:0, x:"Polite requests use Konjunktiv II; for können that is könnte(n): Könnten Sie mir helfen? The umlaut carries the politeness — konnten without it is the plain Präteritum 'were able to', a statement about the past.", tr:"Could you help me?"},
          {q:"Wenn ich reich ___, würde ich reisen.", c:["wäre","bin","war","sei"], a:0, x:"Unreal conditions put Konjunktiv II in the wenn-clause: sein → wäre — Wenn ich reich wäre, würde ich reisen. Bin and war state real facts, and sei is Konjunktiv I, which is reserved for reported speech.", tr:"If I were rich, I would travel."},
          {q:"The würde-form is used:", c:["as a substitute for most verbs' Konjunktiv II","only in questions","for the past","only with modals"], a:0, x:"Most verbs' original Konjunktiv II forms sound stilted, so German substitutes würde + infinitive: ich würde gehen. Only common verbs — wäre, hätte, könnte, müsste, wüsste — regularly keep their own forms.", ex:"Ich würde gern mehr reisen.", tr:"I would like to travel more."},
          {q:"Ich ___ gern einen Kaffee. (höfliche Bitte)", c:["hätte","habe","hatte","hätten"], a:0, x:"Polite wishes and orders use Konjunktiv II hätte + gern: Ich hätte gern einen Kaffee. Habe (present) states a fact and hatte a real past; only the umlauted hätte gives the polite 'would like' formula.", tr:"I would like a coffee."},
          {q:"Missed opportunity: Ich ___ früher kommen ___.", c:["hätte … sollen","habe … sollen","wäre … sollen","hätte … gesollt"], a:0, x:"A missed obligation uses hätte + DOUBLE INFINITIVE: Ich hätte früher kommen sollen. With a second verb present, the modal stays an infinitive (sollen), never the participle gesollt; habe would make it a real past.", tr:"I should have come earlier."},
          {q:"Konjunktiv I (er sagt, er sei krank) is mainly used for:", c:["indirect speech in formal/written German","polite requests","unreal wishes","commands"], a:0, x:"Konjunktiv I (er sei, er habe, er komme) marks indirect speech, signalling 'this is what he SAYS' without vouching for it — standard in news and formal writing. Politeness and unreal wishes use Konjunktiv II instead.", ex:"Er sagt, er sei krank.", tr:"He says he is sick."},
          {q:"Wenn ich das gewusst ___, wäre ich gekommen.", c:["hätte","habe","hatte","würde"], a:0, x:"The unreal past is built with hätte/wäre + Partizip II: Wenn ich das gewusst hätte, wäre ich gekommen. Hatte would state a real past fact; as a subclause, the wenn-clause puts the auxiliary at the very end.", tr:"If I had known that, I would have come."}
        ]},
        { id: "de_b1_g12", type: "grammar", title: "Grammar: Tenses – Plusquamperfekt & Futur", lesson: "The Plusquamperfekt is the 'past before the past': hatte or war + Partizip II. It pairs naturally with nachdem: Nachdem er gegessen hatte, ging er ins Bett (After he had eaten, he went to bed). Movement verbs use war: Als sie ankam, war der Zug schon abgefahren (When she arrived, the train had already departed).\n\nFutur I = werden + infinitive: Ich werde kommen (I will come). Besides the future, it also expresses an assumption about the PRESENT, often with wohl: Er wird wohl krank sein (He's probably sick).\n\nFutur II = werden + Partizip II + haben/sein, and expresses an assumption that something is already completed: Er wird angekommen sein (He will have arrived).", items: [
          {q:"The 'past before the past' is the:", c:["Plusquamperfekt","Perfekt","Präteritum","Futur II"], a:0, x:"The Plusquamperfekt expresses a past event BEFORE another past event: hatte/war + Partizip II — Er hatte gegessen, bevor ich kam. Perfekt and Präteritum are ordinary pasts; Futur II looks forward, not further back.", ex:"Er hatte gegessen, bevor ich kam.", tr:"He had eaten before I came."},
          {q:"Nachdem er gegessen ___, ging er ins Bett.", c:["hatte","hat","ist","war"], a:0, x:"Nachdem demands one tense step back: its clause takes the Plusquamperfekt (gegessen hatte) while the main clause uses the Präteritum (ging). Hat gegessen (Perfekt) would put both events on the same time level.", tr:"After he had eaten, he went to bed."},
          {q:"Futur I is formed with:", c:["werden + infinitive","haben + Partizip","sein + infinitive","würde + Partizip"], a:0, x:"Futur I = conjugated werden in position 2 + infinitive at the end: Ich werde kommen. Haben/sein + Partizip build past tenses, and würde + infinitive is Konjunktiv II ('would come'), not the future.", ex:"Ich werde dich morgen anrufen.", tr:"I will call you tomorrow."},
          {q:"'Er wird wohl krank sein' expresses:", c:["an assumption about the present","a certain future","a command","a wish"], a:0, x:"Werden + infinitive also expresses an ASSUMPTION about the present, typically flagged by wohl: Er wird wohl krank sein = he is probably sick. Without that reading, the same form is a plain future prediction.", ex:"Er wird wohl krank sein.", tr:"He is probably sick."},
          {q:"Futur II ('Er wird angekommen sein') expresses:", c:["an assumption that something is already completed","a plan","an obligation","a repeated action"], a:0, x:"Futur II = werden + Partizip II + haben/sein, presenting an action as already COMPLETED — usually an assumption: Er wird (inzwischen) angekommen sein = he will/must have arrived by now.", ex:"Er wird angekommen sein.", tr:"He will have arrived."},
          {q:"Als sie ankam, ___ der Zug schon abgefahren.", c:["war","ist","hatte","wurde"], a:0, x:"The departure happened BEFORE she arrived, so the Plusquamperfekt is required; abfahren is a movement verb and takes sein, hence war abgefahren. Ist abgefahren (Perfekt) would lose the earlier-than-past meaning.", tr:"When she arrived, the train had already departed."}
        ]},
        { id: "de_b1_g13", type: "grammar", title: "Grammar: Passive voice & nominalization", lesson: "German has two passives. The Vorgangspassiv (process passive) = werden + Partizip II and describes an action in progress: Das Fenster wird geöffnet (The window is being opened). The Zustandspassiv (state passive) = sein + Partizip II and describes the RESULT: Das Geschäft ist geschlossen (The store is closed).\n\nPast forms of the process passive: Präteritum wurde + Partizip II — Das Auto wurde repariert (The car was repaired); Perfekt: Das Auto ist repariert worden — note that geworden shortens to worden in the passive.\n\nThe agent (the doer) is introduced with von + Dativ: Das Buch wurde von ihr geschrieben (The book was written by her).\n\nLastly, any infinitive can be capitalized into a neuter noun: das Lernen (the learning), das Essen.", items: [
          {q:"The Vorgangspassiv (process passive) is formed with:", c:["werden + Partizip II","sein + Partizip II","haben + Partizip II","werden + infinitive"], a:0, x:"The Vorgangspassiv (process passive) = werden + Partizip II and shows an action being carried out: Das Haus wird gebaut. Sein + Partizip II is the Zustandspassiv, which describes only the finished state.", ex:"Das Haus wird gerade gebaut.", tr:"The house is being built right now."},
          {q:"Das Fenster ___ geöffnet. (someone is opening it right now)", c:["wird","ist","hat","war"], a:0, x:"An action in progress needs the process passive with werden: Das Fenster wird geöffnet (someone is opening it now). Ist geöffnet would be the state passive — the window simply stands open, with no one acting.", tr:"The window is being opened."},
          {q:"'Das Geschäft ist geschlossen' is the:", c:["Zustandspassiv (state passive)","Vorgangspassiv","Perfekt active","Konjunktiv"], a:0, x:"Sein + Partizip II forms the Zustandspassiv: it describes the STATE resulting from a finished action — the store is (now) closed. The action itself ('is being closed') would need werden: wird geschlossen.", ex:"Das Geschäft ist geschlossen.", tr:"The store is closed."},
          {q:"Passive past (Präteritum): Das Auto ___ repariert.", c:["wurde","wird","ist worden","war werden"], a:0, x:"The Präteritum passive conjugates werden in the simple past: wurde + Partizip II — Das Auto wurde repariert. Wird is present ('is being repaired'), and 'ist worden' is incomplete without the participle.", tr:"The car was repaired."},
          {q:"Passive Perfekt: Das Auto ist repariert ___.", c:["worden","geworden","werden","gewesen"], a:0, x:"In the passive Perfekt, the participle of werden drops its ge-: Das Auto ist repariert worden. Full geworden appears only when werden means 'to become' (Er ist Arzt geworden) — that is the giveaway.", tr:"The car has been repaired."},
          {q:"The agent in a passive sentence is introduced by:", c:["von","mit","aus","bei"], a:0, x:"The agent (the doer) of a passive sentence is introduced by von + Dativ: Das Buch wurde von ihr geschrieben. Mit marks the instrument instead (mit einem Stift), not the person acting.", ex:"Das Buch wurde von ihr geschrieben.", tr:"The book was written by her."},
          {q:"Nominalized verb: 'das Lernen' means:", c:["(the) learning","the lesson","the student","the teacher"], a:0, x:"Any infinitive can be nominalized: capitalize it and it becomes a neuter noun naming the activity — das Lernen = (the) learning, das Essen = (the) eating/food. It names the activity, not the person doing it.", ex:"Das Lernen macht mir Spaß.", tr:"Learning is fun for me."}
        ]},
        { id: "de_b1_g14", type: "grammar", title: "Grammar: Modal verb combinations", lesson: "When a modal verb appears in the Perfekt together with another verb, German uses the DOUBLE INFINITIVE instead of a participle: Ich habe arbeiten müssen (I had to work) — not 'gemusst'. The unreal past works the same way with hätte: Das hätte er nicht tun sollen (He shouldn't have done that). Only when the modal stands ALONE does it use its participle: Nicht jeder hätte das gekonnt! (Not everyone could have done that!)\n\nModals also combine with the passive: modal + Partizip II + werden: Das Problem muss gelöst werden (The problem must be solved). Longer chains simply stack the infinitives at the end: Das muss bis morgen gemacht werden können.\n\nOne famous exception to verb-final order: in a subclause with a double infinitive, haben moves BEFORE the two infinitives: …, weil ich habe arbeiten müssen.", items: [
          {q:"Das hätte er nicht tun ___.", c:["sollen","gesollt","soll","sollte"], a:0, x:"In the unreal past, a modal with another verb forms a DOUBLE INFINITIVE after hätte: Das hätte er nicht tun sollen. The participle gesollt is used only when the modal stands alone; sollte would be simple past.", tr:"He shouldn't have done that."},
          {q:"Modal in the passive: Das Problem muss gelöst ___.", c:["werden","worden","sein","haben"], a:0, x:"A modal combines with the passive as modal + Partizip II + werden (infinitive) at the end: Das Problem muss gelöst werden. Worden belongs only to the passive Perfekt (ist gelöst worden); sein would describe a state.", tr:"The problem must be solved."},
          {q:"Perfekt with modal + verb: Ich habe arbeiten ___.", c:["müssen","gemusst","musste","muss"], a:0, x:"A modal in the Perfekt with a main verb takes the double infinitive: Ich habe arbeiten müssen — never 'gemusst' when another verb is present. Musste is the one-word Präteritum and cannot follow habe.", tr:"I had to work."},
          {q:"Nicht jeder ___ das gekonnt! (hätte/Konjunktiv)", c:["hätte","wäre","hat","ist"], a:0, x:"Here the modal stands ALONE (no second verb), so it uses its normal participle: hätte gekonnt = would have been able to. Modals always form their perfect with haben, never sein — so wäre is out.", tr:"Not everyone could have done that!"},
          {q:"Das muss bis morgen gemacht werden ___. (assumption + necessity, K II)", c:["können","müssen","dürfen","wollen"], a:0, x:"Longer chains simply stack infinitives at the end: muss + gemacht werden (passive) + können = 'it must be POSSIBLE to get it done'. Können adds possibility; müssen would pointlessly double the necessity already in muss.", tr:"It must be possible to get that done by tomorrow."},
          {q:"In a subclause with a double infinitive, the auxiliary 'haben' goes:", c:["BEFORE the two infinitives","at the very end","in position 2","is dropped"], a:0, x:"Famous exception to verb-final order: in a subclause containing a double infinitive, the auxiliary haben stands BEFORE the two infinitives — …, weil ich habe arbeiten müssen — not at the very end.", ex:"Ich war müde, weil ich habe arbeiten müssen.", tr:"I was tired because I had to work."}
        ]},
        // ---------- A2/B1 VOCAB ----------
        { id: "de_b1_v1", type: "vocab", title: "Vocab: Connectors & conjunctions", items: [
          {t:"weil", e:"because"}, {t:"denn", e:"because / for"}, {t:"deshalb", e:"therefore"},
          {t:"trotzdem", e:"nevertheless"}, {t:"obwohl", e:"although"}, {t:"während", e:"while / during"},
          {t:"bevor", e:"before"}, {t:"nachdem", e:"after"}, {t:"seitdem", e:"since then"},
          {t:"damit", e:"so that"}, {t:"falls", e:"in case"}, {t:"sobald", e:"as soon as"},
          {t:"außerdem", e:"besides / moreover"}, {t:"allerdings", e:"however"},
          {t:"zuerst", e:"first"}, {t:"danach", e:"afterwards"}, {t:"schließlich", e:"finally"},
          {t:"entweder … oder", e:"either … or"}, {t:"weder … noch", e:"neither … nor"},
          {t:"nicht nur … sondern auch", e:"not only … but also"}, {t:"zwar … aber", e:"admittedly … but"},
          {t:"je … desto", e:"the … the (more)"}
        ]},
        { id: "de_b1_v2", type: "vocab", title: "Vocab: Verbs with fixed prepositions", items: [
          {t:"warten auf", e:"to wait for"}, {t:"denken an", e:"to think of"},
          {t:"sich freuen auf", e:"to look forward to"}, {t:"sich freuen über", e:"to be happy about"},
          {t:"sich interessieren für", e:"to be interested in"}, {t:"sich ärgern über", e:"to be annoyed about"},
          {t:"sich erinnern an", e:"to remember"}, {t:"sich kümmern um", e:"to take care of"},
          {t:"träumen von", e:"to dream of"}, {t:"sprechen über", e:"to talk about"},
          {t:"abhängen von", e:"to depend on"}, {t:"teilnehmen an", e:"to take part in"},
          {t:"sich bewerben um", e:"to apply for"}, {t:"sich entschuldigen für", e:"to apologize for"},
          {t:"Angst haben vor", e:"to be afraid of"}, {t:"fragen nach", e:"to ask about"},
          {t:"sich unterhalten über", e:"to converse about"}, {t:"gratulieren zu", e:"to congratulate on"},
          {t:"sich verlieben in", e:"to fall in love with"}, {t:"suchen nach", e:"to search for"}
        ]},
        { id: "de_b1_v3", type: "vocab", title: "Vocab: Opinions & discussion", items: [
          {t:"die Meinung", e:"the opinion"}, {t:"meiner Meinung nach", e:"in my opinion"},
          {t:"ich glaube", e:"I believe"}, {t:"ich finde", e:"I find / think"},
          {t:"zustimmen", e:"to agree"}, {t:"widersprechen", e:"to contradict"},
          {t:"der Vorteil", e:"the advantage"}, {t:"der Nachteil", e:"the disadvantage"},
          {t:"einerseits", e:"on the one hand"}, {t:"andererseits", e:"on the other hand"},
          {t:"der Grund", e:"the reason"}, {t:"das Beispiel", e:"the example"},
          {t:"zum Beispiel", e:"for example"}, {t:"wichtig", e:"important"},
          {t:"unwichtig", e:"unimportant"}, {t:"richtig", e:"correct"}, {t:"falsch", e:"wrong"},
          {t:"vielleicht", e:"maybe"}, {t:"wahrscheinlich", e:"probably"}, {t:"sicher", e:"certainly"},
          {t:"die Erfahrung", e:"the experience"}, {t:"vorschlagen", e:"to suggest"},
          {t:"empfehlen", e:"to recommend"}, {t:"entscheiden", e:"to decide"}
        ]}
      ]
    }
  ]
};
