// German idioms & useful phrases for the Idioms Test and Useful Phrases quizzes.
window.QUIZ_IDIOMS = window.QUIZ_IDIOMS || {};
window.QUIZ_IDIOMS.german = [
  {t:"Das ist mir Wurst.", e:"I don't care", lit:"that's sausage to me", hint:"very common; casual register"},
  {t:"Ich verstehe nur Bahnhof.", e:"it's all Greek to me", lit:"I only understand train station", hint:"casual; total incomprehension"},
  {t:"Jemandem die Daumen drücken", e:"to keep one's fingers crossed for someone", lit:"to press the thumbs for someone", hint:"Germans press thumbs instead of crossing fingers"},
  {t:"Schwein haben", e:"to be lucky", lit:"to have pig", hint:"casual; luck you didn't earn"},
  {t:"Blau machen", e:"to skip work or school", lit:"to make blue", hint:"casual; playing hooky"},
  {t:"Die Nase voll haben", e:"to be fed up", lit:"to have the nose full", hint:"often 'die Nase voll haben von' + thing"},
  {t:"Tomaten auf den Augen haben", e:"to be oblivious to the obvious", lit:"to have tomatoes on the eyes", hint:"casual; missing what's right in front of you"},
  {t:"Um den heißen Brei herumreden", e:"to beat around the bush", lit:"to talk around the hot porridge", hint:"used when someone won't get to the point"},
  {t:"Ins Gras beißen", e:"to kick the bucket, to die", lit:"to bite into the grass", hint:"very casual, even crude; also 'fail badly'"},
  {t:"Die Kirche im Dorf lassen", e:"to not get carried away", lit:"to leave the church in the village", hint:"telling someone not to exaggerate"},
  {t:"Da steppt der Bär.", e:"it's a great party, the place is buzzing", lit:"the bear tap-dances there", hint:"casual; lively event"},
  {t:"Zwei Fliegen mit einer Klappe schlagen", e:"to kill two birds with one stone", lit:"to hit two flies with one swatter", hint:"neutral register; efficiency"},
  {t:"Die Katze im Sack kaufen", e:"to buy a pig in a poke", lit:"to buy the cat in the sack", hint:"buying without checking first"},
  {t:"Da liegt der Hund begraben.", e:"that's the crux of the matter", lit:"that's where the dog is buried", hint:"the real hidden problem"},
  {t:"Jemandem auf den Keks gehen", e:"to get on someone's nerves", lit:"to walk on someone's cookie", hint:"casual; 'Du gehst mir auf den Keks!'"},
  {t:"Es ist nicht alles Gold, was glänzt.", e:"all that glitters is not gold", lit:"not everything that shines is gold", hint:"proverb; appearances deceive"},
  {t:"Den Nagel auf den Kopf treffen", e:"to hit the nail on the head", lit:"to hit the nail on the head", hint:"exact English equivalent"},
  {t:"Alles in Butter", e:"everything is fine", lit:"everything in butter", hint:"casual; 'Alles in Butter?' = all good?"},
  {t:"Das Haar in der Suppe suchen", e:"to nitpick, to look for faults", lit:"to look for the hair in the soup", hint:"chronic fault-finding"},
  {t:"Seinen Senf dazugeben", e:"to put in one's two cents", lit:"to add one's mustard", hint:"casual; unsolicited opinions"},
  {t:"Nicht alle Tassen im Schrank haben", e:"to be crazy", lit:"to not have all cups in the cupboard", hint:"casual insult; 'Hast du nicht alle Tassen im Schrank?'"},
  {t:"Einen Vogel haben", e:"to be nuts", lit:"to have a bird", hint:"casual; tapping the forehead gesture goes with it"},
  {t:"Auf Wolke sieben schweben", e:"to be on cloud nine", lit:"to float on cloud seven", hint:"usually about being in love"},
  {t:"Jemanden auf den Arm nehmen", e:"to pull someone's leg", lit:"to take someone on the arm", hint:"teasing, not malicious"},
  {t:"Die Beine in die Hand nehmen", e:"to run for it, to hurry", lit:"to take the legs into the hand", hint:"casual; fleeing or rushing"},
  {t:"Hals über Kopf", e:"headlong, in a mad rush", lit:"neck over head", hint:"'sich Hals über Kopf verlieben' = fall head over heels"},
  {t:"Unter vier Augen", e:"in private, one-on-one", lit:"under four eyes", hint:"neutral; 'ein Gespräch unter vier Augen'"},
  {t:"Auf dem Holzweg sein", e:"to be barking up the wrong tree", lit:"to be on the wood path", hint:"a Holzweg is a logging track that leads nowhere"},
  {t:"Aus allen Wolken fallen", e:"to be completely flabbergasted", lit:"to fall from all clouds", hint:"sudden unpleasant surprise"},
  {t:"Den Faden verlieren", e:"to lose one's train of thought", lit:"to lose the thread", hint:"common while speaking or presenting"},
  {t:"Das fünfte Rad am Wagen sein", e:"to be the third wheel", lit:"to be the fifth wheel on the wagon", hint:"feeling superfluous in a group"},
  {t:"Jemandem Löcher in den Bauch fragen", e:"to pepper someone with questions", lit:"to ask holes into someone's belly", hint:"often said about curious children"},
  {t:"Sich auf die Socken machen", e:"to get going, to head out", lit:"to get onto one's socks", hint:"casual; time to leave"},
  {t:"Die Flinte ins Korn werfen", e:"to throw in the towel", lit:"to throw the shotgun into the grain", hint:"giving up too early; often negated as advice"},
  {t:"Jemandem einen Bären aufbinden", e:"to tell someone a tall tale", lit:"to tie a bear onto someone", hint:"fooling someone with a made-up story"},
  {t:"Eine Extrawurst verlangen", e:"to demand special treatment", lit:"to demand an extra sausage", hint:"casual; mildly disapproving"},
  {t:"Kein Blatt vor den Mund nehmen", e:"to not mince words", lit:"to take no leaf before the mouth", hint:"speaking bluntly"},
  {t:"Etwas auf die lange Bank schieben", e:"to put something off, to procrastinate", lit:"to push something onto the long bench", hint:"from old court practice of shelving files"},
  {t:"Jetzt geht es um die Wurst.", e:"now it's crunch time", lit:"now it's about the sausage", hint:"the decisive moment; from fairground contests"},
  {t:"Klar wie Kloßbrühe", e:"crystal clear", lit:"clear as dumpling broth", hint:"ironic origin - broth is cloudy; casual"},
  {t:"Fix und fertig sein", e:"to be completely exhausted", lit:"to be fixed and finished", hint:"casual; physically or emotionally drained"},
  {t:"Die Ohren spitzen", e:"to prick up one's ears", lit:"to sharpen the ears", hint:"listening closely"},
  {t:"Auf großem Fuß leben", e:"to live large, beyond one's means", lit:"to live on a big foot", hint:"lavish lifestyle"},
  {t:"Ins Fettnäpfchen treten", e:"to put one's foot in one's mouth", lit:"to step into the little grease bowl", hint:"an embarrassing social blunder"},
  {t:"Jemandem den Kopf waschen", e:"to give someone a good telling-off", lit:"to wash someone's head", hint:"a scolding, not grooming"},
  {t:"Sich etwas hinter die Ohren schreiben", e:"to take something to heart, to remember it well", lit:"to write something behind one's ears", hint:"often a warning: 'Schreib dir das hinter die Ohren!'"},
  {t:"Wo sich Fuchs und Hase gute Nacht sagen", e:"in the middle of nowhere", lit:"where fox and hare say goodnight to each other", hint:"remote places; humorous"},
  {t:"Ein Auge zudrücken", e:"to turn a blind eye", lit:"to press one eye shut", hint:"leniency; 'beide Augen zudrücken' = even more lenient"},
  {t:"Wie ein Elefant im Porzellanladen", e:"like a bull in a china shop", lit:"like an elephant in the porcelain shop", hint:"clumsy, tactless behavior"},
  {t:"Das A und O", e:"the be-all and end-all, the most important thing", lit:"the A and O", hint:"from alpha and omega; very common"},
  {t:"Nur die Spitze des Eisbergs", e:"only the tip of the iceberg", lit:"only the tip of the iceberg", hint:"exact English equivalent"},
  {t:"Öl ins Feuer gießen", e:"to add fuel to the fire", lit:"to pour oil into the fire", hint:"making a conflict worse"},
  {t:"Wie auf Kohlen sitzen", e:"to be on tenterhooks", lit:"to sit as if on hot coals", hint:"nervous impatience, e.g. waiting"},
  {t:"Etwas aus dem Ärmel schütteln", e:"to do something off the cuff", lit:"to shake something out of the sleeve", hint:"effortless improvisation"},
  {t:"Jemanden durch den Kakao ziehen", e:"to make fun of someone", lit:"to pull someone through the cocoa", hint:"casual; mocking, often behind their back"},
  {t:"Sich aus dem Staub machen", e:"to make oneself scarce, to clear off", lit:"to make oneself out of the dust", hint:"casual; leaving quickly, often to avoid something"},
  {t:"Etwas auf Herz und Nieren prüfen", e:"to test something thoroughly", lit:"to test something on heart and kidneys", hint:"rigorous checking; biblical origin"},
  {t:"Mit dem falschen Fuß aufstehen", e:"to get up on the wrong side of the bed", lit:"to get up with the wrong foot", hint:"explaining a bad mood"},
  {t:"Über seinen Schatten springen", e:"to overcome one's own reluctance", lit:"to jump over one's own shadow", hint:"doing what's hard for your character"},
  {t:"Nah am Wasser gebaut sein", e:"to cry easily", lit:"to be built close to the water", hint:"gentle, slightly teasing"},
  {t:"Ein dickes Fell haben", e:"to have a thick skin", lit:"to have a thick fur", hint:"unbothered by criticism"},
  {t:"Auf der Leitung stehen", e:"to be slow on the uptake", lit:"to stand on the line", hint:"casual; momentary mental block"},
  {t:"Aus einer Mücke einen Elefanten machen", e:"to make a mountain out of a molehill", lit:"to make an elephant out of a mosquito", hint:"blowing things out of proportion"},
  {t:"Sich in die Nesseln setzen", e:"to get oneself into hot water", lit:"to sit down into the nettles", hint:"self-inflicted trouble"},
  {t:"Das Kind mit dem Bade ausschütten", e:"to throw the baby out with the bathwater", lit:"to pour out the child with the bath", hint:"overcorrecting and losing the good part"},
  {t:"Perlen vor die Säue werfen", e:"to cast pearls before swine", lit:"to throw pearls before the sows", hint:"biblical; wasted effort on the unappreciative"},
  {t:"In den sauren Apfel beißen", e:"to bite the bullet", lit:"to bite into the sour apple", hint:"doing something unpleasant but necessary"},
  {t:"Jemandem ein X für ein U vormachen", e:"to hoodwink someone", lit:"to show someone an X for a U", hint:"from Roman numerals V and X on tavern bills"},
  {t:"Mit Kanonen auf Spatzen schießen", e:"to use a sledgehammer to crack a nut", lit:"to shoot at sparrows with cannons", hint:"disproportionate response"},
  {t:"Da beißt die Maus keinen Faden ab.", e:"there's no way around it", lit:"the mouse bites no thread off of that", hint:"a fact that can't be changed"},
  {t:"Sich kein Bein ausreißen", e:"to not overexert oneself", lit:"to not tear out one's own leg", hint:"casual; mildly critical of low effort"},
  {t:"Auf Nummer sicher gehen", e:"to play it safe", lit:"to go on number safe", hint:"very common; cautious choice"},
  {t:"Etwas an die große Glocke hängen", e:"to broadcast something to everyone", lit:"to hang something on the big bell", hint:"usually negated: don't spread it around"},
  {t:"Wie am Schnürchen laufen", e:"to run like clockwork", lit:"to run as if on a little string", hint:"everything going smoothly"},
  {t:"Den Wald vor lauter Bäumen nicht sehen", e:"to not see the forest for the trees", lit:"to not see the forest because of all the trees", hint:"missing the obvious whole"},
  {t:"Jemandem Honig ums Maul schmieren", e:"to butter someone up", lit:"to smear honey around someone's mouth", hint:"casual; insincere flattery"},
  {t:"Auf eigene Faust", e:"on one's own initiative", lit:"on one's own fist", hint:"'auf eigene Faust reisen' = travel independently"},
  {t:"Mir fällt ein Stein vom Herzen.", e:"that's a weight off my mind", lit:"a stone falls from my heart", hint:"relief after worry"},
  {t:"Das Eis brechen", e:"to break the ice", lit:"to break the ice", hint:"exact English equivalent"},
  {t:"Aller Anfang ist schwer.", e:"every beginning is hard", lit:"all beginning is hard", hint:"proverb; encouragement for beginners"},
  {t:"Übung macht den Meister.", e:"practice makes perfect", lit:"practice makes the master", hint:"proverb; very common"},
  {t:"Wer A sagt, muss auch B sagen.", e:"in for a penny, in for a pound", lit:"who says A must also say B", hint:"proverb; finish what you started"},
  {t:"Morgenstund hat Gold im Mund.", e:"the early bird catches the worm", lit:"morning hour has gold in its mouth", hint:"proverb; slightly old-fashioned"},
  {t:"Man soll den Tag nicht vor dem Abend loben.", e:"don't count your chickens before they hatch", lit:"one should not praise the day before the evening", hint:"proverb; caution against early celebration"},
  {t:"Hunde, die bellen, beißen nicht.", e:"barking dogs seldom bite", lit:"dogs that bark do not bite", hint:"proverb; loud threats are empty"},
  {t:"Lügen haben kurze Beine.", e:"lies don't travel far", lit:"lies have short legs", hint:"proverb; lies are soon found out"},
  {t:"Was Hänschen nicht lernt, lernt Hans nimmermehr.", e:"you can't teach an old dog new tricks", lit:"what little Hans doesn't learn, Hans never learns", hint:"proverb; learn while young"},
  {t:"Ende gut, alles gut.", e:"all's well that ends well", lit:"end good, everything good", hint:"proverb; exact equivalent"},
  {t:"In der Not frisst der Teufel Fliegen.", e:"beggars can't be choosers", lit:"in need the devil eats flies", hint:"proverb; making do in hard times"},
  {t:"Kleinvieh macht auch Mist.", e:"every little bit helps", lit:"small livestock also makes manure", hint:"proverb; earthy but common"},
  {t:"Den Teufel an die Wand malen", e:"to tempt fate, to imagine the worst", lit:"to paint the devil on the wall", hint:"often: 'Mal den Teufel nicht an die Wand!'"},
  {t:"Sich ins gemachte Nest setzen", e:"to have everything handed to one", lit:"to sit down into the ready-made nest", hint:"benefiting from others' work; disapproving"},
  {t:"Eine Leiche im Keller haben", e:"to have a skeleton in the closet", lit:"to have a corpse in the cellar", hint:"a hidden embarrassing secret"},
  {t:"Schnee von gestern", e:"old news, water under the bridge", lit:"snow from yesterday", hint:"'Das ist Schnee von gestern.' = it no longer matters"},
  {t:"Bekannt sein wie ein bunter Hund", e:"to be known all over town", lit:"to be known like a colorful dog", hint:"casual; conspicuous, everyone knows them"},
  {t:"Am Ball bleiben", e:"to stay on the ball, to keep at it", lit:"to stay on the ball", hint:"from soccer; persistence"},
  {t:"Etwas durch die Blume sagen", e:"to say something indirectly", lit:"to say something through the flower", hint:"hinting politely instead of stating bluntly"},
  {t:"Halt die Ohren steif!", e:"keep your chin up", lit:"hold the ears stiff", hint:"casual farewell of encouragement"},
  {t:"Auf den Hund kommen", e:"to go to the dogs, to fall on hard times", lit:"to come onto the dog", hint:"decline in fortune or health"},
  {t:"Jemandem ein Dorn im Auge sein", e:"to be a thorn in someone's side", lit:"to be a thorn in someone's eye", hint:"a constant annoyance"},
  {t:"Kalte Füße bekommen", e:"to get cold feet", lit:"to get cold feet", hint:"exact equivalent; backing out at the last minute"},
  {t:"Die Karten auf den Tisch legen", e:"to lay one's cards on the table", lit:"to lay the cards on the table", hint:"full honesty about intentions"},
  {t:"Jemandem aus der Seele sprechen", e:"to say exactly what someone feels", lit:"to speak out of someone's soul", hint:"'Du sprichst mir aus der Seele!' = my thoughts exactly"}
];
window.QUIZ_PHRASES = window.QUIZ_PHRASES || {};
window.QUIZ_PHRASES.german = [
  {id:"restaurant", title:"Ordering at a restaurant", items:[
    {t:"Ich hätte gern die Speisekarte, bitte.", e:"I would like the menu, please."},
    {t:"Haben Sie einen Tisch für zwei Personen?", e:"Do you have a table for two people?"},
    {t:"Ich möchte gern bestellen.", e:"I would like to order."},
    {t:"Was können Sie empfehlen?", e:"What can you recommend?"},
    {t:"Ich nehme das Schnitzel mit Pommes.", e:"I'll have the schnitzel with fries."},
    {t:"Ein großes Wasser ohne Kohlensäure, bitte.", e:"A large still water, please."},
    {t:"Gibt es auch vegetarische Gerichte?", e:"Are there also vegetarian dishes?"},
    {t:"Ich bin allergisch gegen Nüsse.", e:"I am allergic to nuts."},
    {t:"Könnten wir noch etwas Brot bekommen?", e:"Could we get some more bread?"},
    {t:"Das Essen war ausgezeichnet.", e:"The food was excellent."},
    {t:"Die Rechnung, bitte.", e:"The check, please."},
    {t:"Können wir getrennt zahlen?", e:"Can we pay separately?"},
    {t:"Kann ich mit Karte zahlen?", e:"Can I pay by card?"},
    {t:"Stimmt so.", e:"Keep the change."}
  ]},
  {id:"directions", title:"Directions & transport", items:[
    {t:"Entschuldigung, wie komme ich zum Bahnhof?", e:"Excuse me, how do I get to the train station?"},
    {t:"Ist es weit von hier?", e:"Is it far from here?"},
    {t:"Gehen Sie geradeaus und dann die zweite Straße links.", e:"Go straight ahead and then take the second street on the left."},
    {t:"Biegen Sie an der Ampel rechts ab.", e:"Turn right at the traffic light."},
    {t:"Können Sie mir das auf der Karte zeigen?", e:"Can you show me that on the map?"},
    {t:"Ich habe mich verlaufen.", e:"I have gotten lost."},
    {t:"Welche Linie fährt zum Flughafen?", e:"Which line goes to the airport?"},
    {t:"Wo ist die nächste U-Bahn-Station?", e:"Where is the nearest subway station?"},
    {t:"Muss ich umsteigen?", e:"Do I have to change trains?"},
    {t:"An welcher Haltestelle muss ich aussteigen?", e:"At which stop do I have to get off?"},
    {t:"Wie oft fährt der Bus?", e:"How often does the bus run?"},
    {t:"Können Sie mir bitte ein Taxi rufen?", e:"Can you please call me a taxi?"},
    {t:"Es ist gleich um die Ecke.", e:"It's just around the corner."}
  ]},
  {id:"shopping", title:"Shopping", items:[
    {t:"Ich schaue mich nur um, danke.", e:"I'm just looking around, thanks."},
    {t:"Wie viel kostet das?", e:"How much does this cost?"},
    {t:"Haben Sie das auch in einer anderen Größe?", e:"Do you have this in another size too?"},
    {t:"Haben Sie das auch in Blau?", e:"Do you have this in blue too?"},
    {t:"Kann ich das anprobieren?", e:"Can I try this on?"},
    {t:"Wo sind die Umkleidekabinen?", e:"Where are the fitting rooms?"},
    {t:"Das ist mir zu teuer.", e:"That is too expensive for me."},
    {t:"Gibt es darauf einen Rabatt?", e:"Is there a discount on this?"},
    {t:"Ich nehme es.", e:"I'll take it."},
    {t:"Kann ich das umtauschen, wenn es nicht passt?", e:"Can I exchange this if it doesn't fit?"},
    {t:"Könnte ich bitte eine Quittung bekommen?", e:"Could I get a receipt, please?"},
    {t:"Brauchen Sie eine Tüte?", e:"Do you need a bag?"},
    {t:"Wann schließen Sie heute?", e:"When do you close today?"}
  ]},
  {id:"hotel", title:"Hotel & accommodation", items:[
    {t:"Ich habe ein Zimmer reserviert.", e:"I have reserved a room."},
    {t:"Haben Sie noch ein Zimmer frei?", e:"Do you still have a room available?"},
    {t:"Ich möchte ein Doppelzimmer für drei Nächte.", e:"I would like a double room for three nights."},
    {t:"Ist das Frühstück im Preis inbegriffen?", e:"Is breakfast included in the price?"},
    {t:"Um wie viel Uhr gibt es Frühstück?", e:"At what time is breakfast served?"},
    {t:"Wie lautet das WLAN-Passwort?", e:"What is the Wi-Fi password?"},
    {t:"Die Heizung in meinem Zimmer funktioniert nicht.", e:"The heating in my room doesn't work."},
    {t:"Könnte ich bitte ein zusätzliches Handtuch bekommen?", e:"Could I please get an extra towel?"},
    {t:"Wann muss ich auschecken?", e:"When do I have to check out?"},
    {t:"Kann ich mein Gepäck hier lassen?", e:"Can I leave my luggage here?"},
    {t:"Gibt es einen Parkplatz am Hotel?", e:"Is there parking at the hotel?"},
    {t:"Könnten Sie mich bitte um sieben Uhr wecken?", e:"Could you please wake me at seven o'clock?"},
    {t:"Ich möchte mich über den Lärm beschweren.", e:"I would like to complain about the noise."}
  ]},
  {id:"smalltalk", title:"Greetings & small talk", items:[
    {t:"Wie geht es Ihnen?", e:"How are you? (formal)"},
    {t:"Danke, gut. Und Ihnen?", e:"Fine, thanks. And you? (formal)"},
    {t:"Ich heiße Anna. Und wie heißen Sie?", e:"My name is Anna. And what is your name?"},
    {t:"Freut mich, Sie kennenzulernen.", e:"Pleased to meet you."},
    {t:"Woher kommen Sie?", e:"Where are you from?"},
    {t:"Ich komme aus den USA.", e:"I come from the USA."},
    {t:"Was machen Sie beruflich?", e:"What do you do for a living?"},
    {t:"Sprechen Sie Englisch?", e:"Do you speak English?"},
    {t:"Ich lerne erst seit einem Jahr Deutsch.", e:"I have only been learning German for a year."},
    {t:"Können Sie bitte etwas langsamer sprechen?", e:"Can you please speak a bit more slowly?"},
    {t:"Schönes Wetter heute, oder?", e:"Nice weather today, isn't it?"},
    {t:"Wie war Ihr Wochenende?", e:"How was your weekend?"},
    {t:"Bis bald, und einen schönen Tag noch!", e:"See you soon, and have a nice day!"},
    {t:"Grüßen Sie Ihre Familie von mir.", e:"Give my regards to your family."}
  ]},
  {id:"emergency", title:"Emergencies & health", items:[
    {t:"Hilfe! Rufen Sie bitte die Polizei!", e:"Help! Please call the police!"},
    {t:"Rufen Sie einen Krankenwagen!", e:"Call an ambulance!"},
    {t:"Es ist ein Unfall passiert.", e:"An accident has happened."},
    {t:"Ich brauche einen Arzt.", e:"I need a doctor."},
    {t:"Wo ist die nächste Apotheke?", e:"Where is the nearest pharmacy?"},
    {t:"Ich fühle mich nicht wohl.", e:"I don't feel well."},
    {t:"Ich habe starke Kopfschmerzen.", e:"I have a bad headache."},
    {t:"Mir ist übel und schwindelig.", e:"I feel nauseous and dizzy."},
    {t:"Ich habe Fieber.", e:"I have a fever."},
    {t:"Haben Sie etwas gegen Halsschmerzen?", e:"Do you have something for a sore throat?"},
    {t:"Ich nehme regelmäßig Medikamente.", e:"I take medication regularly."},
    {t:"Mein Portemonnaie wurde gestohlen.", e:"My wallet was stolen."},
    {t:"Ich habe meinen Pass verloren.", e:"I have lost my passport."},
    {t:"Wo ist die Notaufnahme?", e:"Where is the emergency room?"}
  ]},
  {id:"phone", title:"Phone & appointments", items:[
    {t:"Guten Tag, hier spricht Frau Müller.", e:"Hello, this is Ms. Müller speaking."},
    {t:"Könnte ich bitte mit Herrn Schmidt sprechen?", e:"Could I please speak with Mr. Schmidt?"},
    {t:"Worum geht es denn?", e:"What is it about?"},
    {t:"Ich möchte einen Termin vereinbaren.", e:"I would like to make an appointment."},
    {t:"Hätten Sie am Dienstag um zehn Uhr Zeit?", e:"Would Tuesday at ten o'clock work for you?"},
    {t:"Leider muss ich den Termin absagen.", e:"Unfortunately, I have to cancel the appointment."},
    {t:"Können wir den Termin verschieben?", e:"Can we postpone the appointment?"},
    {t:"Er ist im Moment leider nicht erreichbar.", e:"Unfortunately, he is not available at the moment."},
    {t:"Kann ich eine Nachricht hinterlassen?", e:"Can I leave a message?"},
    {t:"Könnten Sie ihm ausrichten, dass ich angerufen habe?", e:"Could you tell him that I called?"},
    {t:"Ich rufe später noch einmal an.", e:"I will call again later."},
    {t:"Die Verbindung ist sehr schlecht.", e:"The connection is very bad."},
    {t:"Können Sie das bitte wiederholen?", e:"Can you please repeat that?"},
    {t:"Vielen Dank für Ihren Anruf. Auf Wiederhören!", e:"Thank you for your call. Goodbye! (on the phone)"}
  ]},
  {id:"opinions", title:"Opinions & feelings", items:[
    {t:"Meiner Meinung nach ist das eine gute Idee.", e:"In my opinion, that is a good idea."},
    {t:"Ich bin ganz Ihrer Meinung.", e:"I completely agree with you."},
    {t:"Da bin ich anderer Meinung.", e:"I disagree on that."},
    {t:"Ich bin mir nicht sicher.", e:"I am not sure."},
    {t:"Das kommt darauf an.", e:"That depends."},
    {t:"Einerseits ja, andererseits nein.", e:"On the one hand yes, on the other hand no."},
    {t:"Ich finde das sehr interessant.", e:"I find that very interesting."},
    {t:"Das gefällt mir überhaupt nicht.", e:"I don't like that at all."},
    {t:"Ich freue mich sehr darauf.", e:"I am really looking forward to it."},
    {t:"Ich mache mir Sorgen um ihn.", e:"I am worried about him."},
    {t:"Das ist mir egal.", e:"I don't care about that."},
    {t:"Ich habe keine Lust dazu.", e:"I don't feel like doing that."},
    {t:"Das hat mich sehr enttäuscht.", e:"That disappointed me a lot."},
    {t:"Was halten Sie davon?", e:"What do you think of that?"}
  ]},
  {id:"travel", title:"Travel & tickets", items:[
    {t:"Eine Fahrkarte nach Berlin, bitte.", e:"One ticket to Berlin, please."},
    {t:"Einfach oder hin und zurück?", e:"One-way or round trip?"},
    {t:"Wann fährt der nächste Zug nach München?", e:"When does the next train to Munich leave?"},
    {t:"Von welchem Gleis fährt der Zug ab?", e:"From which platform does the train depart?"},
    {t:"Der Zug hat zwanzig Minuten Verspätung.", e:"The train is twenty minutes late."},
    {t:"Ist dieser Platz noch frei?", e:"Is this seat still free?"},
    {t:"Ich möchte einen Fensterplatz reservieren.", e:"I would like to reserve a window seat."},
    {t:"Muss ich die Fahrkarte entwerten?", e:"Do I have to validate the ticket?"},
    {t:"Wo kann ich einchecken?", e:"Where can I check in?"},
    {t:"Wie viel Gepäck darf ich mitnehmen?", e:"How much luggage am I allowed to take?"},
    {t:"Mein Flug wurde gestrichen.", e:"My flight was cancelled."},
    {t:"Ich habe meinen Anschluss verpasst.", e:"I missed my connection."},
    {t:"Wo kann ich ein Auto mieten?", e:"Where can I rent a car?"},
    {t:"Gute Reise!", e:"Have a good trip!"}
  ]}
];
